import { c, defineStyle } from "./define";

/** Illustration approaches, material crafts and ornamental period looks. */
export const craftStyles = [
  defineStyle({
    slug: "vector-minimalism",
    name: "Vector Minimalism",
    aliases: ["Flat minimal", "Minimal vector", "Flat design"],
    kind: "technique",
    summary: "Few flat shapes, no outlines, a tight palette and clever negative space.",
    about:
      "A reduced vector illustration approach: subjects are built from a handful of flat geometric shapes with no outlines or texture, using negative space to imply form and a palette of three or four colours.",
    tags: ["flat shapes", "negative space", "no outlines", "icon-like"],
    colourFacets: ["muted", "restrained"],
    formFacets: ["geometric", "illustrative"],
    density: "sparse",
    swatches: [
      c("#F3EDE2", "sand white"),
      c("#274C5E", "deep teal"),
      c("#E07A5F", "terracotta"),
      c("#F2CC8F", "wheat"),
    ],
    look: {
      colour: "three or four flat colours with no gradients",
      texture: "none: perfectly flat vector fills",
      materials: "vector shapes",
      lighting: "implied only by flat tonal steps",
      composition: "a centred, iconic subject built from a few shapes with ample margin",
      typography: "simple geometric sans-serif",
    },
    prompt: {
      cues: [
        "a subject built from a handful of flat geometric shapes",
        "no outlines, gradients or texture",
        "negative space used to imply form",
        "a tight palette of three or four colours",
        "iconic, centred composition with ample margin",
      ],
      motion: "shapes morphing and sliding with smooth easing, simple loops",
      avoid: ["texture", "detailed rendering", "outlines"],
    },
    related: ["vector-art", "minimalism", "swiss", "mid-century-modern"],
  }),
  defineStyle({
    slug: "vector-art",
    name: "Vector Art",
    aliases: ["Vector illustration", "Flat illustration"],
    kind: "technique",
    summary: "Crisp scalable illustration with clean curves, layered flat shading and bold shapes.",
    about:
      "Illustration built from clean Bézier shapes: crisp edges, layered flat shading in two or three tones per colour, and bold, readable forms. More detailed and expressive than vector minimalism.",
    tags: ["crisp edges", "flat shading", "Bézier curves", "illustration"],
    colourFacets: ["vivid"],
    formFacets: ["illustrative", "digital"],
    density: "balanced",
    swatches: [
      c("#FFF6E9", "canvas cream"),
      c("#2D3047", "ink navy"),
      c("#FF9B42", "tangerine"),
      c("#1B998B", "jade"),
    ],
    look: {
      colour: "saturated flat colours with two or three shading tones each",
      texture: "clean flat fills, occasional subtle grain",
      materials: "vector shapes",
      lighting: "flat cel-style shading with hard shadow shapes",
      composition: "a clear hero subject with layered foreground, midground and background",
      typography: "friendly rounded sans or custom lettering",
    },
    prompt: {
      cues: [
        "crisp clean vector edges and smooth curves",
        "layered flat shading with hard-edged shadow shapes",
        "bold, readable silhouettes",
        "saturated tangerine, jade and navy palette",
        "depth built from flat foreground, midground and background layers",
      ],
      motion: "smooth vector animation with overlapping action and easing",
      avoid: ["photographic texture", "sketchy lines", "muddy colour"],
    },
    related: ["vector-minimalism", "pixel-art", "clay-style", "pop-art"],
  }),
  defineStyle({
    slug: "clay-style",
    name: "Clay Style",
    aliases: ["Claymation", "Clay 3D", "Plasticine"],
    kind: "technique",
    summary: "Soft rounded clay forms with fingerprints, matte pastel colour and stop-motion charm.",
    about:
      "Characters and objects modelled from clay or plasticine (or rendered to look like it) with soft rounded forms, visible fingerprints and tool marks, matte surfaces and warm miniature-set lighting.",
    tags: ["plasticine", "handmade", "rounded", "stop-motion"],
    colourFacets: ["pastel", "vivid"],
    formFacets: ["dimensional", "textured"],
    density: "balanced",
    swatches: [
      c("#FBE7D4", "peach clay"),
      c("#F28C8C", "coral clay"),
      c("#8AC6D0", "powder blue clay"),
      c("#F6D55C", "butter clay"),
    ],
    look: {
      colour: "matte pastel clays: peach, coral, powder blue and butter",
      texture: "fingerprints, tool marks, slightly uneven surfaces",
      materials: "plasticine, polymer clay, felt and card sets",
      lighting: "warm, soft miniature-set lighting with gentle shadows",
      composition: "chunky rounded characters on a small handmade set",
      typography: "rolled-clay lettering",
    },
    prompt: {
      cues: [
        "soft rounded plasticine forms",
        "visible fingerprints and tool marks",
        "matte pastel colour with no gloss",
        "a small handmade miniature set",
        "warm soft lighting with gentle shadows",
      ],
      motion: "stop-motion at 12 frames per second with slight surface boil",
      avoid: ["glossy CGI", "hard sharp edges", "photorealistic skin"],
    },
    related: ["bubbleglam", "kidcore", "naive", "neumorphism"],
  }),
  defineStyle({
    slug: "naive",
    name: "Naïve",
    aliases: ["Naive", "Naïve art", "Folk art", "Outsider-inspired"],
    kind: "movement",
    summary: "Flat perspective, earnest detail and bold unmixed colour with a self-taught charm.",
    about:
      "Associated with self-taught painters: perspective is flattened, figures are frontal and simplified, and detail is lavished on patterns like leaves or fabric. Colour is bold and unblended, and the mood is earnest rather than ironic.",
    tags: ["flat perspective", "patterned detail", "frontal figures", "folk"],
    colourFacets: ["vivid", "earthy"],
    formFacets: ["illustrative", "organic"],
    density: "dense",
    swatches: [
      c("#E8DDC4", "gesso"),
      c("#2F6B3A", "leaf green"),
      c("#C2452D", "barn red"),
      c("#243A5E", "night blue"),
    ],
    look: {
      colour: "bold unmixed greens, reds and deep blue",
      texture: "visible brushstrokes in flat, careful fills",
      materials: "oil or gouache on canvas or board",
      lighting: "even, shadowless light",
      composition: "flattened perspective with frontal figures and patterned foliage",
      typography: "hand-painted lettering with uneven spacing",
    },
    prompt: {
      cues: [
        "flattened perspective with frontal, simplified figures",
        "carefully repeated, patterned foliage",
        "bold, unmixed colour",
        "even, shadowless light",
        "earnest, hand-painted quality",
      ],
      motion: "gentle, simple movement as if a painted scene quietly comes alive",
      avoid: ["technical perspective", "photorealism", "slick digital finish"],
    },
    related: ["kidcore", "bohemian", "surreal-design", "type-doodles"],
    references: ["rousseau-the-dream"],
  }),
  defineStyle({
    slug: "surreal-design",
    name: "Surreal Design",
    aliases: ["Surreal", "Surrealist-inspired", "Dreamlike"],
    kind: "aesthetic",
    summary: "Impossible juxtapositions rendered with calm, believable realism.",
    about:
      "Inspired by surrealism: ordinary objects placed at impossible scales or in impossible places, rendered with calm realism under clear light. Long shadows, empty horizons and quiet colour make the strangeness feel believable.",
    tags: ["impossible scale", "dreamlike", "juxtaposition", "empty horizon"],
    colourFacets: ["muted", "pastel"],
    formFacets: ["photographic", "dimensional"],
    density: "sparse",
    swatches: [
      c("#E9D8C4", "desert sand"),
      c("#8FB3D9", "dream sky"),
      c("#B34A3C", "red door"),
      c("#3E3A4F", "long shadow"),
    ],
    look: {
      colour: "calm sand and sky tones with one unexpected accent",
      texture: "smooth, believable realism",
      materials: "ordinary objects in unexpected materials or scales",
      lighting: "clear late-afternoon light with long shadows",
      composition: "an impossible juxtaposition on an empty horizon",
      typography: "minimal; elegant serif if any",
    },
    prompt: {
      cues: [
        "an impossible juxtaposition of scale or place",
        "calm, believable realism",
        "an empty horizon with long late-afternoon shadows",
        "sand and sky tones with one unexpected accent",
        "quiet, dreamlike stillness",
      ],
      motion: "slow, uncanny movement; objects floating or transforming calmly",
      avoid: ["chaotic clutter", "cartoon outlines", "horror gore"],
    },
    related: ["collage-art", "vaporwave", "psychedelic", "post-modernism"],
  }),
  defineStyle({
    slug: "luxury-minimal",
    name: "Luxury Minimal",
    aliases: ["Quiet luxury", "Luxury minimalism"],
    kind: "aesthetic",
    summary: "Expensive restraint: stone, cashmere, champagne tones and sculptural soft light.",
    about:
      "Minimalism with rich materials: travertine, cashmere, brushed brass and matte ceramics in warm neutrals, lit with soft sculptural shadow. Composition is spare and calm, and type is a refined serif or small spaced caps.",
    tags: ["travertine", "neutrals", "soft shadow", "refined"],
    colourFacets: ["muted", "restrained", "metallic"],
    formFacets: ["photographic", "dimensional"],
    density: "sparse",
    swatches: [
      c("#EDE6DC", "travertine"),
      c("#C8B79E", "cashmere"),
      c("#9C7C4A", "brushed brass"),
      c("#2B2622", "espresso"),
    ],
    look: {
      colour: "travertine, cashmere and espresso with a thin brushed-brass accent",
      texture: "honed stone, soft knit, matte ceramic",
      materials: "travertine, cashmere, brushed brass, linen",
      lighting: "soft sculptural window light with long gentle shadows",
      composition: "a single hero object on a plinth with generous empty space",
      typography: "refined serif or small widely spaced capitals",
    },
    prompt: {
      cues: [
        "a single hero object with generous empty space",
        "honed travertine, cashmere and brushed brass",
        "warm neutral palette",
        "soft sculptural window light with long gentle shadows",
        "calm, expensive restraint",
      ],
      motion: "slow, weighty camera glides; light shifting softly across stone",
      avoid: ["clutter", "saturated colour", "glossy plastic"],
    },
    related: ["minimalism", "art-deco", "editorial", "neumorphism"],
  }),
  defineStyle({
    slug: "maximalism",
    name: "Maximalism",
    aliases: ["Maximalist", "More is more"],
    kind: "aesthetic",
    summary: "Layered pattern on pattern, saturated jewel tones and joyful abundance.",
    about:
      "The opposite of minimalism: pattern layered on pattern, collections displayed en masse, jewel-toned walls, clashing prints and dense decoration. It stays coherent through a shared palette and repeated motifs.",
    tags: ["pattern clash", "jewel tones", "abundance", "layering"],
    colourFacets: ["vivid", "dark"],
    formFacets: ["ornamental", "textured"],
    density: "dense",
    swatches: [
      c("#1F3B2D", "bottle green"),
      c("#B0265B", "raspberry"),
      c("#E3A72F", "saffron"),
      c("#2B3A7A", "sapphire"),
    ],
    look: {
      colour: "jewel tones: bottle green, raspberry, saffron and sapphire",
      texture: "velvet, chinoiserie wallpaper, lacquer, fringe",
      materials: "velvet, brass, ceramics, patterned wallpaper, rugs",
      lighting: "warm lamplight with rich shadow",
      composition: "every surface patterned and filled, framed by a repeated motif",
      typography: "decorative display serifs",
    },
    prompt: {
      cues: [
        "pattern layered on pattern across every surface",
        "saturated jewel tones: bottle green, raspberry, saffron, sapphire",
        "velvet, lacquer and brass details",
        "dense collections displayed in abundance",
        "warm lamplight with rich shadow",
      ],
      motion: "slow sweeping reveals across layers of detail",
      avoid: ["empty space", "monochrome palettes", "sterile minimalism"],
    },
    related: ["bohemian", "victorian-style", "memphis", "psychedelic"],
  }),
  defineStyle({
    slug: "gothic",
    name: "Gothic",
    aliases: ["Goth", "Gothic revival", "Dark academia (adjacent)"],
    kind: "period",
    summary: "Pointed arches, blackletter, candlelit shadows and deep oxblood and black.",
    about:
      "Combines Gothic architectural forms (pointed arches, tracery, ribbed vaults) with a dark romantic mood: candlelight, velvet, wrought iron, blackletter type and a palette of black, oxblood and aged gold.",
    tags: ["pointed arches", "blackletter", "candlelight", "dark romance"],
    colourFacets: ["dark", "metallic"],
    formFacets: ["ornamental", "photographic"],
    density: "dense",
    swatches: [
      c("#0F0D0E", "raven black"),
      c("#5A1520", "oxblood"),
      c("#A88A4E", "aged gold"),
      c("#6B6966", "cathedral stone"),
    ],
    look: {
      colour: "raven black, oxblood and aged gold with grey stone",
      texture: "carved stone, velvet, wax, tarnished metal",
      materials: "stone tracery, stained glass, wrought iron, velvet, candles",
      lighting: "candlelight and shafts of light through stained glass",
      composition: "strong verticals and pointed arches framing a central figure",
      typography: "blackletter and ornate capitals",
    },
    prompt: {
      cues: [
        "pointed arches, tracery and ribbed vaults",
        "candlelight and shafts of coloured light",
        "raven black, oxblood and aged gold",
        "velvet, wrought iron and carved stone",
        "strong vertical framing",
        "blackletter lettering",
      ],
      motion: "slow upward tilts, flickering candlelight, drifting dust in light shafts",
      avoid: ["bright pastels", "flat vector shapes", "cheerful daylight"],
    },
    related: ["victorian-style", "art-deco", "maximalism", "steampunk"],
    references: ["cologne-cathedral-interior"],
  }),
  defineStyle({
    slug: "steampunk",
    name: "Steampunk",
    aliases: ["Steam punk", "Victorian sci-fi"],
    kind: "aesthetic",
    summary: "Brass gears, riveted copper, leather and steam: Victorian engineering as fantasy.",
    about:
      "A retro-fantasy genre imagining steam-powered technology in a nineteenth-century setting. Objects are built from brass, copper, dark wood and leather, with exposed gears, rivets, gauges and pipes lit by warm gaslight.",
    tags: ["brass", "gears", "Victorian", "machinery"],
    colourFacets: ["metallic", "earthy", "dark"],
    formFacets: ["ornamental", "dimensional", "textured"],
    density: "dense",
    swatches: [
      c("#2A1E17", "smoked walnut"),
      c("#B5853A", "polished brass"),
      c("#8A4B2A", "oxidised copper"),
      c("#D9C7A0", "parchment"),
    ],
    look: {
      colour: "polished brass, copper and smoked walnut with parchment",
      texture: "rivets, patina, stitched leather, worn wood",
      materials: "brass gears, copper pipes, leather straps, glass gauges, walnut",
      lighting: "warm gaslight glow with haze and soft steam",
      composition: "intricate machinery layered around the subject",
      typography: "Victorian display serifs and engraved plates",
    },
    prompt: {
      cues: [
        "exposed brass gears, rivets and pressure gauges",
        "copper pipes venting soft steam",
        "stitched leather straps and dark walnut",
        "warm gaslight glow with haze",
        "intricate layered Victorian machinery",
      ],
      motion: "gears turning, pistons pumping, steam drifting through warm light",
      avoid: ["plastic surfaces", "neon", "minimal empty space"],
    },
    related: ["victorian-style", "gothic", "blueprint", "skeuomorphism"],
    references: ["proulx-brass-spider", "parseghian-steampunk-radio"],
    featured: 8,
  }),
  defineStyle({
    slug: "bohemian",
    name: "Bohemian",
    aliases: ["Boho", "Boho chic"],
    kind: "aesthetic",
    summary: "Layered textiles, rattan, plants, warm terracotta and relaxed, collected interiors.",
    about:
      "A relaxed, collected look: layered kilims and macramé, rattan and wood, trailing plants, ceramics and warm earth colours, lit by soft afternoon sun.",
    tags: ["textiles", "rattan", "plants", "earth tones"],
    colourFacets: ["earthy", "muted"],
    formFacets: ["textured", "organic", "photographic"],
    density: "dense",
    swatches: [
      c("#F1E4D3", "unbleached linen"),
      c("#C0643C", "terracotta"),
      c("#7C8C58", "olive leaf"),
      c("#D9A441", "turmeric"),
    ],
    look: {
      colour: "terracotta, turmeric and olive on unbleached linen",
      texture: "woven kilims, macramé, rattan, rough ceramics",
      materials: "cotton, jute, rattan, terracotta, wood, plants",
      lighting: "warm, hazy afternoon sun through sheer curtains",
      composition: "layered, collected arrangements at floor level",
      typography: "loose hand-lettered or soft serif",
    },
    prompt: {
      cues: [
        "layered woven textiles, kilims and macramé",
        "rattan, jute and rough terracotta",
        "trailing plants throughout",
        "warm hazy afternoon sun through sheer curtains",
        "terracotta, turmeric and olive tones",
      ],
      motion: "curtains lifting in a breeze, dappled light moving across textiles",
      avoid: ["chrome", "neon", "sterile minimalism"],
    },
    related: ["70s-retro", "maximalism", "naive", "art-nouveau"],
  }),
  defineStyle({
    slug: "victorian-style",
    name: "Victorian Style",
    aliases: ["Victorian", "Victoriana"],
    kind: "period",
    summary: "Dense botanical pattern, engraved detail, ornate frames and rich deep colour.",
    about:
      "A look drawn from nineteenth-century British visual culture: dense botanical and bird patterns, engraved illustration, ornate gilt frames, playbill typography and deep colours such as indigo, plum and bottle green.",
    tags: ["botanical pattern", "engraving", "ornate frame", "playbill"],
    colourFacets: ["dark", "earthy"],
    formFacets: ["ornamental", "illustrative"],
    density: "dense",
    swatches: [
      c("#1D2A44", "indigo"),
      c("#5A2D45", "plum"),
      c("#C9A45A", "gilt"),
      c("#E6DBC4", "engraving paper"),
    ],
    look: {
      colour: "indigo, plum and bottle green with gilt and cream",
      texture: "fine engraving hatching, block-printed pattern, embossed paper",
      materials: "wallpaper, velvet, gilt frames, mahogany, lace",
      lighting: "warm oil-lamp light",
      composition: "a central subject in an ornate frame on a dense repeating pattern",
      typography: "mixed playbill display faces, ornate serif capitals",
    },
    prompt: {
      cues: [
        "dense, symmetrical botanical and bird pattern",
        "fine engraving-style hatching",
        "an ornate gilt frame around the subject",
        "deep indigo, plum and gilt colours",
        "warm oil-lamp lighting",
      ],
      motion: "slow push-ins through ornate frames, lamp-flicker, pages turning",
      avoid: ["flat modern vector", "neon", "empty minimal space"],
    },
    related: ["gothic", "steampunk", "art-nouveau", "maximalism"],
    references: ["morris-strawberry-thief"],
  }),
];
