import { c, defineStyle } from "./define";

/** Screen, interface and digital-culture styles. */
export const digitalStyles = [
  defineStyle({
    slug: "web-1-0",
    name: "Web 1.0",
    aliases: ["Web 1", "Early web", "90s web", "GeoCities"],
    kind: "interface",
    summary: "Early homepage chaos: tiled backgrounds, bevelled buttons, pixel GIFs and default fonts.",
    about:
      "The hand-built personal pages of the early web: tiled patterned backgrounds, default serif and Comic-style fonts, bevelled grey buttons, visitor counters, under-construction icons, marquees and low-colour GIFs.",
    tags: ["tiled background", "bevel buttons", "GIFs", "default fonts"],
    colourFacets: ["vivid"],
    formFacets: ["digital", "typographic"],
    density: "dense",
    swatches: [
      c("#C0C0C0", "system grey"),
      c("#0000EE", "hyperlink blue"),
      c("#000080", "navy title bar"),
      c("#FFFF00", "highlight yellow"),
    ],
    look: {
      colour: "system grey, hyperlink blue, navy title bars and raw web-safe brights",
      texture: "dithered GIFs, tiled patterned backgrounds, aliased pixel edges",
      materials: "CRT monitors, beige plastic, floppy disks",
      lighting: "CRT screen glow",
      composition: "stacked centred blocks, tables, marquees and counters",
      typography: "default Times-style serif, underlined blue links, pixel fonts",
    },
    prompt: {
      cues: [
        "tiled patterned background with dithered GIF graphics",
        "bevelled grey buttons and navy title bars",
        "underlined blue hyperlink text in a default serif",
        "aliased pixel edges and web-safe colours",
        "centred stacked layout with counters and badges",
      ],
      motion: "looping low-frame-rate GIF animation, scrolling marquee text",
      avoid: ["smooth gradients", "high-resolution 3D", "subtle minimalism"],
    },
    related: ["pixel-art", "vaporwave", "web-2-0-gloss", "glitch"],
  }),
  defineStyle({
    slug: "web-2-0-gloss",
    name: "Web 2.0 Gloss",
    aliases: ["Web 2.0", "Glossy web", "Aqua gloss"],
    kind: "interface",
    summary: "Glassy gel buttons, reflections, candy gradients and rounded badges from the mid-2000s web.",
    about:
      "Mid-2000s interface styling: glossy gel buttons with a white highlight band, reflections below logos, candy gradients, rounded 'beta' badges and soft drop shadows on clean white pages.",
    tags: ["gel buttons", "reflections", "badges", "mid-2000s"],
    colourFacets: ["vivid", "pastel"],
    formFacets: ["digital", "dimensional"],
    density: "balanced",
    swatches: [
      c("#FFFFFF", "page white"),
      c("#3BA0FF", "gel blue"),
      c("#7ED321", "lime gel"),
      c("#FF7F2A", "tangerine gel"),
    ],
    look: {
      colour: "clean white with glossy gel blue, lime and tangerine",
      texture: "glassy highlight bands, mirror reflections, soft gradients",
      materials: "glossy plastic, glass, polished metal",
      lighting: "top-down highlight with reflections below objects",
      composition: "centred logos and buttons on white with floor reflections",
      typography: "rounded friendly sans-serif with glossy wordmarks",
    },
    prompt: {
      cues: [
        "glossy gel surfaces with a white highlight band across the top",
        "mirror reflections beneath objects on a white floor",
        "candy gradients in blue, lime and tangerine",
        "rounded badge and starburst shapes",
        "soft drop shadows on clean white",
      ],
      motion: "glossy highlights sliding across surfaces, bouncy scale-ups",
      avoid: ["flat design", "grunge textures", "dark moody scenes"],
    },
    related: ["y2k", "skeuomorphism", "web-1-0", "bubbleglam"],
  }),
  defineStyle({
    slug: "skeuomorphism",
    name: "Skeuomorphism",
    aliases: ["Skeuomorphic", "Realistic UI"],
    kind: "interface",
    summary: "Interfaces imitating real materials: stitched leather, wood, brushed metal and paper.",
    about:
      "A digital design approach that imitates physical objects: leather with stitching, felt, wood grain, torn paper, brushed-metal knobs and realistic shadows, so interface elements feel tangible.",
    tags: ["realistic materials", "stitching", "knobs", "tactile"],
    colourFacets: ["earthy", "metallic"],
    formFacets: ["dimensional", "textured", "digital"],
    density: "balanced",
    swatches: [
      c("#6B4226", "saddle leather"),
      c("#D9C7A3", "notepad yellow"),
      c("#A9ADB2", "brushed steel"),
      c("#2E2A26", "shadow brown"),
    ],
    look: {
      colour: "saddle leather, notepad yellow, brushed steel",
      texture: "leather grain, stitching, wood grain, felt, paper",
      materials: "leather, brushed aluminium, walnut, linen paper, glass",
      lighting: "soft top light with realistic drop and inner shadows",
      composition: "objects arranged like real desk items with physical depth",
      typography: "embossed or letterpressed lettering",
    },
    prompt: {
      cues: [
        "realistic stitched leather and wood grain surfaces",
        "brushed metal knobs and toggles with fine specular highlights",
        "embossed and letterpressed lettering",
        "soft top light with realistic drop shadows",
        "tactile, physical depth on every element",
      ],
      motion: "physical clicks, knobs turning, pages curling with realistic weight",
      avoid: ["flat colour", "neon", "abstract geometric shapes"],
    },
    related: ["web-2-0-gloss", "neumorphism", "steampunk", "clay-style"],
  }),
  defineStyle({
    slug: "neumorphism",
    name: "Neumorphism",
    aliases: ["Soft UI", "Neomorphism"],
    kind: "interface",
    summary: "Soft extruded shapes the same colour as the background, lit by paired light and dark shadows.",
    about:
      "A soft-UI trend where elements are pushed out of or pressed into the surface using a light highlight on one side and a soft shadow on the other, with the element and background sharing one colour.",
    tags: ["soft UI", "extruded", "monochrome", "tactile"],
    colourFacets: ["pastel", "restrained"],
    formFacets: ["dimensional", "digital"],
    density: "sparse",
    swatches: [
      c("#E4E8EE", "soft grey"),
      c("#FFFFFF", "highlight white"),
      c("#B8C0CC", "shadow grey-blue"),
      c("#6C7A91", "slate"),
    ],
    look: {
      colour: "a single soft grey with lighter highlights and cooler shadows",
      texture: "smooth matte plastic",
      materials: "matte moulded plastic",
      lighting: "one soft light from top-left creating paired highlights and shadows",
      composition: "rounded controls gently extruded from a single-colour surface",
      typography: "soft, low-contrast rounded sans-serif",
    },
    prompt: {
      cues: [
        "rounded forms softly extruded from a same-colour background",
        "paired soft highlight and soft shadow on opposite sides",
        "a single matte grey tone with low contrast",
        "smooth, seamless moulded-plastic surfaces",
        "a single soft light from the top-left",
      ],
      motion: "gentle press-in and pop-out, soft shadow shifts",
      avoid: ["hard outlines", "multiple saturated colours", "busy texture"],
    },
    related: ["glassmorphism", "skeuomorphism", "clay-style", "minimalism"],
  }),
  defineStyle({
    slug: "glassmorphism",
    name: "Glassmorphism",
    aliases: ["Frosted glass UI", "Glass UI"],
    kind: "interface",
    summary: "Frosted translucent panels floating over vivid blurred colour.",
    about:
      "An interface style of frosted-glass panels with background blur, thin light borders and subtle transparency, floating over vivid, softly blurred colour fields or orbs.",
    tags: ["frosted glass", "blur", "translucency", "floating panels"],
    colourFacets: ["vivid", "pastel"],
    formFacets: ["digital", "dimensional"],
    density: "sparse",
    swatches: [
      c("#1B1F3B", "deep indigo"),
      c("#8F5CFF", "violet orb"),
      c("#FF6AA2", "rose orb"),
      c("#E9ECFF", "frost white"),
    ],
    look: {
      colour: "vivid violet and rose light behind frosted white translucency",
      texture: "frosted glass, background blur, fine noise",
      materials: "frosted acrylic, glass",
      lighting: "coloured light glowing through translucent layers",
      composition: "layered floating panels over blurred colour orbs",
      typography: "clean white sans-serif on frosted panels",
    },
    prompt: {
      cues: [
        "frosted translucent glass panels with background blur",
        "thin light edge highlights on each panel",
        "vivid violet and rose light glowing behind the glass",
        "layered floating depth",
        "fine grain over smooth colour",
      ],
      motion: "parallax drift of glass layers, colour orbs slowly shifting behind",
      avoid: ["opaque flat panels", "hard black outlines", "earthy textures"],
    },
    related: ["aurora", "neumorphism", "gen-x-soft-club", "y2k"],
  }),
  defineStyle({
    slug: "neubrutalism",
    name: "Neubrutalism",
    aliases: ["Neo-brutalism", "Neobrutalism", "Brutalist web"],
    kind: "interface",
    summary: "Thick black outlines, hard offset shadows, flat loud colour and raw default type.",
    about:
      "A contemporary web and graphic style: flat saturated blocks with thick black borders, hard un-blurred offset shadows, visible structure and blunt type. It borrows the name, not the concrete, of architectural brutalism.",
    tags: ["thick outlines", "hard shadows", "flat colour", "raw"],
    colourFacets: ["vivid"],
    formFacets: ["geometric", "digital", "typographic"],
    density: "balanced",
    swatches: [
      c("#FFF4DA", "paper cream"),
      c("#111111", "outline black"),
      c("#FF6B6B", "punch red"),
      c("#4DD4FF", "pop cyan"),
    ],
    look: {
      colour: "flat punch red, pop cyan and yellow with black outlines on cream",
      texture: "perfectly flat fills",
      materials: "flat digital surfaces, sticker-like cut-outs",
      lighting: "no lighting, only hard offset shadows",
      composition: "chunky blocks with thick borders and solid offset shadows",
      typography: "blunt bold grotesque or monospace, often oversized",
    },
    prompt: {
      cues: [
        "thick black outlines on every shape",
        "hard solid offset shadows with no blur",
        "flat saturated blocks of colour on cream",
        "chunky, oversized blunt type",
        "raw, visible structure",
      ],
      motion: "snappy hard cuts, blocks slamming into place with no easing",
      avoid: ["soft gradients", "blurred shadows", "photorealism"],
    },
    related: ["brutalism", "memphis", "pop-art", "swiss"],
  }),
  defineStyle({
    slug: "cyberpop",
    name: "Cyberpop",
    aliases: ["Cyber pop"],
    kind: "aesthetic",
    summary: "Candy-bright digital pop: holographic stickers, UI fragments, anime energy and neon shine.",
    about:
      "A playful counterpart to cyberpunk: bright candy colours, holographic stickers, interface fragments, sparkles and anime-influenced characters, with tech motifs used as decoration rather than dystopia.",
    note: "Informal label; definitions vary.",
    tags: ["holographic", "stickers", "UI fragments", "candy neon"],
    colourFacets: ["neon", "pastel"],
    formFacets: ["digital", "illustrative"],
    density: "dense",
    swatches: [
      c("#F6F0FF", "screen white"),
      c("#FF3CAC", "cyber pink"),
      c("#2BD2FF", "hologram cyan"),
      c("#C6FF3D", "lime flash"),
    ],
    look: {
      colour: "cyber pink, hologram cyan and lime flash on bright white",
      texture: "holographic foil, glossy stickers, pixel sparkles",
      materials: "holographic vinyl, translucent plastic, LED",
      lighting: "bright, high-key light with neon edge glow",
      composition: "a central character or object surrounded by UI windows, stickers and icons",
      typography: "chunky rounded digital display type with outline strokes",
    },
    prompt: {
      cues: [
        "holographic sticker and foil textures",
        "floating interface windows, icons and cursor fragments",
        "cyber pink, hologram cyan and lime on white",
        "bright high-key light with neon edge glow",
        "anime-influenced graphic energy",
      ],
      motion: "sticker pops, UI windows snapping open, sparkle bursts",
      avoid: ["dystopian grime", "muted earth tones", "heavy darkness"],
    },
    related: ["kidcore", "y2k", "cyberpunk", "future-funk"],
  }),
  defineStyle({
    slug: "chromecore",
    name: "Chromecore",
    aliases: ["Chrome core", "Liquid chrome"],
    kind: "aesthetic",
    summary: "Liquid mirror-chrome forms reflecting a simple studio world.",
    about:
      "An aesthetic centred on reflective chrome: liquid, melted or inflated mirror-metal forms and lettering that reflect a simple sky or studio environment, often on black or pale grounds.",
    note: "Informal label; overlaps with Y2K and Acid.",
    tags: ["liquid chrome", "reflection", "metal", "3D type"],
    colourFacets: ["metallic", "restrained"],
    formFacets: ["dimensional", "digital"],
    density: "sparse",
    swatches: [
      c("#0E0E10", "void black"),
      c("#E9ECEF", "mirror highlight"),
      c("#8B929A", "chrome mid"),
      c("#5AB3FF", "reflected sky"),
    ],
    look: {
      colour: "mirror silver with reflected sky blue on black",
      texture: "perfect mirror reflections, liquid ripples",
      materials: "polished chrome, liquid mercury-like metal",
      lighting: "studio softboxes reflected as crisp highlights",
      composition: "a single liquid chrome form or word floating centre frame",
      typography: "inflated or melted chrome lettering",
    },
    prompt: {
      cues: [
        "liquid mirror-chrome surfaces",
        "crisp reflections of studio softboxes and sky",
        "melted, flowing metal forms",
        "a single floating object on a black ground",
        "high-contrast silver and deep black",
      ],
      motion: "liquid metal flowing and reforming, reflections sliding across",
      avoid: ["matte surfaces", "earthy colours", "flat illustration"],
    },
    related: ["y2k", "acid", "italo-disco", "futuristic"],
  }),
  defineStyle({
    slug: "cyberpunk",
    name: "Cyberpunk",
    aliases: ["Cyber punk", "Neo-noir sci-fi"],
    kind: "aesthetic",
    summary: "Rain-soaked neon megacities, dense signage, high tech and low life.",
    about:
      "A science-fiction genre look: dense night cityscapes, rain and reflections, stacked neon signage, cables and augmentations, and a cyan-magenta palette cutting through darkness.",
    tags: ["neon signage", "rain", "megacity", "night"],
    colourFacets: ["neon", "dark"],
    formFacets: ["photographic", "digital"],
    density: "dense",
    swatches: [
      c("#07090F", "night black"),
      c("#00F0FF", "neon cyan"),
      c("#FF1F8E", "neon magenta"),
      c("#FFB000", "sodium amber"),
    ],
    look: {
      colour: "near-black night with neon cyan, magenta and sodium amber",
      texture: "wet reflective asphalt, rain streaks, haze, grime",
      materials: "wet concrete, cables, LED signage, worn tech",
      lighting: "neon signs and screens as the only light sources, strong reflections",
      composition: "dense vertical cityscapes and narrow alleys layered with signage",
      typography: "stacked neon signage in mixed scripts",
    },
    prompt: {
      cues: [
        "rain-soaked night streets reflecting neon",
        "dense stacked neon signage and screens",
        "cyan and magenta light cutting through darkness",
        "haze, cables and worn high-tech details",
        "towering vertical city layers",
      ],
      motion: "slow tracking through rain, flickering signs, drifting fog",
      avoid: ["daylight", "clean pastel minimalism", "rural scenes"],
    },
    related: ["synthwave", "glitch", "surveillance", "cyberpop"],
  }),
  defineStyle({
    slug: "cyberminimalism",
    name: "Cyberminimalism",
    aliases: ["Cyber minimalism", "Cyber-minimal"],
    kind: "aesthetic",
    summary: "Sparse futuristic interfaces: fine lines, monochrome planes, precise data and one cold accent.",
    about:
      "A restrained take on digital futurism: dark or pale monochrome surfaces, hairline strokes, precise grid-aligned data, small monospace labels and a single cold accent colour. Technology is suggested through precision, not clutter.",
    note: "Informal label; definitions vary.",
    tags: ["hairlines", "monochrome", "HUD", "precision"],
    colourFacets: ["restrained", "dark"],
    formFacets: ["digital", "geometric", "typographic"],
    density: "sparse",
    swatches: [
      c("#0C0D0F", "carbon black"),
      c("#E6E8EA", "cold white"),
      c("#5B6168", "graphite"),
      c("#7CF7FF", "ice cyan"),
    ],
    look: {
      colour: "carbon black and cold white with a single ice-cyan accent",
      texture: "smooth matte surfaces, hairline strokes",
      materials: "anodised metal, matte glass, carbon fibre",
      lighting: "low-key light with thin edge highlights",
      composition: "sparse grid-aligned elements with measurement marks and generous darkness",
      typography: "small monospace and thin extended sans-serif labels",
    },
    prompt: {
      cues: [
        "sparse monochrome composition with hairline strokes",
        "grid-aligned data marks and small monospace labels",
        "a single ice-cyan accent",
        "matte anodised and dark glass surfaces",
        "low-key light with thin edge highlights",
      ],
      motion: "precise linear motion, lines extending and data ticking over, slow dolly",
      avoid: ["clutter", "warm vintage tones", "ornament"],
    },
    related: ["minimalism", "tech-spec", "futuristic", "gen-x-soft-club"],
    featured: 7,
  }),
  defineStyle({
    slug: "glitch",
    name: "Glitch",
    aliases: ["Glitch art", "Databending", "Datamosh"],
    kind: "technique",
    summary: "Corrupted data made visible: RGB splits, pixel sorting, scan lines and broken blocks.",
    about:
      "Glitch art turns digital errors into material: channels split into offset red, green and blue, rows of pixels smear sideways, compression blocks break apart and scan lines interrupt the image.",
    tags: ["RGB split", "pixel sorting", "scan lines", "corruption"],
    colourFacets: ["neon", "dark"],
    formFacets: ["digital", "textured"],
    density: "dense",
    swatches: [
      c("#0B0B0D", "dead pixel black"),
      c("#FF0040", "red channel"),
      c("#00FFD1", "cyan channel"),
      c("#F2F2F2", "blown white"),
    ],
    look: {
      colour: "offset red and cyan channels with blown whites on black",
      texture: "compression blocks, pixel-sort streaks, scan lines",
      materials: "CRT screens, corrupted video, broken files",
      lighting: "screen glow",
      composition: "a recognisable subject sliced by horizontal displacement bands",
      typography: "sliced, displaced and channel-split type",
    },
    prompt: {
      cues: [
        "RGB channel split with red and cyan offsets",
        "horizontal displacement bands slicing the subject",
        "pixel-sorting streaks and compression blocks",
        "scan lines across the image",
        "blown whites on deep black",
      ],
      motion: "stuttering frames, datamosh smears, sudden displacement jumps",
      avoid: ["clean, stable imagery", "soft pastels", "organic textures"],
    },
    related: ["cyberpunk", "surveillance", "web-1-0", "acid"],
  }),
  defineStyle({
    slug: "pixel-art",
    name: "Pixel Art",
    aliases: ["8-bit", "16-bit", "Sprite art"],
    kind: "technique",
    summary: "Hand-placed pixels on a low-resolution grid with a limited palette and crisp edges.",
    about:
      "Images made at very low resolution where each pixel is placed deliberately: a limited palette, hard stair-step edges, dithering for shading and a clear silhouette readable at small sizes.",
    tags: ["low resolution", "limited palette", "dithering", "sprites"],
    colourFacets: ["vivid"],
    formFacets: ["digital", "illustrative"],
    density: "balanced",
    swatches: [
      c("#1A1C2C", "night sprite"),
      c("#41A6F6", "pixel sky"),
      c("#38B764", "grass green"),
      c("#FFCD75", "sand"),
    ],
    look: {
      colour: "a limited palette of 8 to 16 flat colours",
      texture: "hard pixel grid, dithering patterns",
      materials: "screen pixels only",
      lighting: "stylised shading with one or two tones per colour",
      composition: "clear silhouettes in a side view or three-quarter isometric view",
      typography: "bitmap pixel fonts",
    },
    prompt: {
      cues: [
        "a visible low-resolution pixel grid with crisp stair-step edges",
        "a limited palette of flat colours",
        "dithering patterns for shading",
        "clear, readable silhouettes",
        "no anti-aliasing or blur",
      ],
      motion: "few-frame sprite animation loops, stepped movement, parallax layers",
      avoid: ["smooth gradients", "photographic detail", "blurry edges"],
    },
    related: ["web-1-0", "glitch", "kidcore", "vector-art"],
  }),
  defineStyle({
    slug: "aurora",
    name: "Aurora",
    aliases: ["Aurora UI", "Aurora gradients", "Mesh gradient"],
    kind: "aesthetic",
    summary: "Soft glowing colour fields that bloom and blend like northern lights.",
    about:
      "A soft-glow style of blended light fields: large blurred blooms of green, violet and blue blend into each other over a dark or pale ground, often with fine grain, suggesting aurora light rather than hard shapes.",
    note: "Primarily a digital/UI trend name.",
    tags: ["glow", "mesh gradient", "blur", "northern lights"],
    colourFacets: ["vivid", "dark"],
    formFacets: ["digital", "organic"],
    density: "sparse",
    swatches: [
      c("#060B1A", "polar night"),
      c("#3CFFB0", "aurora green"),
      c("#7A5CFF", "violet veil"),
      c("#2F80FF", "deep sky blue"),
    ],
    look: {
      colour: "aurora green, violet and deep sky blue glowing on polar night",
      texture: "soft blur, fine grain, no hard edges",
      materials: "light itself: glow, haze, mist",
      lighting: "self-luminous colour fields, soft bloom",
      composition: "large overlapping glowing fields with a quiet focal point",
      typography: "clean, light sans-serif in white",
    },
    prompt: {
      cues: [
        "large soft glowing colour fields blending into each other",
        "aurora green, violet and blue light on a dark night ground",
        "no hard edges; everything blooms and diffuses",
        "fine grain over smooth colour",
        "a calm, quiet focal point",
      ],
      motion: "slow undulating curtains of light, colour fields drifting and breathing",
      avoid: ["hard outlines", "busy detail", "flat solid fills"],
    },
    related: ["glassmorphism", "gen-x-soft-club", "cyberminimalism", "psychedelic"],
  }),
  defineStyle({
    slug: "surveillance",
    name: "Surveillance",
    aliases: ["CCTV aesthetic", "Security camera", "Surveillance footage"],
    kind: "aesthetic",
    summary: "CCTV footage: high angles, timestamps, green-grey noise and detached observation.",
    about:
      "Imagery that looks captured by security or trail cameras: high fixed angles, wide-angle distortion, low-resolution noise, timestamp overlays, green or blue-grey monochrome and a feeling of being watched.",
    tags: ["CCTV", "timestamp", "high angle", "noise"],
    colourFacets: ["dark", "muted"],
    formFacets: ["photographic", "digital"],
    density: "sparse",
    swatches: [
      c("#1C221E", "monitor dark"),
      c("#7F9A84", "night-vision green"),
      c("#C7CCC6", "washed grey"),
      c("#E94B3C", "record red"),
    ],
    look: {
      colour: "desaturated green-grey with a small red recording dot",
      texture: "low-resolution sensor noise, compression, interlacing",
      materials: "concrete corridors, parking lots, fluorescent-lit rooms",
      lighting: "fluorescent overheads or infrared night vision",
      composition: "fixed high-angle wide shot with fisheye distortion and a timestamp overlay",
      typography: "blocky monospace timestamp and camera-ID overlays",
    },
    prompt: {
      cues: [
        "a fixed high-angle wide shot like a security camera",
        "fisheye distortion and low-resolution sensor noise",
        "desaturated green-grey night-vision tones",
        "timestamp and camera-ID overlay in blocky monospace",
        "flat fluorescent or infrared light",
      ],
      motion: "static locked-off camera, dropped frames, figures crossing the frame",
      avoid: ["cinematic shallow depth of field", "vivid colour", "flattering lighting"],
    },
    related: ["glitch", "brutalism", "cyberpunk", "grunge"],
  }),
  defineStyle({
    slug: "futuristic",
    name: "Futuristic",
    aliases: ["Futurism (design)", "Sci-fi", "Future"],
    kind: "aesthetic",
    summary: "Seamless white forms, monumental scale and luminous clean technology.",
    about:
      "A general forward-looking look: seamless curved forms, monumental white architecture, luminous panels and precise engineering, with a clean, optimistic mood. Not the same as Italian Futurism, the early-twentieth-century art movement.",
    note: "Not the Italian Futurist art movement. This entry describes a general sci-fi design look.",
    tags: ["seamless forms", "monumental", "white", "luminous"],
    colourFacets: ["restrained", "metallic"],
    formFacets: ["dimensional", "geometric"],
    density: "sparse",
    swatches: [
      c("#F3F5F7", "ceramic white"),
      c("#9AA4AE", "titanium"),
      c("#1E2A38", "deep space"),
      c("#4FC3F7", "light-panel blue"),
    ],
    look: {
      colour: "ceramic white and titanium with deep space blue and luminous accents",
      texture: "seamless ceramic, brushed titanium, smooth composites",
      materials: "white composites, titanium, glass, light panels",
      lighting: "clean, bright ambient light with luminous panels",
      composition: "monumental curved forms with a small human for scale",
      typography: "wide, extended geometric sans-serif",
    },
    prompt: {
      cues: [
        "seamless curved white architecture",
        "monumental scale with a small figure for reference",
        "luminous light panels set into smooth surfaces",
        "ceramic white and brushed titanium materials",
        "clean, bright, optimistic lighting",
      ],
      motion: "smooth gliding camera, doors sliding open, lights fading up in sequence",
      avoid: ["grime and decay", "vintage textures", "clutter"],
    },
    related: ["cyberminimalism", "chromecore", "tech-spec", "blueprint"],
    references: ["gottscho-trylon-perisphere", "paul-amazing-stories-1928-08"],
  }),
];
