import { c, defineStyle } from "./define";

/** Recognised art, design and architecture movements. */
export const movementStyles = [
  defineStyle({
    slug: "swiss",
    name: "Swiss / International Typographic Style",
    aliases: ["Swiss", "Swiss Style", "International Typographic Style", "International Style"],
    kind: "movement",
    summary: "Objective, grid-built graphic design with flush-left sans-serif type and bold asymmetric balance.",
    about:
      "A post-war graphic design approach that treats the page as a mathematical grid. Type is usually a neo-grotesque sans-serif set flush left, ragged right, and photography or flat geometry is placed with deliberate asymmetry. Decoration is removed so hierarchy comes from scale, weight and position alone.",
    tags: ["grid", "sans-serif", "asymmetry", "poster"],
    colourFacets: ["restrained", "vivid"],
    formFacets: ["typographic", "geometric"],
    density: "sparse",
    swatches: [
      c("#F1EFEA", "paper white"),
      c("#111111", "ink black"),
      c("#E2231A", "signal red"),
      c("#9A9A96", "concrete grey"),
    ],
    look: {
      colour: "white paper, black type and a single saturated red used sparingly",
      texture: "flat offset-printed colour with crisp edges and no visible texture",
      materials: "uncoated poster paper, black-and-white photography",
      lighting: "even, shadowless light; photographs are high-contrast and neutral",
      composition: "strict modular grid, strong asymmetry, large areas of empty space, content aligned to column edges",
      typography: "neo-grotesque sans-serif, flush left ragged right, extreme scale contrast between headline and text",
    },
    prompt: {
      cues: [
        "strict modular grid with elements snapped to column edges",
        "flush-left sans-serif typography with extreme scale contrast",
        "asymmetric balance with large areas of empty white space",
        "a single saturated red accent against black and white",
        "flat, offset-printed colour with no ornament",
        "high-contrast black-and-white photography cropped hard to the grid",
      ],
      motion: "clean linear slides along grid lines, elements snapping into columns, no easing flourishes",
      avoid: ["decorative flourishes", "centred symmetrical layouts", "gradients"],
    },
    related: ["bauhaus", "modernism", "minimalism", "editorial"],
    featured: 1,
  }),
  defineStyle({
    slug: "bauhaus",
    name: "Bauhaus",
    aliases: ["Bauhaus design", "Bauhaus school"],
    kind: "movement",
    summary: "Primary colours, elementary shapes and functional construction from the German design school.",
    about:
      "Associated with the German school of art, architecture and design. The graphic language reduces form to circles, squares and triangles, often in red, yellow and blue with black. Typography is sturdy and geometric, and composition is built from overlapping planes and bars rather than illustration.",
    tags: ["primary colours", "geometry", "overlap", "functional"],
    colourFacets: ["vivid"],
    formFacets: ["geometric", "typographic"],
    density: "balanced",
    swatches: [
      c("#EDE6D6", "unbleached cream"),
      c("#D62718", "primary red"),
      c("#F2B90F", "primary yellow"),
      c("#1D3F8F", "primary blue"),
    ],
    look: {
      colour: "primary red, yellow and blue with black on an unbleached cream ground",
      texture: "flat lithographic colour with slight paper grain",
      materials: "printed paper, painted steel, plywood, glass",
      lighting: "flat, frontal, graphic light with no dramatic shadow",
      composition: "overlapping circles, squares and bars arranged on diagonals and right angles",
      typography: "geometric sans-serif, often lowercase, set in heavy bars and blocks",
    },
    prompt: {
      cues: [
        "elementary circles, squares and triangles as the main forms",
        "primary red, yellow and blue with solid black accents",
        "overlapping flat planes and thick bars",
        "geometric sans-serif lettering integrated as a shape",
        "functional, unornamented construction",
      ],
      motion: "shapes slide, rotate and overlap on precise axes, like a moving constructivist diagram",
      avoid: ["soft gradients", "ornamental detail", "photorealistic texture"],
    },
    related: ["constructivism", "swiss", "modernism", "memphis"],
    references: ["moholy-nagy-komposition-6"],
    featured: 2,
  }),
  defineStyle({
    slug: "constructivism",
    name: "Constructivism",
    aliases: ["Russian Constructivism", "Soviet Constructivism"],
    kind: "movement",
    summary: "Diagonal red-and-black compositions with photomontage and propaganda-poster energy.",
    about:
      "An early-twentieth-century movement that treated art as construction. Its posters use aggressive diagonals, red and black on off-white, heavy slab lettering and photomontage. Forms push against each other to suggest force and direction.",
    tags: ["diagonals", "red and black", "photomontage", "poster"],
    colourFacets: ["restrained", "vivid"],
    formFacets: ["geometric", "typographic", "photographic"],
    density: "balanced",
    swatches: [
      c("#E8DFCC", "aged newsprint"),
      c("#C8201E", "revolutionary red"),
      c("#1A1A1A", "press black"),
      c("#8C8373", "warm grey"),
    ],
    look: {
      colour: "red and black on aged off-white newsprint",
      texture: "slightly misregistered lithographic print, halftone photographs",
      materials: "newsprint, cut photographs, steel and timber structures",
      lighting: "hard, graphic contrast; photographs lit from low angles",
      composition: "steep diagonals, wedges and radiating lines creating forward thrust",
      typography: "heavy condensed sans-serif and slab lettering set on angles",
    },
    prompt: {
      cues: [
        "steep diagonal composition with wedge shapes cutting across the frame",
        "red and black on aged off-white paper",
        "photomontage fragments shot from a low, heroic angle",
        "heavy condensed lettering set on an angle",
        "radiating lines that suggest motion and force",
      ],
      motion: "sharp diagonal pushes and wedges driving across frame, montage-style hard cuts",
      avoid: ["pastel colours", "soft organic curves", "centred symmetry"],
    },
    related: ["bauhaus", "collage-art", "punk", "deconstructivism"],
    references: ["lissitzky-red-wedge"],
  }),
  defineStyle({
    slug: "art-deco",
    name: "Art Deco",
    aliases: ["Deco", "Style Moderne"],
    kind: "movement",
    summary: "Glamorous symmetry, stepped geometry, sunbursts and metallic finishes.",
    about:
      "A decorative style associated with the interwar years, visible in architecture, interiors, posters and objects. It combines strict symmetry with luxurious materials: stepped setbacks, fan and sunburst motifs, chevrons, lacquer, chrome and gold leaf. Lettering is tall and geometric with high contrast.",
    tags: ["symmetry", "gold", "sunburst", "luxury"],
    colourFacets: ["metallic", "dark"],
    formFacets: ["geometric", "ornamental"],
    density: "balanced",
    swatches: [
      c("#14231F", "deep emerald black"),
      c("#C9A45C", "brushed gold"),
      c("#EFE6D2", "ivory"),
      c("#3F6B5E", "jade green"),
    ],
    look: {
      colour: "deep emerald or black grounds with gold, ivory and jade",
      texture: "polished lacquer, brushed metal, inlaid wood veneer",
      materials: "gold leaf, chrome, marble, black lacquer, etched glass",
      lighting: "dramatic uplighting that picks out metallic edges and reflections",
      composition: "strict bilateral symmetry, stepped tiers, radiating sunbursts and fans",
      typography: "tall geometric capitals with high contrast strokes and generous tracking",
    },
    prompt: {
      cues: [
        "strict bilateral symmetry with stepped, tiered geometry",
        "radiating sunburst and fan motifs",
        "polished gold and brass details against deep emerald and black",
        "lacquer, marble and inlaid wood surfaces",
        "chevron and zigzag ornament bands",
        "dramatic uplighting catching metallic edges",
      ],
      motion: "slow symmetrical reveals, fans unfolding and light sweeping across metallic surfaces",
      avoid: ["asymmetric clutter", "rustic textures", "neon colours"],
    },
    related: ["art-nouveau", "luxury-minimal", "gothic", "mid-century-modern"],
    references: ["gottscho-chrysler-1932", "chrysler-lift-door"],
    featured: 4,
  }),
  defineStyle({
    slug: "art-nouveau",
    name: "Art Nouveau",
    aliases: ["Jugendstil", "Modern Style", "Liberty style"],
    kind: "movement",
    summary: "Flowing whiplash curves, botanical ornament and framed decorative figures.",
    about:
      "A decorative style of the turn of the twentieth century built on organic line. Stems, hair and drapery curve in long whiplash strokes, figures are framed by ornamental borders or halos, and colour is soft and natural. Hand-drawn lettering is integrated into the design.",
    tags: ["organic line", "botanical", "ornamental frame", "poster"],
    colourFacets: ["earthy", "muted"],
    formFacets: ["organic", "ornamental", "illustrative"],
    density: "dense",
    swatches: [
      c("#EDE1C4", "vellum"),
      c("#B9853F", "ochre"),
      c("#5E7153", "sage green"),
      c("#7A3B2E", "madder brown"),
    ],
    look: {
      colour: "soft ochres, sage greens and madder browns on vellum",
      texture: "lithographic flat colour with fine contour lines",
      materials: "printed paper, wrought iron, stained glass, carved wood",
      lighting: "soft, even decorative light without cast shadows",
      composition: "a central figure or motif framed by an ornamental border, halo or arch",
      typography: "hand-drawn, organic lettering with swelling strokes",
    },
    prompt: {
      cues: [
        "long, flowing whiplash curves",
        "botanical ornament of stems, flowers and leaves",
        "a central figure framed by a circular halo or decorative arch",
        "fine even contour lines around flat areas of colour",
        "muted ochre, sage and madder tones",
        "hand-drawn lettering woven into the border",
      ],
      motion: "slow flowing movement of hair, vines and drapery following long curves",
      avoid: ["hard geometric grids", "neon colours", "sans-serif type"],
    },
    related: ["art-deco", "victorian-style", "psychedelic", "bohemian"],
    references: ["mucha-job-1896"],
    featured: 12,
  }),
  defineStyle({
    slug: "modernism",
    name: "Modernism",
    aliases: ["Modernist design", "Modern movement"],
    kind: "movement",
    summary: "Reduction to essentials: rational structure, primary relationships, form following function.",
    about:
      "A broad umbrella for early-to-mid-twentieth-century design that rejected historical ornament. Visually it favours rational structure, clear planes, primary colour relationships and honest materials. Use it when you want clarity and restraint rather than a specific national school.",
    note: "Broad umbrella term. Pair it with Swiss, Bauhaus or Mid-Century Modern for a more specific look.",
    tags: ["reduction", "rational", "planes", "clarity"],
    colourFacets: ["restrained", "vivid"],
    formFacets: ["geometric"],
    density: "sparse",
    swatches: [
      c("#F4F3EF", "gallery white"),
      c("#1B1B1B", "black line"),
      c("#C22A22", "cadmium red"),
      c("#23479A", "cobalt blue"),
    ],
    look: {
      colour: "white fields divided by black, with small areas of primary colour",
      texture: "smooth painted planes, matte surfaces",
      materials: "white render, steel, glass, painted panels",
      lighting: "clear daylight, crisp shadows from simple volumes",
      composition: "rectilinear divisions of the frame with an intentional imbalance of areas",
      typography: "plain sans-serif, clear hierarchy, no ornament",
    },
    prompt: {
      cues: [
        "rectilinear division of the frame into clean planes",
        "white and black with small, deliberate areas of primary colour",
        "no ornament; structure and proportion carry the image",
        "smooth matte painted surfaces",
        "crisp daylight with simple cast shadows",
      ],
      motion: "measured, architectural camera moves; planes slide and align",
      avoid: ["ornament", "busy texture", "nostalgic filters"],
    },
    related: ["swiss", "bauhaus", "minimalism", "mid-century-modern"],
    references: ["mondrian-composition-ii-1930"],
  }),
  defineStyle({
    slug: "minimalism",
    name: "Minimalism",
    aliases: ["Minimal", "Minimalist"],
    kind: "movement",
    summary: "One subject, generous negative space and a disciplined, reduced palette.",
    about:
      "Minimalism strips an image to a single subject, a few shapes and a lot of empty space. Colour is reduced to one or two quiet tones, materials are shown plainly and repetition or precise alignment does the expressive work.",
    tags: ["negative space", "single subject", "reduction", "quiet"],
    colourFacets: ["restrained", "muted"],
    formFacets: ["geometric"],
    density: "sparse",
    swatches: [
      c("#EEEBE5", "chalk white"),
      c("#2B2B2A", "graphite"),
      c("#C8C2B8", "stone"),
      c("#8E8A82", "warm grey"),
    ],
    look: {
      colour: "one or two quiet neutrals with minimal contrast shifts",
      texture: "smooth, matte, unblemished surfaces",
      materials: "plaster, raw steel, pale wood, concrete",
      lighting: "soft, diffuse light with long gentle gradients of shadow",
      composition: "a single subject placed with precision in a large field of negative space",
      typography: "small, light sans-serif set with generous spacing",
    },
    prompt: {
      cues: [
        "a single subject with generous negative space",
        "a reduced palette of one or two quiet neutrals",
        "smooth matte surfaces with no clutter",
        "precise placement off-centre in an empty field",
        "soft diffuse light with gentle shadow gradients",
      ],
      motion: "very slow, steady camera drift; minimal subject movement; long holds",
      avoid: ["clutter", "multiple competing subjects", "saturated colour"],
    },
    related: ["luxury-minimal", "vector-minimalism", "cyberminimalism", "swiss"],
  }),
  defineStyle({
    slug: "brutalism",
    name: "Brutalism",
    aliases: ["Brutalist architecture", "Béton brut"],
    kind: "movement",
    summary: "Raw board-marked concrete, heavy repeated modules and monumental massing.",
    about:
      "Named from the French for raw concrete, the look is dominated by exposed material and heavy, repeated forms. Surfaces show board marks and weathering, volumes are cantilevered and monumental, and colour comes mostly from the concrete itself and the sky.",
    tags: ["concrete", "monumental", "repetition", "raw material"],
    colourFacets: ["muted", "restrained"],
    formFacets: ["geometric", "textured", "photographic"],
    density: "dense",
    swatches: [
      c("#A7A39A", "weathered concrete"),
      c("#5D5A55", "shadowed concrete"),
      c("#D9D6CF", "overcast sky"),
      c("#2E2D2B", "deep recess"),
    ],
    look: {
      colour: "grey concrete tones from pale to charcoal under an overcast sky",
      texture: "board-marked, bush-hammered and weathered concrete",
      materials: "raw concrete, dark glass, steel",
      lighting: "flat overcast light or hard raking sun that exaggerates texture",
      composition: "massive repeated modules, cantilevers and deep recesses shot from low angles",
      typography: "blunt, heavy sans-serif or stencil lettering",
    },
    prompt: {
      cues: [
        "raw board-marked concrete surfaces with visible weathering",
        "heavy, repeated modular volumes and deep recessed openings",
        "monumental massing seen from a low angle",
        "grey concrete palette under flat overcast light",
        "hard raking light that exaggerates surface texture",
      ],
      motion: "slow upward tilts revealing scale, heavy static framing, clouds moving over concrete",
      avoid: ["decorative ornament", "bright saturated colour", "glossy surfaces"],
    },
    related: ["neubrutalism", "modernism", "surveillance", "minimalism"],
    references: ["huffman-barbican"],
  }),
  defineStyle({
    slug: "mid-century-modern",
    name: "Mid-Century Modern",
    aliases: ["MCM", "Mid-century", "Atomic age"],
    kind: "movement",
    summary: "Warm teak, organic curves, mustard and teal, and optimistic post-war forms.",
    about:
      "A post-war design look found in furniture, interiors and illustration. It pairs warm wood and clean-lined silhouettes with organic curves, tapered legs, starbursts and boomerang shapes. Colour runs to mustard, burnt orange, teal and olive.",
    tags: ["teak", "organic modern", "mustard and teal", "atomic"],
    colourFacets: ["earthy", "vivid"],
    formFacets: ["geometric", "organic", "illustrative"],
    density: "balanced",
    swatches: [
      c("#F2E8D5", "warm paper"),
      c("#D99B2B", "mustard"),
      c("#1F6F6B", "teal"),
      c("#9A5230", "teak brown"),
    ],
    look: {
      colour: "mustard, teal, burnt orange and teak brown on warm off-white",
      texture: "woodgrain, woven upholstery, slightly grainy printed illustration",
      materials: "teak, moulded plywood, fibreglass, brass, terrazzo",
      lighting: "warm, sunny interior light through large windows",
      composition: "low horizontal lines, open plans and floating, tapered forms",
      typography: "friendly geometric sans and brush script accents",
    },
    prompt: {
      cues: [
        "warm teak and moulded plywood with visible woodgrain",
        "low horizontal lines and tapered, floating forms",
        "mustard, teal and burnt-orange accents",
        "boomerang and starburst motifs",
        "warm sunny light through large windows",
      ],
      motion: "gentle dolly through an open plan; sunlight shifting across wood surfaces",
      avoid: ["chrome-heavy futurism", "neon", "cluttered ornament"],
    },
    related: ["70s-retro", "retro", "modernism", "art-deco"],
  }),
  defineStyle({
    slug: "post-modernism",
    name: "Post-Modernism",
    aliases: ["Postmodern", "Postmodern design", "PoMo"],
    kind: "movement",
    summary: "Ironic mixes of historical quotation, pastel colour and playful classical fragments.",
    about:
      "A reaction against modernist restraint that brings back ornament with a wink. Classical columns and pediments appear as flat cut-outs, pastels meet bold pattern, and materials are deliberately faked: laminate marble, painted stone. It is theatrical and self-aware.",
    tags: ["pastiche", "pastel", "classical fragments", "irony"],
    colourFacets: ["pastel", "vivid"],
    formFacets: ["geometric", "ornamental"],
    density: "balanced",
    swatches: [
      c("#F2D7CF", "salmon pink"),
      c("#9FC7C0", "mint"),
      c("#3C4C8C", "ultramarine"),
      c("#E7C35A", "sand yellow"),
    ],
    look: {
      colour: "salmon, mint, sand and ultramarine used in blocky zones",
      texture: "faux marble, laminate, painted terrazzo",
      materials: "laminate, painted MDF, faux stone, glass block",
      lighting: "bright, stagey light with clean shadows",
      composition: "flat classical fragments (columns, arches, pediments) stacked as stage sets",
      typography: "mixed classical serif capitals and geometric display faces",
    },
    prompt: {
      cues: [
        "flat, cut-out classical columns, arches and pediments",
        "salmon pink, mint and ultramarine colour blocks",
        "faux marble and laminate surfaces",
        "theatrical stage-set arrangement",
        "playful ironic mix of historical references",
      ],
      motion: "stage-like reveals, flat set pieces sliding in, deliberate theatrical pacing",
      avoid: ["austere minimalism", "grunge texture", "monochrome"],
    },
    related: ["memphis", "deconstructivism", "surreal-design", "80s-editorial"],
  }),
  defineStyle({
    slug: "deconstructivism",
    name: "Deconstructivism",
    aliases: ["Deconstruction", "Deconstructivist"],
    kind: "movement",
    summary: "Fragmented, tilted planes and colliding structures that break the grid on purpose.",
    about:
      "Drawn from architecture and later graphic design, the look fragments form: planes collide and tilt, grids fracture, and structure appears unstable. In graphic work, text layers overlap and break across the frame while staying carefully controlled.",
    tags: ["fragmentation", "tilted planes", "layered type", "instability"],
    colourFacets: ["restrained", "metallic"],
    formFacets: ["geometric", "typographic"],
    density: "dense",
    swatches: [
      c("#E6E4DF", "pale zinc"),
      c("#8A8F94", "steel grey"),
      c("#1E2124", "carbon"),
      c("#C84B31", "oxide red"),
    ],
    look: {
      colour: "zinc, steel grey and carbon with a single oxide-red cut",
      texture: "brushed metal, cracked plaster, layered transparent sheets",
      materials: "folded steel cladding, glass shards, layered tracing paper",
      lighting: "hard light producing sharp, fractured shadows",
      composition: "tilted, intersecting planes and fractured grids, deliberately off-balance",
      typography: "overlapping, broken lines of type at varying angles and sizes",
    },
    prompt: {
      cues: [
        "fractured, intersecting planes set at conflicting angles",
        "a broken grid with elements colliding and overlapping",
        "brushed steel and pale zinc surfaces",
        "hard light casting sharp, splintered shadows",
        "a single oxide-red accent slicing through grey",
      ],
      motion: "planes shearing past each other, jagged camera moves, fragments reassembling",
      avoid: ["calm symmetry", "soft rounded forms", "pastels"],
    },
    related: ["constructivism", "experimental-type", "post-modernism", "brutalism"],
  }),
  defineStyle({
    slug: "pop-art",
    name: "Pop Art",
    aliases: ["Pop"],
    kind: "movement",
    summary: "Ben-Day dots, thick outlines, flat saturated colour and consumer imagery.",
    about:
      "Pop art borrows from comics, advertising and packaging. Images are flattened into thick black outlines, flat saturated fills and visible halftone dot patterns, often repeated in grids or blown up to monumental scale.",
    tags: ["halftone dots", "comic outline", "repetition", "consumer imagery"],
    colourFacets: ["vivid"],
    formFacets: ["illustrative", "textured"],
    density: "balanced",
    swatches: [
      c("#FFE14F", "comic yellow"),
      c("#E8232A", "tomato red"),
      c("#1F5FBF", "process blue"),
      c("#111111", "outline black"),
    ],
    look: {
      colour: "saturated process yellow, red and blue with black outlines",
      texture: "visible Ben-Day halftone dots and screen-print misregistration",
      materials: "screen-printed canvas, comic newsprint, packaging",
      lighting: "flat, graphic light with no realistic shading",
      composition: "a single iconic subject enlarged, or repeated in a grid",
      typography: "comic lettering, speech bubbles and bold sans-serif slogans",
    },
    prompt: {
      cues: [
        "visible Ben-Day halftone dots in the shading",
        "thick black comic-book outlines",
        "flat saturated primary colours",
        "an everyday or iconic subject enlarged to monumental scale",
        "slight screen-print misregistration",
      ],
      motion: "punchy zooms, panel-to-panel cuts, colour variations flicking in a grid",
      avoid: ["muted colour", "photorealistic lighting", "soft gradients"],
    },
    related: ["future-funk", "kidcore", "memphis", "cyberpop"],
  }),
  defineStyle({
    slug: "memphis",
    name: "Memphis",
    aliases: ["Memphis Group", "Memphis design", "Memphis Milano"],
    kind: "movement",
    summary: "Squiggles, confetti, terrazzo and clashing pastel-bright blocks on playful geometric forms.",
    about:
      "Associated with the Milan design collective of the early 1980s. Furniture and graphics combine basic geometric volumes with loud surface patterns (squiggles, dots, confetti and laminate terrazzo) in deliberately clashing brights and pastels.",
    tags: ["squiggles", "terrazzo", "clashing colour", "playful geometry"],
    colourFacets: ["vivid", "pastel"],
    formFacets: ["geometric", "illustrative"],
    density: "dense",
    swatches: [
      c("#F7F0E1", "laminate white"),
      c("#FF5D8F", "flamingo pink"),
      c("#2EC4B6", "aqua"),
      c("#FFCB2E", "egg yellow"),
    ],
    look: {
      colour: "flamingo pink, aqua, egg yellow and black on white",
      texture: "patterned plastic laminate, terrazzo speckle, black squiggle prints",
      materials: "plastic laminate, lacquered wood, terrazzo",
      lighting: "bright, even studio light",
      composition: "chunky geometric volumes stacked off-balance with patterned surfaces",
      typography: "chunky geometric display type with squiggle accents",
    },
    prompt: {
      cues: [
        "black squiggle and confetti surface patterns",
        "chunky cylinders, cones and blocks stacked off-balance",
        "clashing flamingo pink, aqua and egg yellow",
        "terrazzo and patterned laminate textures",
        "bright, even studio lighting",
      ],
      motion: "bouncy stop-motion-like assembly of shapes, patterns sliding and popping",
      avoid: ["muted earth tones", "realistic wear", "minimal empty space"],
    },
    related: ["post-modernism", "kidcore", "80s-editorial", "pop-art"],
    featured: 11,
  }),
  defineStyle({
    slug: "baroque-tenebrism",
    name: "Baroque Tenebrism",
    aliases: ["Baroque", "Baroque art", "Tenebrism", "Caravaggesque", "Chiaroscuro painting"],
    kind: "movement",
    summary: "Figures lit by one hard beam out of deep darkness, in rich oil paint.",
    about:
      "The dramatic side of Baroque painting: most of the canvas falls into near-black shadow while a single strong light, from a high window or a candle, picks out faces, hands and folds of cloth. Warm earth colours, deep reds and ochres, and thick, glazed oil paint give weight and theatre to everyday or sacred scenes.",
    note: "Tenebrism is the extreme-contrast form of Baroque chiaroscuro. Name the light source to get the effect.",
    tags: ["chiaroscuro", "oil painting", "single light source", "dramatic shadow"],
    colourFacets: ["dark", "earthy"],
    formFacets: ["illustrative", "textured"],
    density: "balanced",
    swatches: [
      c("#15110D", "umber black"),
      c("#D9A95B", "candle gold"),
      c("#8E2A1E", "madder red"),
      c("#5E4A2E", "raw umber"),
    ],
    look: {
      colour: "near-black umber shadow with warm gold light, madder red and ochre",
      texture: "thick oil paint, glazes, visible brushwork and aged canvas",
      materials: "velvet and linen drapery, stone arches, worn wood, brass and pewter",
      lighting: "one hard light from a high window or a candle, the rest falling into deep shadow",
      composition: "figures gathered around a lit focal point, set against a dark void, often on a diagonal",
      typography: "classical Roman capitals, engraved or inscribed",
    },
    prompt: {
      cues: [
        "a single hard light source against deep, near-black shadow",
        "rich oil painting with glazes and visible brushwork",
        "faces, hands and cloth folds picked out by the light",
        "warm earth colours with madder red and candle gold",
        "a dramatic diagonal composition of gathered figures",
        "aged canvas texture",
      ],
      motion: "slow push-ins through the dark, a flickering candle and dust drifting in the beam of light",
      avoid: ["even, flat lighting", "bright saturated colours", "clean digital rendering"],
    },
    related: ["gothic", "victorian-style", "maximalism", "art-nouveau"],
  }),
];
