import { c, defineStyle } from "./define";

/** Editorial, typographic, print-culture and hand-made techniques. */
export const printStyles = [
  defineStyle({
    slug: "experimental-type",
    name: "Experimental Type",
    aliases: ["Experimental typography", "Expressive type"],
    kind: "technique",
    summary: "Type as image: stretched, layered, warped and set far outside normal reading rules.",
    about:
      "Letterforms become the main visual material. Words are stretched, cropped off the edge, overprinted, set on curves or broken into fragments. Legibility is traded for texture and rhythm, usually in a tight palette so the forms carry the energy.",
    tags: ["letterforms", "distortion", "layering", "poster"],
    colourFacets: ["restrained", "vivid"],
    formFacets: ["typographic"],
    density: "dense",
    swatches: [
      c("#EDEDE8", "stock white"),
      c("#121212", "ink"),
      c("#3A5BFF", "electric blue"),
      c("#FF4B1F", "hot orange"),
    ],
    look: {
      colour: "black and white with one or two electric overprint colours",
      texture: "overprinted inks, photocopy grain, stretched vector outlines",
      materials: "risograph paper, acetate overlays, screen print",
      lighting: "flat and graphic, with no depth lighting",
      composition: "letterforms fill and bleed off the frame, layered at different scales",
      typography: "stretched, cropped, warped and overlapping letterforms as the primary image",
    },
    prompt: {
      cues: [
        "giant letterforms cropped off the edges of the frame",
        "stretched and warped type used as texture",
        "overlapping layers of type in different scales",
        "overprinted electric blue and hot orange on black and white",
        "rhythm and pattern prioritised over legibility",
      ],
      motion: "kinetic type: letters stretching, sliding and snapping between layouts",
      avoid: ["neat centred headlines", "stock photography", "ornamental borders"],
    },
    related: ["deconstructivism", "type-doodles", "new-wave", "acid"],
  }),
  defineStyle({
    slug: "80s-editorial",
    name: "80’s Editorial",
    aliases: ["80s Editorial", "Eighties magazine", "1980s editorial"],
    kind: "period",
    summary: "Glossy magazine spreads with bold colour blocks, big flash photography and stacked headlines.",
    about:
      "The look of 1980s fashion and culture magazines: saturated colour blocks, direct flash photography with hard shadows, big condensed or geometric headlines and layouts that crop figures boldly against flat colour.",
    tags: ["magazine", "flash photography", "colour blocks", "fashion"],
    colourFacets: ["vivid"],
    formFacets: ["photographic", "typographic"],
    density: "balanced",
    swatches: [
      c("#F6F1E7", "gloss white"),
      c("#E3007A", "magenta"),
      c("#0B0B0B", "jet black"),
      c("#00A6D6", "cyan"),
    ],
    look: {
      colour: "flat magenta, cyan, black and white blocks",
      texture: "glossy coated paper, crisp colour film grain",
      materials: "shoulder-padded fashion, patent leather, plastic jewellery",
      lighting: "direct on-camera flash with hard drop shadows on a coloured wall",
      composition: "figure cropped tightly against a flat colour block, headline stacked beside",
      typography: "bold condensed and geometric headlines, sometimes outlined or italic",
    },
    prompt: {
      cues: [
        "direct on-camera flash with hard drop shadows",
        "a figure cropped boldly against a flat magenta or cyan block",
        "glossy coated magazine finish with colour film grain",
        "stacked bold condensed headlines",
        "strong shoulders, plastic jewellery and graphic styling",
      ],
      motion: "flash-pop freeze frames, quick editorial cuts, poses snapping between frames",
      avoid: ["muted film looks", "soft natural light", "rustic props"],
    },
    related: ["editorial", "new-wave", "italo-disco", "memphis"],
  }),
  defineStyle({
    slug: "editorial",
    name: "Editorial",
    aliases: ["Editorial design", "Magazine layout", "Publication design"],
    kind: "technique",
    summary: "Considered photography paired with refined type, generous margins and a clear reading order.",
    about:
      "Contemporary publication design: a strong photograph, an elegant headline, measured columns of text and plenty of margin. The image is art-directed with a restrained palette and natural light, and everything sits on a disciplined grid.",
    tags: ["art direction", "serif headline", "margins", "photography"],
    colourFacets: ["muted", "restrained"],
    formFacets: ["photographic", "typographic"],
    density: "balanced",
    swatches: [
      c("#F3F0EA", "uncoated white"),
      c("#1C1C1C", "text black"),
      c("#B7A58C", "oat"),
      c("#6E4B3A", "walnut"),
    ],
    look: {
      colour: "restrained neutrals (oat, walnut, off-white) with black text",
      texture: "uncoated paper, fine film grain",
      materials: "linen, wool, ceramics, paper",
      lighting: "soft natural window light with gentle shadow",
      composition: "a single art-directed photograph with measured margins and a clear reading order",
      typography: "refined high-contrast serif headline with a clean sans-serif body",
    },
    prompt: {
      cues: [
        "art-directed photograph with a restrained neutral palette",
        "soft natural window light",
        "generous margins and a calm, gridded layout",
        "refined serif headline paired with small clean text",
        "fine film grain on uncoated paper",
      ],
      motion: "slow push-ins, gentle rack focus, calm editorial pacing",
      avoid: ["neon colour", "cluttered layouts", "heavy filters"],
    },
    related: ["80s-editorial", "luxury-minimal", "swiss", "minimalism"],
  }),
  defineStyle({
    slug: "editorial-poster",
    name: "Editorial Poster",
    aliases: ["Newspaper poster", "Broadsheet poster", "Front-page poster", "Newsprint poster"],
    kind: "aesthetic",
    summary: "Front-page layouts in black and white: a towering masthead, boxed photo panels and a figure breaking out of the grid.",
    about:
      "A contemporary poster look built on the anatomy of a newspaper front page. A huge condensed masthead spans the top, a subhead sits reversed out of a solid black bar, and photographs sit in boxed panels on a column grid. The main figure is cut out and overlaps the panels, breaking the frame. Everything is black ink on newsprint white, with posterised, high-contrast imagery.",
    tags: ["newspaper", "masthead", "broken frame", "monochrome"],
    colourFacets: ["restrained"],
    formFacets: ["typographic", "photographic", "textured"],
    density: "dense",
    swatches: [
      c("#EEECE6", "newsprint white"),
      c("#0D0D0D", "press black"),
      c("#8A8A86", "halftone grey"),
      c("#C8201E", "flag red"),
    ],
    look: {
      colour: "press black on newsprint white with halftone greys, at most one small red accent",
      texture: "newsprint halftone, posterised shadows, faint paper grain",
      materials: "newsprint, broadsheet pages, press photographs",
      lighting: "hard, high-contrast light that posterises shadows into flat black shapes",
      composition: "a masthead band, a reversed-out subhead bar and boxed photo panels on a column grid, the main figure cut out and breaking over the panel edges",
      typography: "towering ultra-condensed sans-serif masthead with a bold condensed sans-serif subhead in a black bar",
    },
    prompt: {
      cues: [
        "newspaper front-page layout under a towering condensed masthead",
        "the main figure cut out and breaking out over boxed photo panels",
        "subhead reversed out in white on a solid black bar",
        "black and white with posterised, high-contrast shading",
        "photo panels on a strict column grid with thin rules",
        "newsprint halftone on off-white paper",
      ],
      motion: "the figure leans out of its panel toward the camera, slow push-in, faint halftone shimmer",
      avoid: ["full-colour photography", "soft gradients", "crumpled-paper mockups"],
    },
    related: ["swiss", "grunge", "collage-art", "pop-art", "editorial", "concert-poster"],
  }),
  defineStyle({
    slug: "concert-poster",
    name: "Concert Poster",
    aliases: ["Music poster", "Tour poster", "Concert key visual", "Music tribute poster"],
    kind: "aesthetic",
    summary: "Black-and-white live photography on a dark ground, a giant title, and type woven through the image.",
    about:
      "The look of contemporary tour posters and music tributes. Black-and-white performance photography sits on a near-black ground: a lone figure under one spotlight, or stage, screens and crowd layered at different depths. A giant condensed title spans the frame, and the best examples weave it through the image so parts of the photo pass in front of the letters. Colour is almost absent, apart from a single warm lens flare.",
    tags: ["live music", "spotlight", "layered depth", "monochrome"],
    colourFacets: ["dark", "restrained"],
    formFacets: ["photographic", "typographic"],
    density: "balanced",
    swatches: [
      c("#0B0B0C", "stage black"),
      c("#EDEDEA", "spotlight white"),
      c("#6E6E70", "haze grey"),
      c("#E8A33D", "flare amber"),
    ],
    look: {
      colour: "near-black ground with spotlight-white highlights and haze greys, one warm amber flare",
      texture: "film grain, dust and fine scratches over the dark ground",
      materials: "stage lights, LED screens, smoke, microphones, crowds",
      lighting: "one hard spotlight cutting through stage haze, everything else falling into black",
      composition: "a performer isolated in vast dark space, or stage, screens and crowd layered at different depths, with a giant title across the frame",
      typography: "a giant condensed title spanning the full width, in heavy sans-serif or high-contrast serif capitals, woven in front of and behind the photograph",
    },
    prompt: {
      cues: [
        "black-and-white live performance photography in a dark venue",
        "one hard spotlight cutting through stage haze",
        "photographs layered at different depths: stage, screens and crowd",
        "crowd silhouettes with raised arms in the foreground",
        "deep crushed blacks with one warm lens flare",
        "film grain and fine scratches over the dark ground",
      ],
      motion: "slow push-in through the haze, the spotlight sweeping, the crowd swaying in silhouette",
      avoid: ["colourful stage lighting", "clean digital gradients", "busy corner text"],
    },
    related: ["editorial-poster", "grunge", "luxury-minimal", "film-still-poster"],
  }),
  defineStyle({
    slug: "film-still-poster",
    name: "Film Still Poster",
    aliases: ["Alternative movie poster", "Alt film poster", "Movie still poster", "Minimalist movie poster"],
    kind: "aesthetic",
    summary: "A black-and-white film still with the title stacked down one side in a single spot colour.",
    about:
      "The look of fan-made alternative movie posters. A black-and-white still shows a character standing in their own scene, framed off-centre with the set around them. The title runs down one side, one letter per line, in heavy capitals and a single spot colour, the only colour on the page. Soft motion blur, a ghosted edge and grainy, bleeding ink make it feel like a frame grabbed from a screen and printed cheaply.",
    tags: ["film still", "stacked title", "spot colour", "monochrome"],
    colourFacets: ["restrained", "dark"],
    formFacets: ["photographic", "typographic"],
    density: "sparse",
    swatches: [
      c("#141414", "film black"),
      c("#E6E4DF", "silver white"),
      c("#7A7A78", "still grey"),
      c("#C8161D", "title red"),
    ],
    look: {
      colour: "black-and-white film greys with one spot colour, usually red",
      texture: "film grain, soft motion blur, a ghosted double edge, grainy bleeding ink",
      materials: "film sets, costumes, period architecture, practical lamps",
      lighting: "soft cinematic light from one side, deep shadows in the set",
      composition: "the figure off-centre in their scene, one side left open for a tall stacked title",
      typography: "the title stacked one letter per line down one side in heavy grotesque capitals, printed in the spot colour with grainy, slightly bleeding ink",
    },
    prompt: {
      cues: [
        "a black-and-white film still of a character standing in their scene",
        "soft motion blur and a faint ghosted double edge on the figure",
        "silver greys with deep velvet blacks",
        "colour held back to a single spot accent",
        "cinematic framing, the figure off-centre with the set around them",
        "film grain and slightly bleeding ink, like a lo-fi print",
      ],
      motion: "a slow drift with a faint ghosting trail, grain flickering, as if a film frame is about to play",
      avoid: ["full-colour photography", "clean digital sharpness", "small text blocks"],
    },
    related: ["concert-poster", "editorial-poster", "grunge"],
  }),
  defineStyle({
    slug: "streetwear-poster",
    name: "Streetwear Poster",
    aliases: ["Hype poster", "Quote poster", "Remix poster", "Desi streetwear poster"],
    kind: "aesthetic",
    summary: "Classical art cut out and remixed with a loud quote in clashing typefaces on flat poster red.",
    about:
      "A remix look from streetwear and social media. Figures from classical or devotional paintings are cut out, posterised and given photocopy grit, then set on a loud flat ground. A quote runs as a stack of clashing typefaces, each line a different font, size and colour, with one giant ultra-condensed word running the full height behind the figures. The clash between old imagery and street language is the point.",
    tags: ["streetwear", "quote", "remix", "mixed type"],
    colourFacets: ["vivid"],
    formFacets: ["typographic", "photographic", "textured"],
    density: "dense",
    swatches: [
      c("#C4161C", "poster red"),
      c("#EFEDE6", "paper white"),
      c("#E3E934", "acid yellow"),
      c("#111111", "ink black"),
    ],
    look: {
      colour: "flat poster red with paper white and one hit of acid yellow, black in the cut-outs",
      texture: "fold creases, paper grain, photocopy grit and halftone on the cut-outs",
      materials: "classical paintings, gold ornament, folded posters, photocopies",
      lighting: "flat print light; the figures keep the painted light of their source",
      composition: "cut-out figures cropped hard at the base, overlapping a giant full-height word, the quote stacked down the open side",
      typography: "one giant ultra-condensed white word running the full height, then the rest of the quote stacked line by line, each line in a different typeface: condensed sans, heavy italic, a decorative display face, some lines in acid yellow",
    },
    prompt: {
      cues: [
        "classical painted figures cut out, posterised and remixed with street culture",
        "a loud flat poster-red ground with fold creases and paper grain",
        "photocopy grit and halftone on the cut-outs",
        "clashing flat colour: red, paper white and acid yellow",
        "figures cropped hard at the base, overlapping the frame",
        "the loud, confident energy of a streetwear drop",
      ],
      motion: "cut-outs slam in frame by frame, the poster shakes on each beat, photocopy grain flickering",
      avoid: ["muted colour", "a single clean typeface", "polished 3D rendering"],
    },
    related: ["collage-art", "maximalism", "pop-art", "film-still-poster"],
  }),
  defineStyle({
    slug: "shoegaze",
    name: "Shoegaze",
    aliases: ["Deftones aesthetic", "Nu-gaze", "Dark dreamcore", "Dreamy grunge"],
    kind: "aesthetic",
    summary: "Dark, dreamy photocopies: blurred figures, teal and green-black tints, and type that fades into the grain.",
    about:
      "A moody look drawn from shoegaze and alternative-metal record art and its revival online. Photographs are grainy, blurred and half-lost in shadow: a face, a body in motion or a creature emerging from the dark. Colour is drained to black with a cold sea-teal, green or bruised violet tint. Type is thin and elegant or worn down by photocopying, and never shouts.",
    tags: ["dreamy", "grain", "blur", "teal tint"],
    colourFacets: ["dark", "muted"],
    formFacets: ["photographic", "textured"],
    density: "sparse",
    swatches: [
      c("#0E1214", "deep black"),
      c("#2E6F73", "sea teal"),
      c("#C9D3CC", "faded mint white"),
      c("#5B4A6B", "bruise violet"),
    ],
    look: {
      colour: "near-black with a cold sea-teal or green tint, faded mint highlights and an occasional bruised violet",
      texture: "heavy film grain, photocopy noise, motion blur, light leaks and water stains",
      materials: "worn record sleeves, photocopies, underwater and night photography",
      lighting: "dim, underexposed light, a face or hand catching a soft glow out of the dark",
      composition: "one figure or creature emerging from darkness, cropped close and off-centre, with plenty of quiet dark space",
      typography: "a thin elegant italic serif or a worn photocopied grotesque, small or set as one quiet line, sometimes a blurred wordmark across the top",
    },
    prompt: {
      cues: [
        "a figure half-lost in darkness, blurred and dreamy",
        "a cold sea-teal or green-black tint over grainy photography",
        "motion blur and soft ghosting, as if seen through water",
        "heavy film grain and photocopy noise",
        "light leaks and faded, washed-out highlights",
        "plenty of dark, quiet space around the subject",
      ],
      motion: "slow drifting blur, the figure fading in and out of the dark, grain crawling, an underwater sway",
      avoid: ["bright saturated colour", "crisp clean digital photography", "loud cluttered layouts"],
    },
    related: ["grunge", "gothic", "concert-poster", "film-still-poster"],
  }),
  defineStyle({
    slug: "type-doodles",
    name: "Type Doodles",
    aliases: ["Doodle type", "Hand-drawn type doodles"],
    kind: "technique",
    summary: "Playful hand-drawn letters surrounded by stars, arrows, squiggles and marginal doodles.",
    about:
      "Loose marker or pen lettering decorated with doodled stars, arrows, underlines and little characters. Letters are inflated, shadowed or outlined by hand, and the page feels like a sketchbook or notebook margin.",
    note: "Informal label. Describes a common illustration approach rather than a defined movement.",
    tags: ["hand lettering", "doodles", "marker", "notebook"],
    colourFacets: ["vivid", "restrained"],
    formFacets: ["typographic", "illustrative"],
    density: "dense",
    swatches: [
      c("#FBF8EF", "notebook paper"),
      c("#1F1F1F", "marker black"),
      c("#FF7A59", "coral"),
      c("#4BB3FD", "sky blue"),
    ],
    look: {
      colour: "black marker with one or two bright highlighter colours",
      texture: "felt-tip marker strokes, ballpoint hatching, paper tooth",
      materials: "notebook paper, markers, ballpoint pens",
      lighting: "flat scan-like light",
      composition: "a central hand-lettered word surrounded by scattered doodles",
      typography: "inflated, outlined and hand-shadowed letters with uneven baselines",
    },
    prompt: {
      cues: [
        "hand-drawn bubble and outline lettering with uneven baselines",
        "doodled stars, arrows, squiggles and underlines around the words",
        "felt-tip marker strokes with visible paper tooth",
        "black line with coral and sky-blue highlights",
        "sketchbook-margin energy",
      ],
      motion: "doodles drawing themselves on, boiling hand-drawn line wobble",
      avoid: ["perfect vector type", "photorealism", "corporate layouts"],
    },
    related: ["handwritten", "kidcore", "naive", "experimental-type"],
  }),
  defineStyle({
    slug: "handwritten",
    name: "Handwritten",
    aliases: ["Handwriting", "Script", "Hand lettering"],
    kind: "technique",
    summary: "Personal pen or brush script, ink texture and the intimacy of a written note.",
    about:
      "Handwriting as the focal element: ink or brush script with natural pressure variation, imperfect spacing and visible pen texture. It suits personal, warm or diaristic images and pairs well with paper, letters and journals.",
    tags: ["script", "ink", "personal", "paper"],
    colourFacets: ["restrained", "earthy"],
    formFacets: ["typographic", "textured"],
    density: "sparse",
    swatches: [
      c("#F1E9DA", "writing paper"),
      c("#23324F", "fountain-pen blue"),
      c("#3A2F28", "sepia ink"),
      c("#B89A74", "kraft"),
    ],
    look: {
      colour: "blue-black or sepia ink on warm writing paper",
      texture: "ink pooling, pressure-varied strokes, laid paper",
      materials: "fountain pen, brush, envelopes, journals",
      lighting: "warm natural light on a desk surface",
      composition: "script lines flowing across the page with generous margins",
      typography: "connected handwriting with natural pressure variation and imperfect spacing",
    },
    prompt: {
      cues: [
        "connected handwritten script with natural pressure variation",
        "ink pooling at stroke ends on textured writing paper",
        "blue-black and sepia ink tones",
        "warm natural desk light",
        "imperfect, personal spacing and slant",
      ],
      motion: "ink writing on in real time, pen nib gliding, paper subtly shifting",
      avoid: ["digital fonts", "neon colour", "glossy surfaces"],
    },
    related: ["type-doodles", "bohemian", "victorian-style", "editorial"],
  }),
  defineStyle({
    slug: "tech-spec",
    name: "Tech Spec",
    aliases: ["Technical spec", "Datasheet aesthetic", "Spec sheet"],
    kind: "aesthetic",
    summary: "Product datasheet graphics: callouts, part numbers, dimension lines and monospace labels.",
    about:
      "Borrowed from engineering datasheets and hardware packaging. Objects are shown cleanly in isolation, annotated with leader lines, numbered callouts, dimension marks, barcodes and small monospace specifications, often with one warning-orange accent.",
    note: "Community label for a design trend; definitions vary.",
    tags: ["callouts", "monospace", "diagram", "hardware"],
    colourFacets: ["restrained", "vivid"],
    formFacets: ["typographic", "digital", "geometric"],
    density: "balanced",
    swatches: [
      c("#E7E7E3", "lab grey"),
      c("#161616", "spec black"),
      c("#FF5A1F", "safety orange"),
      c("#9EA3A6", "aluminium"),
    ],
    look: {
      colour: "light grey and black with a single safety-orange accent",
      texture: "matte anodised aluminium, printed labels",
      materials: "aluminium, rubber, printed stickers, cardboard packaging",
      lighting: "clean, even product-shot lighting on a seamless background",
      composition: "an isolated object with leader lines, numbered callouts and dimension marks",
      typography: "small monospace specifications, part numbers and barcodes",
    },
    prompt: {
      cues: [
        "the subject isolated on a seamless light-grey background",
        "thin leader lines with numbered callouts",
        "dimension marks and small monospace specification labels",
        "a single safety-orange accent",
        "matte anodised aluminium and rubber details",
      ],
      motion: "exploded-view assembly, callouts drawing on, slow turntable rotation",
      avoid: ["painterly texture", "moody lighting", "ornament"],
    },
    related: ["blueprint", "cyberminimalism", "swiss", "futuristic"],
  }),
  defineStyle({
    slug: "blueprint",
    name: "Blueprint",
    aliases: ["Cyanotype drawing", "Technical drawing"],
    kind: "technique",
    summary: "White technical linework on Prussian blue with grids, dimensions and annotations.",
    about:
      "Modelled on reprographic engineering prints: fine white or pale-blue lines on deep Prussian blue, orthographic views, construction grids, dimension arrows and hand-lettered annotations. Paper creases and fading add age.",
    tags: ["technical drawing", "Prussian blue", "grid", "annotation"],
    colourFacets: ["restrained"],
    formFacets: ["geometric", "illustrative"],
    density: "balanced",
    swatches: [
      c("#1B3F7A", "Prussian blue"),
      c("#EAF1FA", "chalk white"),
      c("#5F86C0", "faded blue"),
      c("#0F2750", "deep blue"),
    ],
    look: {
      colour: "Prussian blue ground with fine white linework",
      texture: "slightly mottled paper, fold creases, faded edges",
      materials: "reprographic paper, drafting instruments",
      lighting: "flat, scanned document light",
      composition: "orthographic front, side and section views arranged on a construction grid",
      typography: "technical hand lettering and small stencil-like capitals",
    },
    prompt: {
      cues: [
        "fine white technical linework on Prussian blue",
        "orthographic views and cross-sections on a construction grid",
        "dimension arrows and small annotations",
        "mottled paper texture with fold creases",
        "precise, mechanical line weight",
      ],
      motion: "lines plotting on stroke by stroke, a slow pan across the sheet",
      avoid: ["full colour rendering", "photographic texture", "soft focus"],
    },
    related: ["tech-spec", "steampunk", "futuristic", "vector-minimalism"],
  }),
  defineStyle({
    slug: "collage-art",
    name: "Collage Art",
    aliases: ["Collage", "Paper collage", "Mixed media collage"],
    kind: "technique",
    summary: "Torn paper, found photographs and printed scraps layered into a new image.",
    about:
      "Collage builds images from existing material: magazine cut-outs, tickets, photographs, textured papers and type. Edges are torn or cut, pieces overlap with slight shadows, and scale shifts abruptly between fragments.",
    tags: ["torn paper", "found imagery", "layering", "mixed media"],
    colourFacets: ["earthy", "muted"],
    formFacets: ["textured", "photographic"],
    density: "dense",
    swatches: [
      c("#D8C3A0", "kraft paper"),
      c("#23364F", "faded navy"),
      c("#E5B83A", "printer yellow"),
      c("#B8483A", "brick red"),
    ],
    look: {
      colour: "aged paper tones with faded navy, printer yellow and brick red",
      texture: "torn fibrous edges, halftone print, glue marks and slight curling",
      materials: "magazine paper, tickets, photographs, kraft paper, tape",
      lighting: "soft raking light that reveals paper layers and edge shadows",
      composition: "overlapping fragments with abrupt shifts of scale and orientation",
      typography: "found letters and cut-out words from different sources",
    },
    prompt: {
      cues: [
        "torn and cut paper fragments layered with small edge shadows",
        "found photographs and printed scraps at clashing scales",
        "halftone print texture and aged paper tones",
        "cut-out letters from different typefaces",
        "soft raking light revealing paper depth",
      ],
      motion: "stop-motion paper pieces sliding into place, subtle paper flutter",
      avoid: ["seamless digital blending", "clean vector shapes", "glossy 3D"],
    },
    related: ["punk", "surreal-design", "grunge", "constructivism"],
    references: ["schwitters-entrance-ticket", "schwitters-strassenbahnbillet"],
    featured: 6,
  }),
  defineStyle({
    slug: "grunge",
    name: "Grunge",
    aliases: ["Grunge design", "90s grunge"],
    kind: "aesthetic",
    summary: "Distressed textures, photocopy grit, scratchy type and a worn, dim palette.",
    about:
      "A 1990s look of decay and noise. Images are photocopied, scratched and stained; type is distressed or typewritten; layouts feel improvised. Colour is dim (olive, rust, dirty cream) with heavy black.",
    tags: ["distressed", "photocopy", "stains", "90s"],
    colourFacets: ["dark", "earthy"],
    formFacets: ["textured", "typographic", "photographic"],
    density: "dense",
    swatches: [
      c("#2B2A26", "soot"),
      c("#6B6A3F", "army olive"),
      c("#A8542E", "rust"),
      c("#D9CDB0", "dirty cream"),
    ],
    look: {
      colour: "soot black, army olive, rust and dirty cream",
      texture: "photocopy noise, scratches, coffee stains, crumpled paper",
      materials: "flannel, denim, tape, photocopied flyers",
      lighting: "dim, underexposed light with crushed shadows",
      composition: "improvised, off-kilter layouts with overlapping torn elements",
      typography: "distressed typewriter and degraded sans-serif type",
    },
    prompt: {
      cues: [
        "photocopy grit and scratched, distressed textures",
        "dim, underexposed light with crushed blacks",
        "olive, rust and dirty cream tones",
        "degraded typewriter-style lettering",
        "stains, tape and crumpled paper",
      ],
      motion: "handheld jitter, frame skips, grainy flicker",
      avoid: ["clean glossy surfaces", "bright pastels", "perfect alignment"],
    },
    related: ["punk", "collage-art", "glitch", "surveillance"],
  }),
  defineStyle({
    slug: "punk",
    name: "Punk",
    aliases: ["Punk graphics", "Punk zine", "DIY punk"],
    kind: "aesthetic",
    summary: "Ransom-note lettering, xeroxed zines, safety pins and high-contrast DIY aggression.",
    about:
      "The DIY graphics of punk flyers and zines: black-and-white photocopies, ransom-note letters cut from magazines, hand-scrawled marker, and a single shocking accent colour such as fluorescent pink or yellow.",
    tags: ["zine", "ransom-note type", "xerox", "DIY"],
    colourFacets: ["restrained", "neon"],
    formFacets: ["textured", "typographic"],
    density: "dense",
    swatches: [
      c("#F0EEE7", "xerox white"),
      c("#0F0F0F", "toner black"),
      c("#FF2E88", "fluoro pink"),
      c("#F4E12B", "fluoro yellow"),
    ],
    look: {
      colour: "toner black on white with fluorescent pink or yellow",
      texture: "high-contrast photocopy, toner specks, torn edges",
      materials: "safety pins, leather, tartan, tape, xeroxed paper",
      lighting: "harsh flash, blown-out highlights",
      composition: "chaotic cut-and-paste layouts, crooked blocks, overlapping text",
      typography: "ransom-note cut-out letters and scrawled marker",
    },
    prompt: {
      cues: [
        "ransom-note letters cut from different magazines",
        "high-contrast black-and-white photocopy texture",
        "one fluorescent pink or yellow accent",
        "crooked cut-and-paste layout with tape",
        "harsh flash photography with blown highlights",
      ],
      motion: "jerky hand-cut stop-motion, rapid xerox flicker, aggressive zooms",
      avoid: ["polished gradients", "elegant serif type", "soft pastels"],
    },
    related: ["grunge", "collage-art", "graffiti", "new-wave"],
  }),
  defineStyle({
    slug: "new-wave",
    name: "New Wave",
    aliases: ["New Wave graphics", "Swiss Punk", "Postmodern typography"],
    kind: "period",
    summary: "Late-70s/80s graphics mixing grid discipline with layered type, dots, stripes and pastel neon.",
    about:
      "Applies both to music-era record-sleeve graphics and a looser, layered successor to Swiss typography. Expect geometric shapes, dot screens, stripes, stepped type and cool pastel-plus-neon colour on a still-visible grid.",
    note: "Used for both a music-era look and a typographic approach; this entry blends the visual traits shared by both.",
    tags: ["record sleeve", "layered type", "dots and stripes", "cool colour"],
    colourFacets: ["vivid", "pastel"],
    formFacets: ["geometric", "typographic"],
    density: "balanced",
    swatches: [
      c("#EDEBE6", "sleeve white"),
      c("#111827", "night navy"),
      c("#FF4F9A", "neon rose"),
      c("#62D2E8", "cool cyan"),
    ],
    look: {
      colour: "cool cyan and neon rose with navy on white",
      texture: "dot screens, fine stripes, flat offset colour",
      materials: "vinyl sleeves, plastic, synth keys, sharp tailoring",
      lighting: "cool studio light with crisp shadows",
      composition: "a visible grid broken by layered shapes, stripes and stepped type",
      typography: "spaced-out geometric caps, stepped and layered headlines",
    },
    prompt: {
      cues: [
        "geometric shapes layered over a visible grid",
        "dot screens and fine stripe patterns",
        "cool cyan and neon rose on white with navy",
        "stepped, widely spaced geometric capitals",
        "cool studio light with crisp shadows",
      ],
      motion: "stepped slides and wipes in time with a synth beat",
      avoid: ["rustic textures", "warm earth tones", "hand-drawn wobble"],
    },
    related: ["80s-editorial", "italo-disco", "experimental-type", "memphis"],
  }),
  defineStyle({
    slug: "graffiti",
    name: "Graffiti",
    aliases: ["Graffitti", "Street art", "Spray paint", "Wildstyle"],
    kind: "technique",
    summary: "Spray-painted wildstyle letters, drips, outlines and layered tags on urban walls.",
    about:
      "Spray paint on brick, concrete and metal: interlocking wildstyle letters with arrows and 3D blocks, crisp fill-and-outline technique, overspray halos, drips and layers of older tags beneath.",
    tags: ["spray paint", "wildstyle", "urban wall", "drips"],
    colourFacets: ["vivid", "neon"],
    formFacets: ["typographic", "textured", "illustrative"],
    density: "dense",
    swatches: [
      c("#5A5652", "concrete wall"),
      c("#FF3D7F", "spray magenta"),
      c("#25D0B4", "spray mint"),
      c("#FFE33D", "chrome yellow"),
    ],
    look: {
      colour: "saturated spray colours with black and white outlines on grey concrete",
      texture: "overspray halos, drips, layered paint on rough brick or concrete",
      materials: "aerosol paint, markers, brick, steel shutters",
      lighting: "flat daylight or sodium streetlight",
      composition: "a large central piece of interlocking letters over older tags",
      typography: "wildstyle letters with arrows, 3D blocks and highlights",
    },
    prompt: {
      cues: [
        "interlocking wildstyle letters with arrows and 3D blocking",
        "crisp outlines with overspray halos and drips",
        "layered older tags beneath the main piece",
        "rough concrete or brick wall texture",
        "saturated magenta, mint and yellow spray colours",
      ],
      motion: "spray cans painting on, drips running, a tracking shot along the wall",
      avoid: ["clean vector gradients", "pastel minimalism", "serif type"],
    },
    related: ["punk", "type-doodles", "cyberpop", "grunge"],
  }),
];
