import { c, defineStyle } from "./define";

/** Retro, music-scene and internet-era nostalgia aesthetics. */
export const retroStyles = [
  defineStyle({
    slug: "70s-retro",
    name: "70’s Retro",
    aliases: ["70s Retro", "Seventies", "1970s"],
    kind: "period",
    summary: "Warm stripes, rounded display type, earthy oranges and sun-faded film.",
    about:
      "A 1970s-inspired look of rainbow stripes in warm tones, rounded bold display type, wood panelling, shag textures and slightly faded, warm film photography.",
    tags: ["warm stripes", "rounded type", "film fade", "earth tones"],
    colourFacets: ["earthy", "vivid"],
    formFacets: ["geometric", "photographic"],
    density: "balanced",
    swatches: [
      c("#F3E3C3", "sunbleached cream"),
      c("#E0762A", "burnt orange"),
      c("#B8421E", "rust red"),
      c("#6F5A1E", "olive brown"),
    ],
    look: {
      colour: "burnt orange, rust, mustard and olive brown on sun-bleached cream",
      texture: "faded warm film grain, corduroy, shag and wood panelling",
      materials: "corduroy, wood veneer, rattan, smoked glass",
      lighting: "golden-hour sun with warm lens flare",
      composition: "curved stripe bands sweeping across the frame",
      typography: "rounded, heavy display type with tight spacing",
    },
    prompt: {
      cues: [
        "curved rainbow stripe bands in warm oranges and browns",
        "sun-faded warm film grain",
        "golden-hour light with soft lens flare",
        "rounded, heavy display lettering",
        "corduroy, wood veneer and rattan textures",
      ],
      motion: "slow zooms, warm light leaks, gentle film gate weave",
      avoid: ["cold blue tones", "chrome", "sharp digital clarity"],
    },
    related: ["retro", "mid-century-modern", "psychedelic", "bohemian"],
  }),
  defineStyle({
    slug: "retro",
    name: "Retro",
    aliases: ["Vintage", "Retro design"],
    kind: "period",
    summary: "General nostalgic print look: halftone, aged paper, badges and limited ink colours.",
    about:
      "A broad vintage print look rather than one decade: limited ink colours, halftone shading, slight misregistration, badge and label layouts and aged paper. Useful when you want nostalgia without committing to a specific era.",
    note: "Broad label. Pair with a decade style for a more specific result.",
    tags: ["halftone", "aged paper", "limited ink", "badge"],
    colourFacets: ["earthy", "muted"],
    formFacets: ["illustrative", "textured"],
    density: "balanced",
    swatches: [
      c("#EFE3C8", "aged paper"),
      c("#D0442C", "poster red"),
      c("#23535E", "deep teal"),
      c("#E9B44C", "mustard ink"),
    ],
    look: {
      colour: "two or three ink colours on aged paper",
      texture: "halftone shading, slight misregistration, paper wear",
      materials: "printed labels, enamel signs, tins, matchbooks",
      lighting: "flat print light",
      composition: "badge, label and banner layouts with centred emblems",
      typography: "script and slab-serif combinations, arched lettering",
    },
    prompt: {
      cues: [
        "a limited palette of two or three ink colours",
        "halftone shading with slight misregistration",
        "aged, worn paper texture",
        "badge or label layout with arched lettering",
        "flat print lighting",
      ],
      motion: "gentle print-press jitter, paper texture drift",
      avoid: ["modern glossy 3D", "neon", "photoreal lighting"],
    },
    related: ["70s-retro", "mid-century-modern", "pop-art", "victorian-style"],
  }),
  defineStyle({
    slug: "synthwave",
    name: "Synthwave",
    aliases: ["Outrun", "Retrowave"],
    kind: "aesthetic",
    summary: "Neon grid horizons, striped sunsets and chrome type in a night-time 80s fantasy.",
    about:
      "A nostalgic, music-linked aesthetic built from imagined 1980s futures: a perspective grid running to a striped sunset, magenta and cyan neon, chrome lettering, palm silhouettes and night drives.",
    tags: ["neon grid", "sunset", "chrome type", "night drive"],
    colourFacets: ["neon", "dark"],
    formFacets: ["digital", "geometric"],
    density: "balanced",
    swatches: [
      c("#140B2E", "midnight violet"),
      c("#FF2E97", "hot magenta"),
      c("#21E6FF", "laser cyan"),
      c("#FF9F1C", "sunset orange"),
    ],
    look: {
      colour: "midnight violet with hot magenta, laser cyan and sunset orange",
      texture: "neon glow, scan lines, soft bloom",
      materials: "chrome, neon tubing, glossy car paint",
      lighting: "neon rim light and a glowing horizon sun",
      composition: "a one-point perspective grid running to a striped setting sun",
      typography: "chrome-beveled italic capitals and neon script",
    },
    prompt: {
      cues: [
        "glowing magenta perspective grid running to the horizon",
        "a large striped sunset sun on the horizon",
        "neon rim lighting with soft bloom",
        "chrome-beveled lettering",
        "palm and mountain silhouettes against a violet night sky",
      ],
      motion: "forward drive over the grid, neon flicker, sun slowly sinking",
      avoid: ["daylight scenes", "muted earth tones", "grainy film"],
    },
    related: ["vaporwave", "cyberpunk", "italo-disco", "future-funk"],
  }),
  defineStyle({
    slug: "italo-disco",
    name: "Italo Disco",
    aliases: ["Italo", "Euro disco"],
    kind: "aesthetic",
    summary: "Airbrushed chrome, laser beams, starry space backdrops and glossy synth-pop sleeves.",
    about:
      "Inspired by the record sleeves of 1980s European synth-pop: airbrushed chrome figures and lettering, laser beams, starfields, glossy cars and dramatic gradients of night sky.",
    tags: ["airbrush", "lasers", "record sleeve", "chrome"],
    colourFacets: ["neon", "metallic", "dark"],
    formFacets: ["illustrative", "dimensional"],
    density: "balanced",
    swatches: [
      c("#0D0A24", "space navy"),
      c("#E83FB4", "laser pink"),
      c("#8FD3FF", "chrome blue"),
      c("#FFD86B", "spotlight gold"),
    ],
    look: {
      colour: "space navy with laser pink, chrome blue and spotlight gold",
      texture: "smooth airbrushed gradients, star sparkles, specular highlights",
      materials: "chrome, lacquer, glitter, glossy vinyl",
      lighting: "laser beams, star glints and hard specular highlights",
      composition: "a centred chrome emblem or figure against a starry sky with beams",
      typography: "airbrushed chrome script and beveled capitals",
    },
    prompt: {
      cues: [
        "smooth airbrushed chrome with star-glint highlights",
        "laser beams crossing a starry night sky",
        "laser pink and chrome blue on deep space navy",
        "a centred emblem like a vintage record sleeve",
        "glossy lacquer and glitter surfaces",
      ],
      motion: "rotating laser beams, sparkling glints, slow spin of a chrome emblem",
      avoid: ["natural daylight", "paper texture", "earth tones"],
    },
    related: ["synthwave", "new-wave", "chromecore", "future-funk"],
  }),
  defineStyle({
    slug: "future-funk",
    name: "Future Funk",
    aliases: ["Future funk art", "City pop visuals"],
    kind: "aesthetic",
    summary: "Bright anime stills, city-pop pastels, VHS gloss and sunny 80s Japanese nostalgia.",
    about:
      "An internet aesthetic paired with sample-based dance music. Visuals borrow from 1980s anime and city-pop cover art: bright pastels, sunny skies, sparkles and VHS gloss.",
    note: "Internet-era label; often overlaps with vaporwave.",
    tags: ["anime still", "city pop", "VHS", "pastel sky"],
    colourFacets: ["pastel", "vivid"],
    formFacets: ["illustrative", "digital"],
    density: "balanced",
    swatches: [
      c("#FFE9F3", "blush"),
      c("#FF6FB5", "bubblegum"),
      c("#59C3FF", "summer sky"),
      c("#FFD447", "lemon"),
    ],
    look: {
      colour: "bubblegum pink, summer sky blue and lemon on blush",
      texture: "cel-shaded animation, VHS tracking lines, sparkles",
      materials: "cel paint, VHS tape, vinyl",
      lighting: "bright, sunny, high-key light",
      composition: "a cel-animated character or cityscape framed like a record cover",
      typography: "bubbly Japanese-style display lettering and neon script",
    },
    prompt: {
      cues: [
        "80s cel-shaded animation style with clean outlines",
        "bright bubblegum, sky blue and lemon palette",
        "sunny, high-key lighting with sparkles",
        "subtle VHS tracking lines and gloss",
        "city-pop record-cover framing",
      ],
      motion: "looping animation cycles, sparkle bursts, VHS wobble",
      avoid: ["gritty realism", "dark palettes", "heavy grunge"],
    },
    related: ["vaporwave", "pop-art", "kidcore", "synthwave"],
  }),
  defineStyle({
    slug: "vaporwave",
    name: "Vaporwave",
    aliases: ["Vapor", "Vaporwave aesthetic"],
    kind: "aesthetic",
    summary: "Pink-and-teal digital nostalgia: marble busts, early-web windows and ironic calm.",
    about:
      "An internet aesthetic that remixes 1980s and 90s consumer and computer imagery with a melancholy, ironic tone. Common elements include classical busts, checker floors, palm trees, early operating-system windows and pastel pink-teal gradients.",
    tags: ["marble bust", "pink and teal", "early OS", "checker floor"],
    colourFacets: ["pastel", "neon"],
    formFacets: ["digital", "photographic"],
    density: "balanced",
    swatches: [
      c("#FF9ECF", "vapor pink"),
      c("#7DE3E1", "pool teal"),
      c("#8A6CFF", "dusk violet"),
      c("#F4F1FF", "lavender white"),
    ],
    look: {
      colour: "vapor pink, pool teal and dusk violet",
      texture: "low-res JPEG artefacts, VHS softness, early 3D renders",
      materials: "marble statues, checker tile, palm fronds, glass",
      lighting: "flat pastel ambient light",
      composition: "surreal still-life arrangements on checker floors with floating windows",
      typography: "wide-spaced full-width Latin and Japanese characters",
    },
    prompt: {
      cues: [
        "classical marble bust in a surreal still life",
        "pink and teal pastel palette with violet dusk",
        "checkerboard floor receding into space",
        "early operating-system window frames floating in the scene",
        "low-resolution digital softness and mild JPEG artefacts",
      ],
      motion: "slow dreamy drift, looping rotations, VHS tape warble",
      avoid: ["gritty realism", "earthy palettes", "high-detail texture"],
    },
    related: ["synthwave", "web-1-0", "future-funk", "y2k"],
    featured: 5,
  }),
  defineStyle({
    slug: "gen-x-soft-club",
    name: "Gen X Soft Club",
    aliases: ["Soft Club", "Gen X soft club"],
    kind: "aesthetic",
    summary: "Late-90s soft focus: frosted blues, brushed silver, translucent tech and hazy club calm.",
    about:
      "An aesthetic label for the late-1990s and early-2000s mood of chill electronic music, portable tech and hazy club light. Images feel soft and slightly overexposed, with icy blue-grey, frosted plastics, brushed silver and gentle motion blur.",
    note: "Internet-era label; definitions vary. This entry focuses on its most consistent visual traits.",
    tags: ["soft focus", "frosted plastic", "icy blue", "late 90s"],
    colourFacets: ["pastel", "metallic"],
    formFacets: ["photographic", "digital"],
    density: "sparse",
    swatches: [
      c("#DDE7EF", "frosted blue-white"),
      c("#A8BCCB", "ice grey"),
      c("#5E7FA3", "twilight blue"),
      c("#C7CCD1", "brushed silver"),
    ],
    look: {
      colour: "frosted blue-white, ice grey, twilight blue and brushed silver",
      texture: "soft focus, bloom, slight overexposure, gentle motion blur",
      materials: "translucent frosted plastic, brushed aluminium, mesh fabric",
      lighting: "hazy, diffused light as if through frosted glass or club haze",
      composition: "calm off-centre subjects with lots of hazy negative space",
      typography: "small, light, wide-set sans-serif in lowercase",
    },
    prompt: {
      cues: [
        "soft focus with gentle bloom and slight overexposure",
        "frosted translucent plastics and brushed silver",
        "icy blue-grey palette",
        "hazy diffused light like club haze or frosted glass",
        "calm off-centre subject with airy negative space",
        "subtle motion blur",
      ],
      motion: "slow floating camera, soft motion blur trails, drifting haze",
      avoid: ["hard contrast", "saturated neon", "gritty texture"],
    },
    related: ["y2k", "cyberminimalism", "chromecore", "aurora"],
    featured: 3,
  }),
  defineStyle({
    slug: "psychedelic",
    name: "Psychedelic",
    aliases: ["Psychedelia", "Psychedelic art", "60s psychedelic"],
    kind: "movement",
    summary: "Melting lettering, vibrating complementary colour and swirling optical patterns.",
    about:
      "Associated with 1960s concert posters and counterculture. Lettering swells and warps to fill shapes, complementary colours vibrate against each other, and patterns swirl, radiate and repeat to disorient the eye.",
    tags: ["melting type", "vibrating colour", "swirls", "concert poster"],
    colourFacets: ["vivid", "neon"],
    formFacets: ["organic", "typographic", "ornamental"],
    density: "dense",
    swatches: [
      c("#FF6B1A", "tangerine"),
      c("#7B2FBF", "purple haze"),
      c("#2FBF71", "electric green"),
      c("#FFD23F", "marigold"),
    ],
    look: {
      colour: "clashing complementary pairs: orange against purple, green against magenta",
      texture: "flat screen-print colour, optical line patterns",
      materials: "screen-printed posters, tie-dye fabric, liquid light projections",
      lighting: "flat poster light, or oily liquid-light projections",
      composition: "swirling, radiating patterns that fill every part of the frame",
      typography: "swelling, melting letters distorted to fill shapes",
    },
    prompt: {
      cues: [
        "swirling, radiating concentric patterns filling the frame",
        "vibrating complementary colours, tangerine against purple",
        "melting, swelling hand-drawn lettering",
        "optical line patterns that ripple",
        "flat screen-print colour",
      ],
      motion: "breathing, morphing patterns, colour cycling, oil-projection flow",
      avoid: ["muted neutrals", "empty space", "rigid grids"],
    },
    related: ["acid", "70s-retro", "art-nouveau", "surreal-design"],
    featured: 10,
  }),
  defineStyle({
    slug: "acid",
    name: "Acid",
    aliases: ["Acid graphics", "Acid design", "Acid aesthetic"],
    kind: "aesthetic",
    summary: "Rave-derived graphics: warped chrome type, acid green, stark black and liquid distortion.",
    about:
      "A contemporary graphic trend drawing on rave flyers and early digital art. It uses warped or liquid chrome lettering, acid green and electric colour against black, wireframes, smiley-like icons and heavy distortion effects.",
    note: "Contemporary design label; overlaps with Chromecore and Y2K.",
    tags: ["rave", "liquid type", "acid green", "distortion"],
    colourFacets: ["neon", "dark", "metallic"],
    formFacets: ["digital", "typographic"],
    density: "dense",
    swatches: [
      c("#0A0A0A", "rave black"),
      c("#B6FF1A", "acid green"),
      c("#D9D9D9", "liquid chrome"),
      c("#7A5CFF", "ultraviolet"),
    ],
    look: {
      colour: "stark black with acid green, ultraviolet and liquid chrome",
      texture: "liquid distortion, wireframe meshes, blown-out glow",
      materials: "liquid chrome, holographic foil, PVC",
      lighting: "strobe and blacklight glow",
      composition: "centred warped type or emblem, stretched and mirrored to the edges",
      typography: "liquefied, stretched chrome display type and blackletter hybrids",
    },
    prompt: {
      cues: [
        "liquefied, warped chrome lettering",
        "acid green and ultraviolet on stark black",
        "wireframe meshes and stretched distortion",
        "blacklight glow and strobe highlights",
        "mirrored, symmetrical composition",
      ],
      motion: "liquid morphing, strobe flashes, pulsing distortions on the beat",
      avoid: ["soft pastels", "paper textures", "calm minimal space"],
    },
    related: ["chromecore", "psychedelic", "y2k", "glitch"],
  }),
  defineStyle({
    slug: "kidcore",
    name: "Kidcore",
    aliases: ["Kid core", "Childcore"],
    kind: "aesthetic",
    summary: "Primary brights, crayon texture, stickers and toy-box nostalgia for childhood.",
    about:
      "An internet aesthetic built on childhood visual culture: primary colours, crayon and marker drawings, stickers, beads, toys, rainbows and playground plastic.",
    note: "Internet-era label; definitions vary.",
    tags: ["primary brights", "crayon", "stickers", "toys"],
    colourFacets: ["vivid"],
    formFacets: ["illustrative", "textured"],
    density: "dense",
    swatches: [
      c("#FFF7E0", "construction paper"),
      c("#FF3B30", "crayon red"),
      c("#FFCC00", "school-bus yellow"),
      c("#1E88E5", "toy blue"),
    ],
    look: {
      colour: "crayon red, school-bus yellow, toy blue and grass green",
      texture: "crayon wax, marker streaks, glitter glue, plastic shine",
      materials: "construction paper, stickers, beads, plastic toys",
      lighting: "bright, cheerful flat light",
      composition: "cluttered, joyful arrangements of stickers and toys",
      typography: "chunky rounded letters, alphabet-block type",
    },
    prompt: {
      cues: [
        "crayon and marker drawing textures",
        "primary red, yellow and blue with grass green",
        "stickers, beads and plastic toys scattered playfully",
        "chunky rounded alphabet-block lettering",
        "bright, cheerful flat lighting",
      ],
      motion: "bouncy toy-like movement, stickers popping on, wobbly hand-drawn loops",
      avoid: ["muted neutrals", "moody lighting", "sophisticated minimalism"],
    },
    related: ["naive", "type-doodles", "memphis", "clay-style"],
  }),
  defineStyle({
    slug: "y2k",
    name: "Y2K",
    aliases: ["Y2K aesthetic", "Millennium", "Y2K futurism"],
    kind: "aesthetic",
    summary: "Translucent plastics, chrome blobs, iridescence and optimistic millennium tech.",
    about:
      "A look drawn from late-1990s and early-2000s consumer tech and pop culture: translucent coloured plastics, chrome and iridescent surfaces, blobby 3D forms, lens flares and techno-optimistic interfaces.",
    tags: ["translucent plastic", "chrome", "iridescent", "blobs"],
    colourFacets: ["metallic", "pastel", "vivid"],
    formFacets: ["digital", "dimensional"],
    density: "balanced",
    swatches: [
      c("#E8F1F8", "ice white"),
      c("#3FA7D6", "translucent aqua"),
      c("#C6CBD4", "chrome silver"),
      c("#F49AC2", "iridescent pink"),
    ],
    look: {
      colour: "ice white, translucent aqua, chrome silver and iridescent pink",
      texture: "glossy translucent plastic, iridescent film, chrome reflections",
      materials: "translucent polycarbonate, chrome, holographic foil, mesh",
      lighting: "bright studio light with lens flares and sharp specular highlights",
      composition: "floating blobby 3D objects with orbiting rings and sparkles",
      typography: "extended techno sans-serif and bubble lettering",
    },
    prompt: {
      cues: [
        "translucent coloured plastic with visible inner parts",
        "chrome and iridescent reflective surfaces",
        "blobby, rounded 3D forms",
        "bright studio light with lens flares",
        "floating orbit rings and sparkles",
      ],
      motion: "floating, rotating objects, lens-flare sweeps, glossy highlights gliding",
      avoid: ["rustic materials", "muted earth tones", "flat paper texture"],
    },
    related: ["gen-x-soft-club", "chromecore", "bubbleglam", "web-2-0-gloss"],
    references: ["imac-g3-bondi"],
    featured: 9,
  }),
  defineStyle({
    slug: "bubbleglam",
    name: "Bubbleglam",
    aliases: ["Bubble glam", "Bubblegum glam"],
    kind: "aesthetic",
    summary: "Inflated glossy shapes, candy pinks, rhinestone sparkle and puffy balloon lettering.",
    about:
      "A playful glam look of inflated, balloon-like forms: glossy candy colours, puffy lettering, rhinestones, glitter and soft pink studio light.",
    note: "Informal internet-era label; definitions vary. Adjacent to Y2K.",
    tags: ["inflated", "glossy", "rhinestones", "candy pink"],
    colourFacets: ["pastel", "vivid"],
    formFacets: ["dimensional", "digital"],
    density: "balanced",
    swatches: [
      c("#FFE3F1", "cotton candy"),
      c("#FF4FA3", "hot bubblegum"),
      c("#B98CFF", "lilac"),
      c("#FFF4B8", "champagne"),
    ],
    look: {
      colour: "cotton candy, hot bubblegum, lilac and champagne",
      texture: "high-gloss inflated vinyl, glitter, rhinestone facets",
      materials: "inflatable vinyl, latex balloons, rhinestones, glitter",
      lighting: "soft pink studio light with bright specular highlights",
      composition: "puffy objects clustered and floating, lots of shine",
      typography: "puffy inflated balloon letters",
    },
    prompt: {
      cues: [
        "inflated, puffy balloon-like forms with high gloss",
        "candy pink, lilac and champagne palette",
        "rhinestone and glitter sparkle",
        "soft pink studio light with bright specular highlights",
        "puffy balloon lettering",
      ],
      motion: "bouncy inflating and squishing, sparkles twinkling",
      avoid: ["matte earth tones", "sharp angular forms", "grunge"],
    },
    related: ["y2k", "clay-style", "kidcore", "chromecore"],
  }),
];
