import type { PaletteRecord } from "../types";
import { stylePalette } from "./define";

/** Palettes made for the craft styles (src/content/styles/craft.ts), four per style. */
export const craftPalettes: PaletteRecord[] = [
  // ——— Vector Minimalism ———
  stylePalette("vector-minimalism", {
    slug: "vector-minimalism-deep-teal",
    name: "Deep Teal",
    mood: "Calm, flat, modern",
    description: "Sand white and a deep teal. A two-colour flat system for icons and illustration.",
    composition: "wave",
    colours: [["#F3EDE2", "sand white", 68], ["#274C5E", "deep teal", 32]],
  }),
  stylePalette("vector-minimalism", {
    slug: "vector-minimalism-terracotta-sun",
    name: "Terracotta Sun",
    mood: "Warm, simple, friendly",
    description: "Sand, deep teal and a terracotta sun. Complementary warm and cool, kept flat.",
    composition: "arch",
    colours: [["#F4EEE3", "sand", 60], ["#264A5B", "deep teal", 28], ["#E07A5F", "terracotta", 12]],
  }),
  stylePalette("vector-minimalism", {
    slug: "vector-minimalism-dune",
    name: "Dune",
    mood: "Balanced, sunny, minimal",
    description: "Sand white, deep teal, wheat and terracotta. The classic flat-illustration quartet for startups and editorial.",
    composition: "wave",
    colours: [["#F3EDE2", "sand white", 44], ["#274C5E", "deep teal", 28], ["#F2CC8F", "wheat", 16], ["#E07A5F", "terracotta", 12]],
  }),
  stylePalette("vector-minimalism", {
    slug: "vector-minimalism-fjord",
    name: "Fjord",
    mood: "Cool, crisp, Nordic",
    description: "Pale mist, ink blue, a glacier blue and a lingonberry red. A cooler flat palette for travel and outdoor.",
    composition: "steps",
    colours: [["#ECF0F1", "pale mist", 46], ["#1D3247", "ink blue", 28], ["#8FB7CC", "glacier blue", 16], ["#C84B4B", "lingonberry", 10]],
  }),

  // ——— Vector Art ———
  stylePalette("vector-art", {
    slug: "vector-art-ink-navy",
    name: "Ink Navy",
    mood: "Clean, bold, illustrative",
    description: "Canvas cream and ink navy: the outline and text colour that holds vector art together.",
    composition: "orbit",
    colours: [["#FFF6E9", "canvas cream", 66], ["#2D3047", "ink navy", 34]],
  }),
  stylePalette("vector-art", {
    slug: "vector-art-tangerine",
    name: "Tangerine",
    mood: "Energetic, warm, crisp",
    description: "Cream, ink navy and a tangerine. Navy and orange are near-complements, so the orange glows.",
    composition: "orbit",
    colours: [["#FFF5E6", "canvas cream", 60], ["#2D3047", "ink navy", 28], ["#FF9B42", "tangerine", 12]],
  }),
  stylePalette("vector-art", {
    slug: "vector-art-jade-orange",
    name: "Jade & Orange",
    mood: "Vivid, balanced, friendly",
    description: "Cream, ink navy, jade and tangerine. Saturated flats with a dark key, for illustration-led brands.",
    composition: "fields",
    colours: [["#FFF6E9", "canvas cream", 44], ["#2D3047", "ink navy", 28], ["#1B998B", "jade", 16], ["#FF9B42", "tangerine", 12]],
  }),
  stylePalette("vector-art", {
    slug: "vector-art-berry",
    name: "Berry Pop",
    mood: "Juicy, playful, bright",
    description: "Pale pink, deep plum outlines, a berry red and a leaf green. Bright vector illustration for food and kids.",
    composition: "orbit",
    colours: [["#FCEDEF", "pale pink", 46], ["#3A1D3F", "plum outline", 28], ["#E2445C", "berry red", 16], ["#5BB55A", "leaf green", 10]],
  }),

  // ——— Clay Style ———
  stylePalette("clay-style", {
    slug: "clay-style-cocoa",
    name: "Peach & Cocoa",
    mood: "Soft, warm, friendly",
    description: "Peach clay with a cocoa text colour. Matte warmth that stays readable.",
    composition: "orbit",
    colours: [["#FBE7D4", "peach clay", 68], ["#5A3A2E", "cocoa", 32]],
  }),
  stylePalette("clay-style", {
    slug: "clay-style-powder",
    name: "Powder Room",
    mood: "Gentle, calm, playful",
    description: "Powder blue clay, deep blue text and a butter accent. Soft 3D for apps and onboarding.",
    composition: "orbit",
    colours: [["#CDE7EC", "powder blue clay", 60], ["#1F3F57", "deep blue", 28], ["#F6D55C", "butter clay", 12]],
  }),
  stylePalette("clay-style", {
    slug: "clay-style-playdough",
    name: "Playdough",
    mood: "Cheerful, squishy, warm",
    description: "Butter, plum text, coral and powder blue. A bright clay set with a dark anchor for headlines.",
    composition: "orbit",
    colours: [["#FCEFC7", "butter", 44], ["#3E2341", "plum", 28], ["#F28C8C", "coral clay", 16], ["#8AC6D0", "powder blue", 12]],
  }),
  stylePalette("clay-style", {
    slug: "clay-style-sage-pot",
    name: "Sage Pot",
    mood: "Earthy, soft, homely",
    description: "Sage clay ground, forest text, a terracotta pot and a cream glaze. Clay style for plants, food and home.",
    composition: "arch",
    colours: [["#D8E2CF", "sage clay", 48], ["#2C3B2A", "forest", 26], ["#D9825F", "terracotta pot", 16], ["#FBF2E2", "cream glaze", 10]],
  }),

  // ——— Naïve ———
  stylePalette("naive", {
    slug: "naive-night-blue",
    name: "Night Blue",
    mood: "Sincere, simple, quiet",
    description: "Gesso and a deep night blue, unmixed. Folk painting at its plainest.",
    composition: "fields",
    colours: [["#E8DDC4", "gesso", 68], ["#243A5E", "night blue", 32]],
  }),
  stylePalette("naive", {
    slug: "naive-orchard",
    name: "Orchard",
    mood: "Joyful, rural, warm",
    description: "Gesso, leaf green and barn red apples. Complementary pairs straight from the tube.",
    composition: "orbit",
    colours: [["#ECE2CB", "gesso", 60], ["#2F6B3A", "leaf green", 28], ["#C2452D", "barn red", 12]],
  }),
  stylePalette("naive", {
    slug: "naive-village-fair",
    name: "Village Fair",
    mood: "Festive, folk, bright",
    description: "Gesso, night blue, barn red and a sunflower yellow. Bold unmixed colour for markets, food and kids’ books.",
    composition: "steps",
    colours: [["#E8DDC4", "gesso", 44], ["#243A5E", "night blue", 28], ["#C2452D", "barn red", 16], ["#E8B83A", "sunflower", 12]],
  }),
  stylePalette("naive", {
    slug: "naive-rousseau",
    name: "Jungle Dream",
    mood: "Lush, dreamlike, bold",
    description: "Deep jungle green, pale moon text, an orange sun and a pink bloom. Rousseau-style jungles for art and books.",
    composition: "orbit",
    colours: [["#1F3D2A", "jungle green", 50], ["#F0E6C8", "pale moon", 26], ["#E9773A", "orange sun", 14], ["#E58BA5", "pink bloom", 10]],
  }),

  // ——— Surreal Design ———
  stylePalette("surreal-design", {
    slug: "surreal-design-long-shadow",
    name: "Long Shadow",
    mood: "Still, eerie, dreamlike",
    description: "Desert sand and a violet long shadow. Two calm colours with something wrong about them.",
    composition: "arch",
    colours: [["#E9D8C4", "desert sand", 68], ["#3E3A4F", "long shadow", 32]],
  }),
  stylePalette("surreal-design", {
    slug: "surreal-design-red-door",
    name: "Red Door",
    mood: "Mysterious, calm, uncanny",
    description: "Sand, shadow violet and one red door. The single unexpected accent the style is built on.",
    composition: "arch",
    colours: [["#EAD9C5", "desert sand", 60], ["#3E3A4F", "long shadow", 30], ["#B34A3C", "red door", 10]],
  }),
  stylePalette("surreal-design", {
    slug: "surreal-design-dream-sky",
    name: "Dream Sky",
    mood: "Serene, impossible, airy",
    description: "Dream sky blue, deep violet text, sand and a red door. Sky and desert, made strange.",
    composition: "window",
    colours: [["#BFD5EA", "dream sky", 46], ["#2E2A40", "deep violet", 28], ["#E9D8C4", "desert sand", 16], ["#B34A3C", "red door", 10]],
  }),
  stylePalette("surreal-design", {
    slug: "surreal-design-melting-hour",
    name: "Melting Hour",
    mood: "Warm, uncanny, cinematic",
    description: "Dusk peach, midnight text, a lilac haze and a lemon moon. Surreal sunset for music and fashion.",
    composition: "orbit",
    colours: [["#F2CFB3", "dusk peach", 48], ["#22203A", "midnight", 26], ["#B8A6D6", "lilac haze", 16], ["#F4E07A", "lemon moon", 10]],
  }),

  // ——— Luxury Minimal ———
  stylePalette("luxury-minimal", {
    slug: "luxury-minimal-travertine",
    name: "Travertine",
    mood: "Quiet, refined, expensive",
    description: "Travertine and espresso. Luxury says less: two colours, generous space.",
    composition: "arch",
    colours: [["#EDE6DC", "travertine", 72], ["#2B2622", "espresso", 28]],
  }),
  stylePalette("luxury-minimal", {
    slug: "luxury-minimal-brass-line",
    name: "Brass Line",
    mood: "Elegant, warm, restrained",
    description: "Travertine, espresso and a thin brushed-brass line. The brass is for rules and small details only.",
    composition: "arch",
    colours: [["#EEE7DD", "travertine", 64], ["#2B2622", "espresso", 28], ["#9C7C4A", "brushed brass", 8]],
  }),
  stylePalette("luxury-minimal", {
    slug: "luxury-minimal-cashmere",
    name: "Cashmere",
    mood: "Soft, tactile, premium",
    description: "Ivory, espresso text, cashmere panels and a brass accent. For fashion, hotels and beauty.",
    composition: "fields",
    colours: [["#F3EEE6", "ivory", 46], ["#2B2622", "espresso", 28], ["#C8B79E", "cashmere", 16], ["#9C7C4A", "brushed brass", 10]],
  }),
  stylePalette("luxury-minimal", {
    slug: "luxury-minimal-noir",
    name: "Noir",
    mood: "Dark, discreet, opulent",
    description: "Espresso-black ground, travertine type, a smoked taupe and a champagne line. Evening luxury for fragrance and jewellery.",
    composition: "window",
    colours: [["#1E1A17", "espresso black", 54], ["#E8E0D4", "travertine", 26], ["#5B5048", "smoked taupe", 12], ["#C9AE7C", "champagne", 8]],
  }),

  // ——— Maximalism ———
  stylePalette("maximalism", {
    slug: "maximalism-saffron-green",
    name: "Saffron Room",
    mood: "Rich, bold, layered",
    description: "Bottle green walls and saffron. Two jewel tones at full strength.",
    composition: "arch",
    colours: [["#1F3B2D", "bottle green", 64], ["#E3A72F", "saffron", 36]],
  }),
  stylePalette("maximalism", {
    slug: "maximalism-raspberry-velvet",
    name: "Raspberry Velvet",
    mood: "Lush, theatrical, warm",
    description: "Raspberry velvet, blush type and a saffron fringe. Saturated and confident for fashion and hospitality.",
    composition: "orbit",
    colours: [["#8E1D49", "raspberry velvet", 58], ["#F6DCE2", "blush", 30], ["#E3A72F", "saffron", 12]],
  }),
  stylePalette("maximalism", {
    slug: "maximalism-jewel-box",
    name: "Treasure",
    mood: "Opulent, eclectic, joyful",
    description: "Sapphire, cream type, raspberry and saffron: jewel tones balanced by one light colour. For interiors and boutiques.",
    composition: "fields",
    colours: [["#25336E", "sapphire", 46], ["#F5ECDA", "cream", 26], ["#B0265B", "raspberry", 16], ["#E3A72F", "saffron", 12]],
  }),
  stylePalette("maximalism", {
    slug: "maximalism-chinoiserie",
    name: "Chinoiserie",
    mood: "Decorative, collected, rich",
    description: "Cream, deep bottle green, coral and a peacock blue. Patterned-wallpaper richness on a light ground.",
    composition: "wave",
    colours: [["#F4ECDC", "cream", 46], ["#1F3B2D", "bottle green", 28], ["#E06B57", "coral", 14], ["#1E6E86", "peacock blue", 12]],
  }),

  // ——— Gothic ———
  stylePalette("gothic", {
    slug: "gothic-raven",
    name: "Raven",
    mood: "Dark, solemn, severe",
    description: "Raven black and a pale bone. Gothic contrast without decoration.",
    composition: "arch",
    colours: [["#0F0D0E", "raven black", 70], ["#DCD5C7", "pale bone", 30]],
  }),
  stylePalette("gothic", {
    slug: "gothic-oxblood",
    name: "Oxblood Vault",
    mood: "Brooding, rich, ancient",
    description: "Raven black, aged-gold type and an oxblood seal. Warm darkness for music, books and wine.",
    composition: "arch",
    colours: [["#110E0F", "raven black", 60], ["#B8975A", "aged gold", 28], ["#6E1A27", "oxblood", 12]],
  }),
  stylePalette("gothic", {
    slug: "gothic-cathedral-stone",
    name: "Nave",
    mood: "Monumental, cold, sacred",
    description: "Black, stone-grey type, oxblood and aged gold. A complete gothic system with stone carrying the text.",
    composition: "arch",
    colours: [["#0F0D0E", "raven black", 46], ["#C9C5BE", "cathedral stone", 28], ["#5A1520", "oxblood", 16], ["#A88A4E", "aged gold", 10]],
  }),
  stylePalette("gothic", {
    slug: "gothic-rose-window",
    name: "Rose Window",
    mood: "Mystic, jewelled, dark",
    description: "Midnight ground, parchment type, stained-glass ruby and a cobalt pane. Light through gothic glass.",
    composition: "orbit",
    colours: [["#141022", "midnight", 50], ["#E5DCC6", "parchment", 26], ["#9E1B32", "ruby glass", 14], ["#2A4BA0", "cobalt pane", 10]],
  }),

  // ——— Steampunk ———
  stylePalette("steampunk", {
    slug: "steampunk-brass-walnut",
    name: "Brass & Walnut",
    mood: "Mechanical, warm, Victorian",
    description: "Smoked walnut and polished brass. The machine room in two colours.",
    composition: "orbit",
    colours: [["#2A1E17", "smoked walnut", 68], ["#C4934A", "polished brass", 32]],
  }),
  stylePalette("steampunk", {
    slug: "steampunk-patent",
    name: "Patent Office",
    mood: "Inventive, papery, precise",
    description: "Parchment, walnut ink and an oxidised copper stamp. Blueprint-era paperwork for maker brands.",
    composition: "window",
    colours: [["#E6D7B3", "parchment", 60], ["#2D211A", "walnut ink", 28], ["#8A4B2A", "oxidised copper", 12]],
  }),
  stylePalette("steampunk", {
    slug: "steampunk-airship",
    name: "Airship",
    mood: "Adventurous, rich, mechanical",
    description: "Walnut, parchment type, copper and a verdigris patina. Warm metals with one cool green to break them up.",
    composition: "arch",
    colours: [["#2A1E17", "smoked walnut", 48], ["#DDCBA4", "parchment", 26], ["#A85A30", "copper", 16], ["#4F8A7A", "verdigris", 10]],
  }),
  stylePalette("steampunk", {
    slug: "steampunk-boiler-room",
    name: "Boiler Room",
    mood: "Hot, gritty, industrial",
    description: "Soot iron ground, brass type, a furnace orange and a steam grey. Heat and pressure for games and bars.",
    composition: "stripes",
    colours: [["#1C1A18", "soot iron", 50], ["#C9A05A", "brass", 24], ["#D9622B", "furnace orange", 14], ["#8D8A84", "steam grey", 12]],
  }),

  // ——— Bohemian ———
  stylePalette("bohemian", {
    slug: "bohemian-terracotta",
    name: "Terracotta Linen",
    mood: "Earthy, relaxed, warm",
    description: "Unbleached linen and a deep terracotta. Sun-baked and easy, for lifestyle and wellness.",
    composition: "arch",
    colours: [["#F1E4D3", "unbleached linen", 66], ["#9E4E2C", "terracotta", 34]],
  }),
  stylePalette("bohemian", {
    slug: "bohemian-olive-grove",
    name: "Olive Grove",
    mood: "Natural, calm, wandering",
    description: "Linen, olive-leaf text and a turmeric accent. Muted greens and spice for food and travel.",
    composition: "wave",
    colours: [["#F0E3D0", "linen", 60], ["#4F5A35", "deep olive", 28], ["#D9A441", "turmeric", 12]],
  }),
  stylePalette("bohemian", {
    slug: "bohemian-kilim",
    name: "Kilim",
    mood: "Woven, warm, collected",
    description: "Linen, a deep madder brown, terracotta and indigo. Rug colours for interiors and handmade goods.",
    composition: "stripes",
    colours: [["#F1E4D3", "linen", 44], ["#4A2A22", "madder brown", 28], ["#C0643C", "terracotta", 16], ["#3A4F7A", "indigo", 12]],
  }),
  stylePalette("bohemian", {
    slug: "bohemian-desert-bloom",
    name: "Desert Bloom",
    mood: "Sunny, free, soft",
    description: "Sand rose ground, umber text, a sage leaf and a marigold bloom. Bohemian softness for weddings and festivals.",
    composition: "orbit",
    colours: [["#EED7C8", "sand rose", 48], ["#3E2A20", "umber", 26], ["#8E9B6C", "sage leaf", 16], ["#E3A23A", "marigold", 10]],
  }),

  // ——— Victorian Style ———
  stylePalette("victorian-style", {
    slug: "victorian-style-engraving",
    name: "Engraving",
    mood: "Formal, detailed, historic",
    description: "Engraving paper and indigo ink. The printed page of the period.",
    composition: "window",
    colours: [["#E6DBC4", "engraving paper", 68], ["#1D2A44", "indigo ink", 32]],
  }),
  stylePalette("victorian-style", {
    slug: "victorian-style-parlour",
    name: "Parlour",
    mood: "Rich, cosy, ornate",
    description: "Plum walls, cream type and a gilt frame. Heavy drapes and candlelight for hospitality and books.",
    composition: "arch",
    colours: [["#4A2338", "plum", 60], ["#ECE1C9", "cream", 28], ["#C9A45A", "gilt", 12]],
  }),
  stylePalette("victorian-style", {
    slug: "victorian-style-apothecary",
    name: "Apothecary",
    mood: "Curious, crafted, vintage",
    description: "Cream label, bottle-green text, gilt and a plum seal. Old-chemist packaging for beauty and drinks.",
    composition: "window",
    colours: [["#EDE3CC", "cream label", 46], ["#1F3A2E", "bottle green", 28], ["#C9A45A", "gilt", 14], ["#5A2D45", "plum seal", 12]],
  }),
  stylePalette("victorian-style", {
    slug: "victorian-style-midnight-library",
    name: "Midnight Library",
    mood: "Scholarly, dark, romantic",
    description: "Indigo ground, parchment text, a bottle green and gilt edges. For bookshops, publishers and literary sites.",
    composition: "arch",
    colours: [["#1A2540", "indigo", 50], ["#E8DDC6", "parchment", 26], ["#2F5242", "bottle green", 14], ["#C9A45A", "gilt edge", 10]],
  }),
];
