import type { PaletteRecord } from "../types";
import { stylePalette } from "./define";

/** Palettes made for the digital styles (src/content/styles/digital.ts), four per style. */
export const digitalPalettes: PaletteRecord[] = [
  // ——— Web 1.0 ———
  stylePalette("web-1-0", {
    slug: "web-1-0-hyperlink",
    name: "Hyperlink",
    mood: "Raw, early, functional",
    description: "System grey with an unvisited hyperlink blue. The browser default as a design choice.",
    composition: "window",
    colours: [["#C0C0C0", "system grey", 70], ["#0000CC", "hyperlink blue", 30]],
  }),
  stylePalette("web-1-0", {
    slug: "web-1-0-title-bar",
    name: "Title Bar",
    mood: "Boxy, nostalgic, utilitarian",
    description: "System grey, navy title bar and a visited-link purple. An old operating system, ready for retro UIs.",
    composition: "window",
    colours: [["#C3C3C3", "system grey", 58], ["#000080", "navy title bar", 30], ["#551A8B", "visited purple", 12]],
  }),
  stylePalette("web-1-0", {
    slug: "web-1-0-geocities",
    name: "Homepage",
    mood: "Earnest, loud, handmade",
    description: "White page, black text, link blue and a highlighter yellow. Under-construction energy for fan sites and zines.",
    composition: "stripes",
    colours: [["#FFFFFF", "page white", 46], ["#000000", "text black", 28], ["#0000EE", "link blue", 16], ["#FFFF00", "highlight yellow", 10]],
  }),
  stylePalette("web-1-0", {
    slug: "web-1-0-dial-up",
    name: "Dial-Up",
    mood: "Dark, hacker, retro",
    description: "Black screen, terminal green, a web-safe cyan and a magenta marquee. The night-time web, circa 1997.",
    composition: "stripes",
    colours: [["#000000", "screen black", 52], ["#00FF66", "terminal green", 24], ["#00CCFF", "web-safe cyan", 14], ["#FF00CC", "magenta marquee", 10]],
  }),

  // ——— Web 2.0 Gloss ———
  stylePalette("web-2-0-gloss", {
    slug: "web-2-0-gloss-gel-blue",
    name: "Gel Button",
    mood: "Friendly, glossy, optimistic",
    description: "Page white and a deep gel blue. The beta-badge era’s most trusted button colour.",
    composition: "orbit",
    colours: [["#FFFFFF", "page white", 68], ["#1E6FD0", "gel blue", 32]],
  }),
  stylePalette("web-2-0-gloss", {
    slug: "web-2-0-gloss-beta",
    name: "Beta",
    mood: "Fresh, social, upbeat",
    description: "White, slate type and a lime gel badge. Startup cheer for apps and launches.",
    composition: "orbit",
    colours: [["#FAFBFC", "page white", 60], ["#2D3640", "slate", 30], ["#7ED321", "lime gel", 10]],
  }),
  stylePalette("web-2-0-gloss", {
    slug: "web-2-0-gloss-mashup",
    name: "Mashup",
    mood: "Shiny, energetic, connected",
    description: "White, charcoal type, gel blue and tangerine. Complementary gels for a full 2006-style interface.",
    composition: "fields",
    colours: [["#FFFFFF", "page white", 44], ["#2A2F36", "charcoal", 28], ["#3BA0FF", "gel blue", 16], ["#FF7F2A", "tangerine gel", 12]],
  }),
  stylePalette("web-2-0-gloss", {
    slug: "web-2-0-gloss-reflection",
    name: "Reflection",
    mood: "Polished, aqua, clean",
    description: "Pale aqua, deep navy text, a lime badge and a pink star. Glossy reflections for playful products.",
    composition: "wave",
    colours: [["#E6F4FB", "pale aqua", 46], ["#163352", "deep navy", 28], ["#8BD12E", "lime badge", 14], ["#FF5FA2", "pink star", 12]],
  }),

  // ——— Skeuomorphism ———
  stylePalette("skeuomorphism", {
    slug: "skeuomorphism-notepad",
    name: "Notepad",
    mood: "Familiar, tactile, warm",
    description: "Notepad yellow and a shadow-brown ink. The legal-pad look for notes and writing apps.",
    composition: "fields",
    colours: [["#E9DCB4", "notepad yellow", 70], ["#2E2A26", "shadow brown", 30]],
  }),
  stylePalette("skeuomorphism", {
    slug: "skeuomorphism-leather-stitch",
    name: "Leather Stitch",
    mood: "Rich, crafted, physical",
    description: "Saddle leather, stitched cream and a brass button. Calendar-app luxury for premium tools.",
    composition: "window",
    colours: [["#5E3A21", "saddle leather", 60], ["#EADBB8", "stitch cream", 28], ["#C49A4A", "brass", 12]],
  }),
  stylePalette("skeuomorphism", {
    slug: "skeuomorphism-desk",
    name: "Desk Set",
    mood: "Ordered, physical, nostalgic",
    description: "Notepad cream, ink brown, brushed steel and a red bookmark. A full desktop of real materials.",
    composition: "fields",
    colours: [["#ECE1C4", "notepad cream", 44], ["#2E2A26", "ink brown", 28], ["#A9ADB2", "brushed steel", 16], ["#B53A2C", "bookmark red", 12]],
  }),
  stylePalette("skeuomorphism", {
    slug: "skeuomorphism-hi-fi",
    name: "Hi-Fi",
    mood: "Analogue, precise, warm",
    description: "Brushed steel, black knobs, a walnut panel and a VU-meter amber. Audio apps and music tools.",
    composition: "window",
    colours: [["#B8BCC0", "brushed steel", 46], ["#1B1B1C", "knob black", 28], ["#6B4528", "walnut panel", 16], ["#F2A93B", "VU amber", 10]],
  }),

  // ——— Neumorphism ———
  stylePalette("neumorphism", {
    slug: "neumorphism-soft-slate",
    name: "Soft Slate",
    mood: "Soft, tactile, calm",
    description: "One soft grey surface with slate text. Neumorphism with the legibility it often lacks.",
    composition: "orbit",
    colours: [["#E4E8EE", "soft grey", 72], ["#4A5568", "slate", 28]],
  }),
  stylePalette("neumorphism", {
    slug: "neumorphism-calm-control",
    name: "Calm Control",
    mood: "Gentle, precise, modern",
    description: "Soft grey, deep slate text and a periwinkle active state. A clear accent for toggles and sliders.",
    composition: "orbit",
    colours: [["#E6EAF0", "soft grey", 62], ["#3B4659", "deep slate", 28], ["#6D7CF2", "periwinkle", 10]],
  }),
  stylePalette("neumorphism", {
    slug: "neumorphism-warm-clay",
    name: "Warm Clay",
    mood: "Cosy, soft, organic",
    description: "Warm putty, cocoa text, a darker putty shadow and a terracotta active state. Neumorphism moved off cold grey.",
    composition: "orbit",
    colours: [["#ECE5DD", "warm putty", 48], ["#4A3B33", "cocoa", 26], ["#CFC4B8", "putty shadow", 16], ["#C8694A", "terracotta", 10]],
  }),
  stylePalette("neumorphism", {
    slug: "neumorphism-dark-dial",
    name: "Dark Dial",
    mood: "Quiet, premium, nocturnal",
    description: "Graphite surface, pale grey text, a darker shadow and a mint indicator. Soft UI in dark mode.",
    composition: "orbit",
    colours: [["#2A2D33", "graphite surface", 50], ["#D5D9E0", "pale grey", 26], ["#1E2025", "deep shadow", 14], ["#5BE0B3", "mint indicator", 10]],
  }),

  // ——— Glassmorphism ———
  stylePalette("glassmorphism", {
    slug: "glassmorphism-frost-indigo",
    name: "Frosted Indigo",
    mood: "Deep, luminous, modern",
    description: "Deep indigo behind frost-white glass. The base of every glass card.",
    composition: "orbit",
    colours: [["#1B1F3B", "deep indigo", 68], ["#E9ECFF", "frost white", 32]],
  }),
  stylePalette("glassmorphism", {
    slug: "glassmorphism-violet-orb",
    name: "Violet Orb",
    mood: "Glowing, airy, techy",
    description: "Indigo ground, frost-white text and a violet orb glowing behind the glass.",
    composition: "orbit",
    colours: [["#191C38", "indigo", 60], ["#ECEEFF", "frost white", 28], ["#8F5CFF", "violet orb", 12]],
  }),
  stylePalette("glassmorphism", {
    slug: "glassmorphism-twin-orbs",
    name: "Twin Orbs",
    mood: "Vivid, layered, dreamy",
    description: "Indigo, frost white, violet and rose: two coloured lights behind frosted panels. Fintech and creative dashboards.",
    composition: "orbit",
    colours: [["#1B1F3B", "deep indigo", 48], ["#E9ECFF", "frost white", 26], ["#8F5CFF", "violet orb", 14], ["#FF6AA2", "rose orb", 12]],
  }),
  stylePalette("glassmorphism", {
    slug: "glassmorphism-daylight",
    name: "Daylight Glass",
    mood: "Bright, clean, fresh",
    description: "Pale sky ground, deep navy text, a peach orb and a mint orb. Light-mode glass for consumer apps.",
    composition: "orbit",
    colours: [["#E7EEFB", "pale sky", 48], ["#1A2345", "deep navy", 26], ["#FFB08A", "peach orb", 14], ["#7FE0C8", "mint orb", 12]],
  }),

  // ——— Neubrutalism ———
  stylePalette("neubrutalism", {
    slug: "neubrutalism-outline",
    name: "Outline",
    mood: "Blunt, honest, graphic",
    description: "Paper cream and thick outline black. The skeleton every neubrutalist UI starts from.",
    composition: "window",
    colours: [["#FFF4DA", "paper cream", 66], ["#111111", "outline black", 34]],
  }),
  stylePalette("neubrutalism", {
    slug: "neubrutalism-punch",
    name: "Punch",
    mood: "Loud, playful, direct",
    description: "Cream, black outlines and a punch-red button with a hard shadow. For indie products and portfolios.",
    composition: "steps",
    colours: [["#FFF2D4", "paper cream", 58], ["#111111", "outline black", 30], ["#FF5C5C", "punch red", 12]],
  }),
  stylePalette("neubrutalism", {
    slug: "neubrutalism-sticker-ui",
    name: "Sticker UI",
    mood: "Fun, chunky, confident",
    description: "Cream, black, pop cyan and a sun yellow. Flat blocks with hard outlines, for SaaS that wants personality.",
    composition: "window",
    colours: [["#FFF4DA", "paper cream", 44], ["#111111", "outline black", 28], ["#4DD4FF", "pop cyan", 16], ["#FFD23F", "sun yellow", 12]],
  }),
  stylePalette("neubrutalism", {
    slug: "neubrutalism-grape-soda",
    name: "Grape Soda",
    mood: "Bold, sweet, cheeky",
    description: "Lavender ground, black outlines, a grape purple block and a lime highlight. A cooler neubrutalist set.",
    composition: "steps",
    colours: [["#E4DBFF", "lavender", 46], ["#121212", "outline black", 28], ["#7B4DFF", "grape", 16], ["#C6F432", "lime", 10]],
  }),

  // ——— Cyberpop ———
  stylePalette("cyberpop", {
    slug: "cyberpop-hologram",
    name: "Hologram",
    mood: "Bright, techy, playful",
    description: "Screen white with a deep violet type colour. Cyberpop’s brightness with a legible base.",
    composition: "orbit",
    colours: [["#F6F0FF", "screen white", 68], ["#3A1C8C", "deep violet", 32]],
  }),
  stylePalette("cyberpop", {
    slug: "cyberpop-pink-signal",
    name: "Pink Signal",
    mood: "Hyper, sweet, digital",
    description: "Screen white, cyber pink deepened for type and a lime flash. Loud and clean for apps and launches.",
    composition: "stripes",
    colours: [["#F7F2FF", "screen white", 60], ["#D4147F", "cyber pink", 28], ["#C6FF3D", "lime flash", 12]],
  }),
  stylePalette("cyberpop", {
    slug: "cyberpop-arcade",
    name: "Arcade",
    mood: "Energetic, glossy, futuristic",
    description: "Screen white, ink violet, cyber pink and hologram cyan. Full cyberpop with a dark ink to hold it together.",
    composition: "orbit",
    colours: [["#F6F0FF", "screen white", 44], ["#24124F", "ink violet", 28], ["#FF3CAC", "cyber pink", 16], ["#2BD2FF", "hologram cyan", 12]],
  }),
  stylePalette("cyberpop", {
    slug: "cyberpop-stream",
    name: "Livestream",
    mood: "Hyped, glowing, online",
    description: "Hologram cyan ground, deep navy type, cyber pink and lime. Bright and saturated for creators and games.",
    composition: "stripes",
    colours: [["#8AE6FF", "hologram cyan", 46], ["#10183F", "deep navy", 28], ["#FF3CAC", "cyber pink", 16], ["#C6FF3D", "lime", 10]],
  }),

  // ——— Chromecore ———
  stylePalette("chromecore", {
    slug: "chromecore-mirror",
    name: "Mirror",
    mood: "Sleek, reflective, cold",
    description: "Void black and a mirror highlight. Chrome as pure contrast.",
    composition: "wave",
    colours: [["#0E0E10", "void black", 66], ["#E9ECEF", "mirror highlight", 34]],
  }),
  stylePalette("chromecore", {
    slug: "chromecore-sky-reflection",
    name: "Sky Reflection",
    mood: "Liquid, futuristic, luxe",
    description: "Black, chrome-white type and a reflected sky blue. The colour chrome picks up from its surroundings.",
    composition: "wave",
    colours: [["#0F1012", "void black", 60], ["#E3E6E9", "chrome white", 28], ["#5AB3FF", "reflected sky", 12]],
  }),
  stylePalette("chromecore", {
    slug: "chromecore-liquid-metal",
    name: "Liquid Metal",
    mood: "Polished, sculptural, premium",
    description: "Black, mirror white, chrome mid-grey and sky blue. The full gradient of a chrome surface, flattened into four steps.",
    composition: "wave",
    colours: [["#0E0E10", "void black", 46], ["#E9ECEF", "mirror white", 26], ["#8B929A", "chrome mid", 18], ["#5AB3FF", "reflected sky", 10]],
  }),
  stylePalette("chromecore", {
    slug: "chromecore-daylight-chrome",
    name: "Daylight Chrome",
    mood: "Bright, metallic, Y2K",
    description: "Pale silver, gunmetal type, a chrome shadow and a warm peach reflection. Chrome in daylight for fashion and beauty.",
    composition: "orbit",
    colours: [["#E2E5E8", "pale silver", 48], ["#25282D", "gunmetal", 26], ["#9AA1A9", "chrome shadow", 16], ["#F5B49A", "peach reflection", 10]],
  }),

  // ——— Cyberpunk ———
  stylePalette("cyberpunk", {
    slug: "cyberpunk-neon-cyan",
    name: "Neon Cyan",
    mood: "Electric, nocturnal, urban",
    description: "Night black with neon cyan signage. Cyberpunk at its cleanest.",
    composition: "stripes",
    colours: [["#07090F", "night black", 70], ["#00F0FF", "neon cyan", 30]],
  }),
  stylePalette("cyberpunk", {
    slug: "cyberpunk-night-city",
    name: "Night City",
    mood: "Dense, dangerous, neon",
    description: "Night black, magenta signage and a sodium-amber streetlight. Hot and warm light on a cold city.",
    composition: "stripes",
    colours: [["#080A12", "night black", 60], ["#FF2E95", "neon magenta", 28], ["#FFB000", "sodium amber", 12]],
  }),
  stylePalette("cyberpunk", {
    slug: "cyberpunk-rain",
    name: "Neon Rain",
    mood: "Moody, cinematic, wet",
    description: "Night black, pale rain-grey text, cyan and magenta. Full cyberpunk with a readable text colour.",
    composition: "window",
    colours: [["#07090F", "night black", 48], ["#D8DEE6", "rain grey", 26], ["#00F0FF", "neon cyan", 14], ["#FF1F8E", "neon magenta", 12]],
  }),
  stylePalette("cyberpunk", {
    slug: "cyberpunk-corpo",
    name: "Corpo",
    mood: "Cold, clinical, corporate",
    description: "Steel blue-grey, black text, a sodium yellow warning and a red alert. Megacorp interfaces and HUDs.",
    composition: "window",
    colours: [["#C9D1D9", "steel grey", 46], ["#0B0E14", "black", 28], ["#FFC21A", "sodium yellow", 16], ["#E8253D", "red alert", 10]],
  }),

  // ——— Cyberminimalism ———
  stylePalette("cyberminimalism", {
    slug: "cyberminimalism-cold-white",
    name: "Cold White",
    mood: "Clinical, sparse, precise",
    description: "Cold white and carbon black. Interface minimalism with a sci-fi chill.",
    composition: "split",
    colours: [["#E6E8EA", "cold white", 70], ["#0C0D0F", "carbon black", 30]],
  }),
  stylePalette("cyberminimalism", {
    slug: "cyberminimalism-ice-line",
    name: "Ice Line",
    mood: "Sharp, quiet, futuristic",
    description: "Carbon black, cold white type and one ice-cyan line. A single accent for focus states and data.",
    composition: "steps",
    colours: [["#0C0D0F", "carbon black", 62], ["#E6E8EA", "cold white", 28], ["#7CF7FF", "ice cyan", 10]],
  }),
  stylePalette("cyberminimalism", {
    slug: "cyberminimalism-console",
    name: "Console",
    mood: "Focused, dark, technical",
    description: "Carbon, cold white, graphite panels and ice cyan. A complete dark UI for dev tools and AI products.",
    composition: "window",
    colours: [["#0E0F12", "carbon", 48], ["#E2E5E8", "cold white", 26], ["#2C3036", "graphite panel", 16], ["#7CF7FF", "ice cyan", 10]],
  }),
  stylePalette("cyberminimalism", {
    slug: "cyberminimalism-lab",
    name: "Clean Lab",
    mood: "Bright, sterile, exact",
    description: "Cold white, carbon type, pale graphite and a signal violet. Light-mode cyberminimal for health and science tech.",
    composition: "fields",
    colours: [["#EEF0F2", "cold white", 48], ["#121418", "carbon", 28], ["#C3C8CE", "pale graphite", 14], ["#6A5CFF", "signal violet", 10]],
  }),

  // ——— Glitch ———
  stylePalette("glitch", {
    slug: "glitch-blown-white",
    name: "Blown Out",
    mood: "Harsh, broken, stark",
    description: "Dead-pixel black and blown white. The signal before the colour splits.",
    composition: "stripes",
    colours: [["#0B0B0D", "dead-pixel black", 66], ["#F2F2F2", "blown white", 34]],
  }),
  stylePalette("glitch", {
    slug: "glitch-rgb-split",
    name: "RGB Split",
    mood: "Unstable, electric, digital",
    description: "Black ground, cyan channel and a red channel offset. The two channels as complementary accents.",
    composition: "stripes",
    colours: [["#0B0B0D", "dead-pixel black", 60], ["#00FFD1", "cyan channel", 28], ["#FF0040", "red channel", 12]],
  }),
  stylePalette("glitch", {
    slug: "glitch-datamosh",
    name: "Datamosh",
    mood: "Chaotic, saturated, corrupted",
    description: "Black, white, magenta and green channels. Corrupted video for music, games and art.",
    composition: "split",
    colours: [["#0D0D10", "black", 46], ["#F0F0F0", "blown white", 26], ["#FF2BD6", "magenta channel", 16], ["#39FF6A", "green channel", 12]],
  }),
  stylePalette("glitch", {
    slug: "glitch-crt-light",
    name: "CRT Light",
    mood: "Bright, jittery, retro",
    description: "Pale scanline grey, black text, a red channel and a blue channel. A light-mode glitch for editorial and fashion.",
    composition: "stripes",
    colours: [["#E4E4E2", "scanline grey", 48], ["#0E0E10", "black", 26], ["#FF1744", "red channel", 14], ["#2E5BFF", "blue channel", 12]],
  }),

  // ——— Pixel Art ———
  stylePalette("pixel-art", {
    slug: "pixel-art-gameboy",
    name: "Handheld",
    mood: "Nostalgic, simple, cosy",
    description: "Pale handheld green and its darkest green. Two of the four shades from the original pocket console.",
    composition: "window",
    colours: [["#C4D69A", "pale screen green", 68], ["#1F3A26", "dark pixel green", 32]],
  }),
  stylePalette("pixel-art", {
    slug: "pixel-art-night-level",
    name: "Night Level",
    mood: "Adventurous, cosy, retro",
    description: "Night-sprite navy, sand text and a grass-green power-up. Indie-game warmth for game and dev sites.",
    composition: "steps",
    colours: [["#1A1C2C", "night sprite", 60], ["#FFCD75", "sand", 28], ["#38B764", "grass green", 12]],
  }),
  stylePalette("pixel-art", {
    slug: "pixel-art-overworld",
    name: "Overworld",
    mood: "Bright, playful, heroic",
    description: "Pixel sky, night-sprite navy outlines, grass green and a sand path. A limited game palette for landing pages.",
    composition: "steps",
    colours: [["#9AD4FF", "pixel sky", 44], ["#1A1C2C", "sprite navy", 28], ["#38B764", "grass green", 16], ["#FFCD75", "sand path", 12]],
  }),
  stylePalette("pixel-art", {
    slug: "pixel-art-dungeon",
    name: "Dungeon",
    mood: "Dark, mysterious, warm",
    description: "Dungeon purple-black, torch gold text, a stone grey and a potion red. Fantasy RPG mood for games and Discord.",
    composition: "window",
    colours: [["#1E1526", "dungeon black", 50], ["#F4C15A", "torch gold", 24], ["#5D5A6E", "stone grey", 16], ["#D63C4F", "potion red", 10]],
  }),

  // ——— Aurora ———
  stylePalette("aurora", {
    slug: "aurora-polar-green",
    name: "Polar Green",
    mood: "Luminous, serene, natural",
    description: "Polar night and aurora green. The glow in its simplest form.",
    composition: "wave",
    colours: [["#060B1A", "polar night", 70], ["#3CFFB0", "aurora green", 30]],
  }),
  stylePalette("aurora", {
    slug: "aurora-veil",
    name: "Violet Veil",
    mood: "Mystical, calm, glowing",
    description: "Polar night, pale ice text and a violet veil. Quiet enough for meditation and sleep apps.",
    composition: "wave",
    colours: [["#070C1C", "polar night", 60], ["#DDE8F4", "pale ice", 28], ["#8A6CFF", "violet veil", 12]],
  }),
  stylePalette("aurora", {
    slug: "aurora-borealis",
    name: "Borealis",
    mood: "Awe-struck, vivid, cosmic",
    description: "Polar night, aurora green, deep-sky blue and violet. Full aurora gradients reduced to four flat steps.",
    composition: "wave",
    colours: [["#060B1A", "polar night", 48], ["#3CFFB0", "aurora green", 24], ["#2F80FF", "deep-sky blue", 16], ["#7A5CFF", "violet veil", 12]],
  }),
  stylePalette("aurora", {
    slug: "aurora-dawn-ice",
    name: "Dawn Ice",
    mood: "Fresh, soft, hopeful",
    description: "Pale glacier, deep night-blue text, a soft aurora green and a dawn pink. A light aurora for wellness and climate.",
    composition: "wave",
    colours: [["#E5EEF5", "pale glacier", 48], ["#0F1A35", "night blue", 26], ["#7EE6BE", "soft aurora", 16], ["#F2A7C3", "dawn pink", 10]],
  }),

  // ——— Surveillance ———
  stylePalette("surveillance", {
    slug: "surveillance-monitor",
    name: "Monitor",
    mood: "Cold, watchful, flat",
    description: "Monitor dark and washed grey. The feed without the drama.",
    composition: "window",
    colours: [["#1C221E", "monitor dark", 68], ["#C7CCC6", "washed grey", 32]],
  }),
  stylePalette("surveillance", {
    slug: "surveillance-rec",
    name: "REC",
    mood: "Tense, documentary, alert",
    description: "Monitor dark, night-vision green text and a red recording dot. One red mark, used sparingly.",
    composition: "window",
    colours: [["#1B201C", "monitor dark", 62], ["#9DB5A1", "night-vision green", 28], ["#E94B3C", "record red", 10]],
  }),
  stylePalette("surveillance", {
    slug: "surveillance-cctv",
    name: "CCTV",
    mood: "Grainy, clinical, uneasy",
    description: "Washed grey, black timestamp text, a green-grey and the record dot. A light surveillance look for editorial.",
    composition: "fields",
    colours: [["#C9CEC8", "washed grey", 48], ["#141814", "timestamp black", 28], ["#7F9A84", "green-grey", 16], ["#E04234", "record red", 8]],
  }),
  stylePalette("surveillance", {
    slug: "surveillance-thermal",
    name: "Thermal",
    mood: "Clinical, hot, unsettling",
    description: "Deep thermal blue, white readout, a heat orange and a hotspot yellow. Thermal imaging for tech and investigative work.",
    composition: "orbit",
    colours: [["#121A3A", "thermal blue", 50], ["#E8ECEE", "readout white", 26], ["#F2602A", "heat orange", 14], ["#FFE14A", "hotspot yellow", 10]],
  }),

  // ——— Futuristic ———
  stylePalette("futuristic", {
    slug: "futuristic-ceramic",
    name: "Ceramic",
    mood: "Pristine, calm, advanced",
    description: "Ceramic white and deep space blue. Clean, sci-fi and readable.",
    composition: "arch",
    colours: [["#F3F5F7", "ceramic white", 70], ["#1E2A38", "deep space", 30]],
  }),
  stylePalette("futuristic", {
    slug: "futuristic-light-panel",
    name: "Light Panel",
    mood: "Glowing, sleek, orbital",
    description: "Deep space ground, ceramic white text and a light-panel blue. Spacecraft interiors for tech launches.",
    composition: "window",
    colours: [["#1A2431", "deep space", 60], ["#EEF1F4", "ceramic white", 28], ["#4FC3F7", "light-panel blue", 12]],
  }),
  stylePalette("futuristic", {
    slug: "futuristic-station",
    name: "Station",
    mood: "Engineered, optimistic, clean",
    description: "Ceramic white, deep space text, titanium and light-panel blue. A complete product palette for hardware and mobility.",
    composition: "arch",
    colours: [["#F3F5F7", "ceramic white", 46], ["#1E2A38", "deep space", 28], ["#9AA4AE", "titanium", 16], ["#3DB5EE", "light-panel blue", 10]],
  }),
  stylePalette("futuristic", {
    slug: "futuristic-mission",
    name: "Mission Control",
    mood: "Focused, heroic, technical",
    description: "Titanium ground, near-black text, a deep space panel and a mission orange. Aerospace with one warm signal colour.",
    composition: "steps",
    colours: [["#C9CFD5", "titanium", 46], ["#11161D", "near black", 28], ["#2B3A4D", "space panel", 16], ["#FF7A2F", "mission orange", 10]],
  }),
];
