import type { PaletteRecord } from "../types";
import { stylePalette } from "./define";

/** Palettes made for the movement styles (src/content/styles/movements.ts), four per style. */
export const movementPalettes: PaletteRecord[] = [
  // ——— Swiss ———
  stylePalette("swiss", {
    slug: "swiss-grid-red",
    name: "Grid Red",
    mood: "Precise, loud, rational",
    description: "Off-white page with a single signal vermilion. The classic Swiss poster pairing, sharp enough for headlines and nav.",
    composition: "split",
    colours: [["#F2F0EB", "offset white", 72], ["#D52B1E", "signal vermilion", 28]],
  }),
  stylePalette("swiss", {
    slug: "swiss-zurich-blue",
    name: "Zürich Blue",
    mood: "Cool, ordered, civic",
    description: "Cool paper, black type and a clean transit blue. Reads like a timetable; works for dashboards and wayfinding.",
    composition: "window",
    colours: [["#EEF0F0", "cool paper", 62], ["#141414", "type black", 28], ["#1E5AA8", "transit blue", 10]],
  }),
  stylePalette("swiss", {
    slug: "swiss-kunsthalle",
    name: "Kunsthalle",
    mood: "Bold, graphic, cultural",
    description: "Black ground, white type, a red field and a lemon highlight. An exhibition-poster system for event and gallery sites.",
    composition: "steps",
    colours: [["#121212", "press black", 52], ["#F4F2EC", "poster white", 28], ["#E2231A", "Swiss red", 12], ["#F5D10F", "lemon", 8]],
  }),
  stylePalette("swiss", {
    slug: "swiss-helvetica-grey",
    name: "Helvetica Grey",
    mood: "Quiet, neutral, exact",
    description: "Pale concrete grey, graphite type and warm white panels, with one small red mark. Restrained enough for long reading.",
    composition: "fields",
    colours: [["#D9D8D3", "pale concrete", 48], ["#232323", "graphite", 30], ["#F7F6F2", "warm white", 14], ["#CC2B1D", "marker red", 8]],
  }),

  // ——— Bauhaus ———
  stylePalette("bauhaus", {
    slug: "bauhaus-dessau-blue",
    name: "Dessau Blue",
    mood: "Solid, primary, workmanlike",
    description: "Ultramarine on unbleached cream: one Bauhaus primary carrying all the weight. Strong for logos and section headers.",
    composition: "orbit",
    colours: [["#EFE7D4", "unbleached cream", 68], ["#1F3E94", "ultramarine", 32]],
  }),
  stylePalette("bauhaus", {
    slug: "bauhaus-weimar-red",
    name: "Weimar Red",
    mood: "Warm, geometric, assertive",
    description: "Cream ground, cadmium red shapes and a black bar. Red leads; black anchors type and rules.",
    composition: "split",
    colours: [["#ECE3CF", "workshop cream", 58], ["#C9271A", "cadmium red", 30], ["#161616", "lamp black", 12]],
  }),
  stylePalette("bauhaus", {
    slug: "bauhaus-triad",
    name: "Workshop Triad",
    mood: "Playful, balanced, didactic",
    description: "Red, yellow and blue on cream, weighted so blue leads and yellow only accents. A disciplined take on the primary triad for education and kids’ brands.",
    composition: "orbit",
    colours: [["#F0E8D5", "cream board", 45], ["#22409A", "primary blue", 28], ["#D3301F", "primary red", 17], ["#F1B417", "primary yellow", 10]],
  }),
  stylePalette("bauhaus", {
    slug: "bauhaus-night-school",
    name: "Night School",
    mood: "Dark, structural, modern",
    description: "Charcoal ground with cream type, mustard and a red dot. The triad moved onto dark mode without losing its weight.",
    composition: "steps",
    colours: [["#1C1C1E", "charcoal", 54], ["#EEE5D0", "cream", 26], ["#E0A419", "mustard", 12], ["#CF2E1F", "red dot", 8]],
  }),

  // ——— Constructivism ———
  stylePalette("constructivism", {
    slug: "constructivism-agitprop",
    name: "Agitprop",
    mood: "Urgent, militant, direct",
    description: "Revolutionary red on aged newsprint: one ink, maximum volume. For campaigns, protest posters and bold CTAs.",
    composition: "split",
    colours: [["#E9DFC9", "aged newsprint", 64], ["#C21F1C", "banner red", 36]],
  }),
  stylePalette("constructivism", {
    slug: "constructivism-red-wedge",
    name: "Red Wedge",
    mood: "Dynamic, diagonal, forceful",
    description: "Black ground, newsprint type and a single red wedge. High drama for hero sections and headline-led layouts.",
    composition: "steps",
    colours: [["#181716", "press black", 60], ["#E6DCC5", "newsprint", 28], ["#D0261E", "wedge red", 12]],
  }),
  stylePalette("constructivism", {
    slug: "constructivism-factory-floor",
    name: "Factory Floor",
    mood: "Industrial, worn, collective",
    description: "Warm grey card with black type, red and a dull ochre, like a faded factory bulletin. Lets red lead without shouting.",
    composition: "stripes",
    colours: [["#D3CABA", "card grey", 46], ["#1B1A18", "stencil black", 28], ["#B8261F", "oxide red", 16], ["#C99A3C", "ochre", 10]],
  }),
  stylePalette("constructivism", {
    slug: "constructivism-rodchenko",
    name: "Rodchenko",
    mood: "Graphic, photomontage, sharp",
    description: "Newsprint, black, red and a cold steel blue for photo tints. The blue gives montage images somewhere to sit.",
    composition: "split",
    colours: [["#EDE4D0", "newsprint", 44], ["#151515", "black", 30], ["#CC2A1F", "Rodchenko red", 16], ["#4A6578", "steel blue", 10]],
  }),

  // ——— Art Deco ———
  stylePalette("art-deco", {
    slug: "art-deco-gilt-night",
    name: "Gilt Night",
    mood: "Opulent, nocturnal, geometric",
    description: "Lacquer black and champagne gold. The essential Deco pairing for luxury landing pages, menus and invitations.",
    composition: "arch",
    colours: [["#14110F", "lacquer black", 72], ["#D4B26A", "champagne gold", 28]],
  }),
  stylePalette("art-deco", {
    slug: "art-deco-chrysler",
    name: "Chrysler",
    mood: "Soaring, metallic, urban",
    description: "Midnight navy, silver-white type and brass trim, from skyscraper lobbies. Cooler than gold-on-black, still unmistakably Deco.",
    composition: "steps",
    colours: [["#16203A", "midnight navy", 60], ["#E7E4DC", "platinum white", 28], ["#C49A4A", "brass", 12]],
  }),
  stylePalette("art-deco", {
    slug: "art-deco-lido",
    name: "Lido",
    mood: "Sunny, sleek, coastal",
    description: "Ivory, deep teal, coral and gold: a seaside-hotel Deco for hospitality and travel brands.",
    composition: "arch",
    colours: [["#F1E8D6", "ivory stucco", 46], ["#1D4F55", "deep teal", 28], ["#E07A5F", "coral", 16], ["#C8A050", "gold leaf", 10]],
  }),
  stylePalette("art-deco", {
    slug: "art-deco-oxblood-salon",
    name: "Oxblood Salon",
    mood: "Rich, intimate, theatrical",
    description: "Oxblood lacquer with ivory type, black inlay and gold. A warmer evening palette for bars, theatres and fashion.",
    composition: "window",
    colours: [["#4A1518", "oxblood lacquer", 50], ["#EFE5D0", "ivory", 26], ["#121010", "ebony inlay", 14], ["#CFA75A", "gold", 10]],
  }),

  // ——— Art Nouveau ———
  stylePalette("art-nouveau", {
    slug: "art-nouveau-vellum-moss",
    name: "Vellum & Moss",
    mood: "Organic, calm, botanical",
    description: "Warm vellum with a deep moss green for line and type. A soft two-colour system for wellness and garden brands.",
    composition: "wave",
    colours: [["#EFE3C6", "vellum", 70], ["#3E5236", "moss", 30]],
  }),
  stylePalette("art-nouveau", {
    slug: "art-nouveau-mucha",
    name: "Mucha",
    mood: "Graceful, warm, decorative",
    description: "Parchment, madder brown line and a gold halo, after the great poster lithographs. Elegant for beauty, tea and wine.",
    composition: "arch",
    colours: [["#F0E2C3", "parchment", 58], ["#6E3426", "madder brown", 30], ["#C6973F", "halo gold", 12]],
  }),
  stylePalette("art-nouveau", {
    slug: "art-nouveau-peacock",
    name: "Peacock",
    mood: "Lush, jewelled, ornate",
    description: "Peacock teal ground with cream line, verdigris and a touch of gold. Rich enough for florists, perfumers and boutique hotels.",
    composition: "wave",
    colours: [["#1E4A4A", "peacock teal", 50], ["#EDE0C2", "cream line", 26], ["#6F9A84", "verdigris", 14], ["#C79B45", "gold", 10]],
  }),
  stylePalette("art-nouveau", {
    slug: "art-nouveau-iris",
    name: "Iris",
    mood: "Romantic, floral, soft",
    description: "Pale sage paper, iris violet, ochre stems and a dusty rose. A gentle palette for stationery, weddings and editorial.",
    composition: "orbit",
    colours: [["#E5E3CF", "pale sage paper", 46], ["#4E3F6E", "iris violet", 28], ["#B58A3E", "ochre stem", 16], ["#C98A86", "dusty rose", 10]],
  }),

  // ——— Modernism ———
  stylePalette("modernism", {
    slug: "modernism-cobalt-field",
    name: "Cobalt Field",
    mood: "Clear, confident, abstract",
    description: "Gallery white and a single cobalt. One primary is enough for a modern, museum-like site.",
    composition: "fields",
    colours: [["#F4F3EF", "gallery white", 70], ["#23479A", "cobalt", 30]],
  }),
  stylePalette("modernism", {
    slug: "modernism-mondrian",
    name: "De Stijl",
    mood: "Balanced, structured, primary",
    description: "White fields, black grid lines and a red block, weighted as in a Mondrian. Clean for portfolios and architecture.",
    composition: "window",
    colours: [["#F3F2EE", "white field", 62], ["#161616", "grid black", 26], ["#C6281F", "red block", 12]],
  }),
  stylePalette("modernism", {
    slug: "modernism-le-corbusier",
    name: "Polychromie",
    mood: "Architectural, warm, considered",
    description: "Limewash, deep umber, burnt sienna and a pale cerulean, after Le Corbusier’s architectural colours. Calm and grown-up for studios and furniture.",
    composition: "fields",
    colours: [["#EDE8DD", "limewash", 46], ["#3B2F28", "umber", 28], ["#B25A35", "burnt sienna", 16], ["#8FB3C6", "pale cerulean", 10]],
  }),
  stylePalette("modernism", {
    slug: "modernism-night-gallery",
    name: "Night Gallery",
    mood: "Serious, focused, modern",
    description: "Near-black ground, white type, cobalt and a yellow marker. A dark-mode modernism for creative tools and galleries.",
    composition: "steps",
    colours: [["#161718", "gallery black", 54], ["#F2F1ED", "white", 26], ["#3157B5", "cobalt", 12], ["#F0C230", "marker yellow", 8]],
  }),

  // ——— Minimalism ———
  stylePalette("minimalism", {
    slug: "minimalism-bone-graphite",
    name: "Bone & Graphite",
    mood: "Calm, essential, quiet",
    description: "Warm bone and soft graphite: almost no colour, all contrast. For portfolios, product pages and reading.",
    composition: "fields",
    colours: [["#EEEAE3", "bone", 74], ["#2E2D2B", "graphite", 26]],
  }),
  stylePalette("minimalism", {
    slug: "minimalism-sage-room",
    name: "Sage Room",
    mood: "Serene, natural, restrained",
    description: "Chalk white, charcoal type and a muted sage accent. A hint of colour without breaking the calm.",
    composition: "window",
    colours: [["#F1EFEA", "chalk", 64], ["#2B2C2A", "charcoal", 28], ["#9AA58D", "muted sage", 8]],
  }),
  stylePalette("minimalism", {
    slug: "minimalism-oat",
    name: "Oat",
    mood: "Soft, warm, tactile",
    description: "Oat, taupe panels, espresso type and a clay accent. A warm neutral system for lifestyle and interiors brands.",
    composition: "fields",
    colours: [["#E9E2D6", "oat", 48], ["#3A302A", "espresso", 26], ["#C9BCAA", "taupe panel", 16], ["#B07A5A", "clay", 10]],
  }),
  stylePalette("minimalism", {
    slug: "minimalism-fog",
    name: "Fog",
    mood: "Cool, airy, precise",
    description: "Cool fog grey, ink-blue type, a pale stone panel and a slate-blue link colour. Quiet tech and studio sites.",
    composition: "split",
    colours: [["#E6E8E8", "fog", 48], ["#1E2630", "ink blue", 28], ["#CDD1D1", "stone", 14], ["#55708A", "slate blue", 10]],
  }),

  // ——— Brutalism ———
  stylePalette("brutalism", {
    slug: "brutalism-poured",
    name: "Poured",
    mood: "Heavy, honest, monumental",
    description: "Raw concrete and its own deep shadow. Two greys, big contrast, nothing decorative.",
    composition: "steps",
    colours: [["#B1ADA4", "raw concrete", 66], ["#2C2B29", "deep recess", 34]],
  }),
  stylePalette("brutalism", {
    slug: "brutalism-barbican",
    name: "Barbican",
    mood: "Civic, robust, green-softened",
    description: "Pale concrete, charcoal and a moss green from planted terraces. Brutalism with a living accent.",
    composition: "window",
    colours: [["#CFCBC2", "pale concrete", 58], ["#2A2927", "charcoal", 30], ["#56684A", "terrace moss", 12]],
  }),
  stylePalette("brutalism", {
    slug: "brutalism-safety",
    name: "Site Safety",
    mood: "Raw, functional, alert",
    description: "Concrete greys with a hazard orange, like signage on a building site. Strong for tools, events and bold UI.",
    composition: "stripes",
    colours: [["#A9A59C", "concrete", 46], ["#1F1E1C", "tar black", 28], ["#6A6761", "formwork grey", 16], ["#E8641B", "hazard orange", 10]],
  }),
  stylePalette("brutalism", {
    slug: "brutalism-overcast-dusk",
    name: "Overcast Dusk",
    mood: "Moody, cold, cinematic",
    description: "Dusk blue-grey, pale sky type, concrete mid-tone and one sodium-lamp amber. Atmospheric for film and architecture.",
    composition: "steps",
    colours: [["#2E3238", "dusk grey", 50], ["#D7D6D0", "pale sky", 26], ["#7D7B76", "wet concrete", 14], ["#E3A23B", "sodium amber", 10]],
  }),

  // ——— Mid-Century Modern ———
  stylePalette("mid-century-modern", {
    slug: "mid-century-modern-teak-cream",
    name: "Teak & Cream",
    mood: "Warm, crafted, relaxed",
    description: "Warm cream with teak brown. The furniture-catalogue pairing for interiors, coffee and lifestyle brands.",
    composition: "arch",
    colours: [["#F2E7D2", "cream", 68], ["#7E4527", "teak", 32]],
  }),
  stylePalette("mid-century-modern", {
    slug: "mid-century-modern-atomic",
    name: "Atomic",
    mood: "Optimistic, playful, space-age",
    description: "Warm paper, deep teal and a starburst orange. Cheerful for food, music and kids’ products.",
    composition: "orbit",
    colours: [["#F3EAD7", "warm paper", 58], ["#1C5F5B", "deep teal", 30], ["#E86A2C", "starburst orange", 12]],
  }),
  stylePalette("mid-century-modern", {
    slug: "mid-century-modern-eames",
    name: "Lounge",
    mood: "Sophisticated, warm, iconic",
    description: "Off-white, walnut, mustard and a slate blue, after mid-century furniture and textiles. Balanced warm and cool.",
    composition: "fields",
    colours: [["#EFE6D4", "off-white", 44], ["#4B3226", "walnut", 28], ["#D49A2A", "mustard", 16], ["#557A8C", "slate blue", 12]],
  }),
  stylePalette("mid-century-modern", {
    slug: "mid-century-modern-palm-springs",
    name: "Palm Springs",
    mood: "Sunny, breezy, retro",
    description: "Pale sand, deep olive, flamingo pink and turquoise: desert-modernist houses and pools. Great for travel and summer campaigns.",
    composition: "wave",
    colours: [["#F1E6CF", "pale sand", 46], ["#3F4A2C", "deep olive", 26], ["#E98B87", "flamingo pink", 16], ["#3FA9A5", "pool turquoise", 12]],
  }),

  // ——— Post-Modernism ———
  stylePalette("post-modernism", {
    slug: "post-modernism-ultramarine-sand",
    name: "Ultramarine Sand",
    mood: "Witty, bold, architectural",
    description: "Sand ground and an ultramarine that does all the talking. A bold two-colour postmodern system.",
    composition: "arch",
    colours: [["#EBD9B0", "sand", 68], ["#2F3F8F", "ultramarine", 32]],
  }),
  stylePalette("post-modernism", {
    slug: "post-modernism-piazza",
    name: "Piazza",
    mood: "Theatrical, classical, ironic",
    description: "Salmon stucco, deep terracotta type and a mint column. Classical forms made into a joke you can read.",
    composition: "arch",
    colours: [["#F1D3C6", "salmon stucco", 60], ["#7A3524", "terracotta", 28], ["#8CC4B6", "mint column", 12]],
  }),
  stylePalette("post-modernism", {
    slug: "post-modernism-sottsass",
    name: "Sottsass",
    mood: "Irreverent, pattern-led, loud",
    description: "Cream, ultramarine, mint and a sunflower yellow in blocky zones. For creative agencies and playful brands.",
    composition: "steps",
    colours: [["#F4ECDC", "cream", 42], ["#343F8C", "ultramarine", 28], ["#9CCBC0", "mint", 18], ["#EDBA3A", "sunflower", 12]],
  }),
  stylePalette("post-modernism", {
    slug: "post-modernism-terrazzo",
    name: "Terrazzo",
    mood: "Speckled, warm, decorative",
    description: "Pale terrazzo, ink navy, coral and sage chips. A softer postmodern palette for interiors and retail.",
    composition: "orbit",
    colours: [["#EEE6DB", "pale terrazzo", 46], ["#22294A", "ink navy", 26], ["#E58C73", "coral chip", 16], ["#9DB49A", "sage chip", 12]],
  }),

  // ——— Deconstructivism ———
  stylePalette("deconstructivism", {
    slug: "deconstructivism-carbon-cut",
    name: "Carbon Cut",
    mood: "Fractured, tense, severe",
    description: "Pale zinc and carbon black at full contrast. Leaves the shapes and angles to do the work.",
    composition: "steps",
    colours: [["#E4E2DD", "pale zinc", 66], ["#1C1F22", "carbon", 34]],
  }),
  stylePalette("deconstructivism", {
    slug: "deconstructivism-oxide-shard",
    name: "Oxide Shard",
    mood: "Sharp, raw, architectural",
    description: "Carbon ground, zinc type and one oxide-red cut through it. The single warm colour reads as the fracture.",
    composition: "split",
    colours: [["#1E2124", "carbon", 60], ["#DEDCD6", "zinc", 28], ["#C74A2F", "oxide red", 12]],
  }),
  stylePalette("deconstructivism", {
    slug: "deconstructivism-titanium",
    name: "Titanium",
    mood: "Metallic, sculptural, cool",
    description: "Brushed titanium, gunmetal, cold steel and a copper edge, after Gehry’s cladding. For architecture and premium tech.",
    composition: "wave",
    colours: [["#C9CBCB", "brushed titanium", 46], ["#2A2E33", "gunmetal", 28], ["#7F878F", "cold steel", 16], ["#B8683F", "copper edge", 10]],
  }),
  stylePalette("deconstructivism", {
    slug: "deconstructivism-blueprint-break",
    name: "Broken Plan",
    mood: "Analytical, unstable, technical",
    description: "Draughting white, deep blue line, grey construction lines and a red correction mark. Drawings pulled apart.",
    composition: "steps",
    colours: [["#EEEEEA", "draughting white", 50], ["#1E3354", "plan blue", 26], ["#9EA3A8", "construction grey", 14], ["#D4402B", "correction red", 10]],
  }),

  // ——— Pop Art ———
  stylePalette("pop-art", {
    slug: "pop-art-whaam",
    name: "Whaam",
    mood: "Explosive, comic, loud",
    description: "Comic yellow and outline black. The most legible pop pairing, for headlines, stickers and sales.",
    composition: "orbit",
    colours: [["#FFE04A", "comic yellow", 66], ["#121212", "outline black", 34]],
  }),
  stylePalette("pop-art", {
    slug: "pop-art-ben-day",
    name: "Ben-Day",
    mood: "Graphic, printed, cheerful",
    description: "Newsprint white, process blue and a tomato red dot. Flat comic colours that stay legible on screen.",
    composition: "orbit",
    colours: [["#F6F1E4", "newsprint white", 58], ["#1F5FBF", "process blue", 30], ["#E8262C", "tomato red", 12]],
  }),
  stylePalette("pop-art", {
    slug: "pop-art-soup-can",
    name: "Soup Can",
    mood: "Iconic, commercial, bold",
    description: "Can red and label white with black type and a gold medallion. Supermarket iconography for food and retail.",
    composition: "split",
    colours: [["#D7262B", "can red", 46], ["#F7F2E8", "label white", 30], ["#141414", "type black", 14], ["#D6A53A", "medallion gold", 10]],
  }),
  stylePalette("pop-art", {
    slug: "pop-art-silkscreen",
    name: "Silkscreen",
    mood: "Celebrity, saturated, offbeat",
    description: "Hot pink ground, black key line, turquoise and a lemon highlight, like mis-registered screen prints. For music and fashion.",
    composition: "fields",
    colours: [["#F2559A", "hot pink", 46], ["#151515", "key black", 26], ["#2BB7B3", "turquoise", 16], ["#F7E24A", "lemon", 12]],
  }),

  // ——— Memphis ———
  stylePalette("memphis", {
    slug: "memphis-squiggle",
    name: "Squiggle",
    mood: "Cheeky, simple, graphic",
    description: "Laminate white and a flamingo pink that reads as a statement colour. Light-hearted for apps and packaging.",
    composition: "wave",
    colours: [["#F8F1E2", "laminate white", 66], ["#E5336D", "flamingo pink", 34]],
  }),
  stylePalette("memphis", {
    slug: "memphis-terrazzo-pop",
    name: "Laminate",
    mood: "Bright, plastic, energetic",
    description: "White laminate, black squiggles and an aqua block. Black gives Memphis colour a readable spine.",
    composition: "stripes",
    colours: [["#F7F0E1", "white laminate", 58], ["#141414", "squiggle black", 30], ["#2EC4B6", "aqua", 12]],
  }),
  stylePalette("memphis", {
    slug: "memphis-milano",
    name: "Milano ’81",
    mood: "Exuberant, clashing, joyful",
    description: "Egg yellow, cobalt, flamingo and black: deliberate clashes, balanced by proportion. For festivals and youth brands.",
    composition: "orbit",
    colours: [["#FFD23F", "egg yellow", 44], ["#253C9E", "cobalt", 28], ["#FF5D8F", "flamingo", 16], ["#151515", "black", 12]],
  }),
  stylePalette("memphis", {
    slug: "memphis-pastel-lab",
    name: "Pastel Lab",
    mood: "Soft, quirky, friendly",
    description: "Lilac ground, navy type, mint and a coral confetti accent. Memphis turned down for wellness and kids’ apps.",
    composition: "orbit",
    colours: [["#E3DAF2", "lilac", 46], ["#1D2350", "navy", 28], ["#9EE0CC", "mint", 16], ["#FF7B6B", "coral", 10]],
  }),

  // ——— Baroque Tenebrism ———
  stylePalette("baroque-tenebrism", {
    slug: "baroque-tenebrism-candlelight",
    name: "Candlelight",
    mood: "Dramatic, intimate, warm",
    description: "Umber black and a single candle gold. Light emerging from darkness, for luxury, wine and theatre.",
    composition: "orbit",
    colours: [["#15110D", "umber black", 74], ["#D8A65A", "candle gold", 26]],
  }),
  stylePalette("baroque-tenebrism", {
    slug: "baroque-tenebrism-caravaggio",
    name: "Caravaggio",
    mood: "Stark, sacred, intense",
    description: "Deep shadow, flesh-light ivory and a madder red drape. The tenebrist trio, for editorial and fine dining.",
    composition: "window",
    colours: [["#17120E", "deep shadow", 62], ["#E6D2AE", "lit flesh", 26], ["#8C2A1F", "madder drape", 12]],
  }),
  stylePalette("baroque-tenebrism", {
    slug: "baroque-tenebrism-rembrandt",
    name: "Rembrandt",
    mood: "Rich, contemplative, golden",
    description: "Warm brown-black, ochre light, raw umber mid-tones and a deep crimson. Old-master warmth for heritage brands.",
    composition: "arch",
    colours: [["#1E1711", "brown-black", 50], ["#D9B06A", "ochre light", 26], ["#5E4A2E", "raw umber", 14], ["#7C1F22", "crimson", 10]],
  }),
  stylePalette("baroque-tenebrism", {
    slug: "baroque-tenebrism-velvet",
    name: "Velvet Chapel",
    mood: "Sumptuous, nocturnal, solemn",
    description: "Midnight olive, candlelit ivory, old gold and a velvet plum. A cooler chiaroscuro for fragrance and music.",
    composition: "arch",
    colours: [["#1A1C14", "midnight olive", 50], ["#E8DCC0", "candlelit ivory", 26], ["#B48A3E", "old gold", 14], ["#5A2340", "velvet plum", 10]],
  }),
];
