import type { PaletteRecord } from "../types";
import { stylePalette } from "./define";

/** Palettes made for the print styles (src/content/styles/print.ts), four per style. */
export const printPalettes: PaletteRecord[] = [
  // ——— Experimental Type ———
  stylePalette("experimental-type", {
    slug: "experimental-type-overprint-blue",
    name: "Overprint Blue",
    mood: "Electric, raw, typographic",
    description: "Stock white and an electric ultramarine that vibrates at headline size. One ink, set big.",
    composition: "stripes",
    colours: [["#EDEDE8", "stock white", 64], ["#2F4BF0", "electric blue", 36]],
  }),
  stylePalette("experimental-type", {
    slug: "experimental-type-signal-orange",
    name: "Hot Proof",
    mood: "Loud, urgent, experimental",
    description: "Black ground, white type and a hot orange overprint. Built for type-led posters, splash pages and type foundries.",
    composition: "split",
    colours: [["#121212", "ink black", 60], ["#EEEDE8", "proof white", 28], ["#FF4B1F", "hot orange", 12]],
  }),
  stylePalette("experimental-type", {
    slug: "experimental-type-two-pass",
    name: "Two Pass",
    mood: "Layered, vibrating, bold",
    description: "Off-white, black, blue and orange as two overprinted passes. Complementary inks for kinetic type systems.",
    composition: "steps",
    colours: [["#EFEEEA", "paper", 44], ["#131313", "ink", 28], ["#3A5BFF", "pass blue", 16], ["#FF5A1F", "pass orange", 12]],
  }),
  stylePalette("experimental-type", {
    slug: "experimental-type-acid-specimen",
    name: "Acid Specimen",
    mood: "Futurist, sharp, nocturnal",
    description: "Graphite ground, acid lime type, a lilac second ink and grey rules. A dark type-specimen look for creative tech.",
    composition: "stripes",
    colours: [["#1B1B1D", "graphite", 52], ["#D6F23A", "acid lime", 24], ["#B7A4F5", "lilac ink", 14], ["#6B6B70", "rule grey", 10]],
  }),

  // ——— 80s Editorial ———
  stylePalette("80s-editorial", {
    slug: "80s-editorial-magenta-cover",
    name: "Magenta Cover",
    mood: "Glossy, confident, fashionable",
    description: "Gloss white with a process magenta that reads like a cover line. For fashion, beauty and magazine sites.",
    composition: "split",
    colours: [["#F6F1E7", "gloss white", 66], ["#D8007A", "process magenta", 34]],
  }),
  stylePalette("80s-editorial", {
    slug: "80s-editorial-newsstand",
    name: "Newsstand",
    mood: "Punchy, graphic, flat",
    description: "Jet black ground, white cover lines and a cyan block. Flat process colour at its most direct.",
    composition: "fields",
    colours: [["#0D0D0D", "jet black", 58], ["#F4F0E6", "gloss white", 30], ["#00A6D6", "process cyan", 12]],
  }),
  stylePalette("80s-editorial", {
    slug: "80s-editorial-cmyk",
    name: "CMYK Spread",
    mood: "Bright, printed, energetic",
    description: "White, black, magenta and cyan in flat blocks, the process colours used as layout. For music, culture and youth editorial.",
    composition: "steps",
    colours: [["#F6F1E7", "gloss white", 44], ["#0B0B0B", "key black", 26], ["#E3007A", "magenta", 18], ["#00A6D6", "cyan", 12]],
  }),
  stylePalette("80s-editorial", {
    slug: "80s-editorial-power-suit",
    name: "Power Suit",
    mood: "Slick, corporate, retro",
    description: "Pale grey, navy type, a teal block and a coral accent: the business pages of the decade. Retro without neon.",
    composition: "window",
    colours: [["#E4E3E0", "office grey", 46], ["#1C2647", "navy", 28], ["#2A8C8C", "teal", 16], ["#F06A5B", "coral", 10]],
  }),

  // ——— Editorial ———
  stylePalette("editorial", {
    slug: "editorial-uncoated",
    name: "Uncoated",
    mood: "Literate, calm, serious",
    description: "Uncoated off-white and soft black. The long-read standard: quiet, legible and timeless.",
    composition: "fields",
    colours: [["#F3F0EA", "uncoated white", 74], ["#1C1C1C", "text black", 26]],
  }),
  stylePalette("editorial", {
    slug: "editorial-walnut-column",
    name: "Walnut Column",
    mood: "Warm, crafted, considered",
    description: "Oat paper, walnut-brown type and a terracotta pull-quote colour. For food, travel and culture magazines.",
    composition: "fields",
    colours: [["#EEE7DA", "oat paper", 62], ["#3E2A20", "walnut", 28], ["#B4573A", "terracotta", 10]],
  }),
  stylePalette("editorial", {
    slug: "editorial-sunday-supplement",
    name: "Sunday Supplement",
    mood: "Polished, warm, readable",
    description: "Off-white, black text, a sand panel and an oxblood headline accent. A complete magazine system for blogs and newsletters.",
    composition: "window",
    colours: [["#F4F1EA", "off-white", 48], ["#1D1D1D", "text black", 28], ["#D9CBB3", "sand panel", 14], ["#7B2430", "oxblood", 10]],
  }),
  stylePalette("editorial", {
    slug: "editorial-review",
    name: "Review",
    mood: "Cool, intelligent, modern",
    description: "Pale stone, ink navy, a slate panel and a mustard highlight. A cooler editorial for science, policy and tech writing.",
    composition: "fields",
    colours: [["#ECEBE6", "pale stone", 48], ["#1B2433", "ink navy", 28], ["#B9BFC4", "slate panel", 14], ["#C9962C", "mustard", 10]],
  }),

  // ——— Editorial Poster ———
  stylePalette("editorial-poster", {
    slug: "editorial-poster-broadsheet",
    name: "Broadsheet",
    mood: "Stark, journalistic, direct",
    description: "Newsprint white and press black: the front page at full contrast.",
    composition: "split",
    colours: [["#EEECE6", "newsprint white", 66], ["#0D0D0D", "press black", 34]],
  }),
  stylePalette("editorial-poster", {
    slug: "editorial-poster-flag",
    name: "Flag Red",
    mood: "Urgent, headline, political",
    description: "Newsprint, press black and a small flag-red accent. One red mark makes the headline land.",
    composition: "split",
    colours: [["#EDEBE4", "newsprint", 60], ["#111111", "press black", 32], ["#C8201E", "flag red", 8]],
  }),
  stylePalette("editorial-poster", {
    slug: "editorial-poster-halftone",
    name: "Halftone",
    mood: "Grainy, documentary, graphic",
    description: "Newsprint, black, mid halftone grey and a red flag. The grey carries photographs without competing with type.",
    composition: "stripes",
    colours: [["#ECEAE3", "newsprint", 46], ["#0F0F0F", "black", 28], ["#8A8A86", "halftone grey", 18], ["#C42A20", "flag red", 8]],
  }),
  stylePalette("editorial-poster", {
    slug: "editorial-poster-late-edition",
    name: "Late Edition",
    mood: "Nocturnal, grave, sharp",
    description: "Black ground, newsprint type, a dark grey and a red slash. The inverted front page for dark-mode news.",
    composition: "steps",
    colours: [["#131313", "night black", 52], ["#E8E5DD", "newsprint", 28], ["#4A4A48", "dark halftone", 12], ["#D3291F", "red slash", 8]],
  }),

  // ——— Concert Poster ———
  stylePalette("concert-poster", {
    slug: "concert-poster-spotlight",
    name: "Spotlight",
    mood: "Stark, live, dramatic",
    description: "Stage black and one spotlight white. Everything else is the performer.",
    composition: "orbit",
    colours: [["#0B0B0C", "stage black", 72], ["#EDEDEA", "spotlight white", 28]],
  }),
  stylePalette("concert-poster", {
    slug: "concert-poster-amber-flare",
    name: "Amber Flare",
    mood: "Warm, smoky, electric",
    description: "Stage black, haze-white type and a single amber lens flare. For gigs, festivals and venue sites.",
    composition: "orbit",
    colours: [["#0C0C0D", "stage black", 62], ["#E6E4DE", "haze white", 28], ["#E8A33D", "amber flare", 10]],
  }),
  stylePalette("concert-poster", {
    slug: "concert-poster-smoke",
    name: "Smoke Machine",
    mood: "Atmospheric, moody, loud",
    description: "Black, spotlight white, haze grey and a deep red gel. Smoke and one coloured light.",
    composition: "wave",
    colours: [["#0D0D0E", "black", 50], ["#ECEBE7", "spotlight", 24], ["#5E5E61", "haze grey", 16], ["#B3261E", "red gel", 10]],
  }),
  stylePalette("concert-poster", {
    slug: "concert-poster-encore",
    name: "Encore",
    mood: "Euphoric, warm, nocturnal",
    description: "Deep plum-black, warm white, an amber wash and a magenta gel. Gig posters for a crowd that stayed late.",
    composition: "orbit",
    colours: [["#16101A", "plum black", 50], ["#F0E9DC", "warm white", 26], ["#E39B3A", "amber wash", 14], ["#C2367A", "magenta gel", 10]],
  }),

  // ——— Film Still Poster ———
  stylePalette("film-still-poster", {
    slug: "film-still-poster-silver",
    name: "Silver Print",
    mood: "Classic, cinematic, monochrome",
    description: "Silver white and film black. A black-and-white still, all tone and no colour.",
    composition: "window",
    colours: [["#E6E4DF", "silver white", 64], ["#141414", "film black", 36]],
  }),
  stylePalette("film-still-poster", {
    slug: "film-still-poster-title-red",
    name: "Title Red",
    mood: "Noir, tense, iconic",
    description: "Film black, silver type and a single red title. The spot colour every thriller poster reaches for.",
    composition: "window",
    colours: [["#121212", "film black", 62], ["#E4E1DA", "silver", 28], ["#C8161D", "title red", 10]],
  }),
  stylePalette("film-still-poster", {
    slug: "film-still-poster-festival",
    name: "Festival Cut",
    mood: "Arthouse, quiet, graphic",
    description: "Pale silver, black, still grey and a red laurel. A film-festival look for streaming and cinema sites.",
    composition: "fields",
    colours: [["#E3E1DB", "pale silver", 46], ["#151515", "black", 28], ["#7A7A78", "still grey", 18], ["#B81C22", "laurel red", 8]],
  }),
  stylePalette("film-still-poster", {
    slug: "film-still-poster-cold-open",
    name: "Cold Open",
    mood: "Chilly, restrained, suspenseful",
    description: "Blue-black, silver, a steel grey and a single cold cyan. A spot colour for sci-fi and thrillers instead of red.",
    composition: "split",
    colours: [["#11151A", "blue-black", 52], ["#DADDDF", "silver", 26], ["#5C646B", "steel grey", 14], ["#5FB7C9", "cold cyan", 8]],
  }),

  // ——— Streetwear Poster ———
  stylePalette("streetwear-poster", {
    slug: "streetwear-poster-drop-red",
    name: "Drop Red",
    mood: "Hyped, flat, aggressive",
    description: "Poster red with paper-white type: the drop announcement. Big, flat and impossible to miss.",
    composition: "split",
    colours: [["#C4161C", "poster red", 70], ["#F1EFE8", "paper white", 30]],
  }),
  stylePalette("streetwear-poster", {
    slug: "streetwear-poster-acid-cut",
    name: "Acid Cut",
    mood: "Loud, youthful, raw",
    description: "Ink black ground, paper-white type and an acid yellow hit. For merch, sneaker drops and club nights.",
    composition: "stripes",
    colours: [["#111111", "ink black", 60], ["#EFEDE6", "paper white", 28], ["#E3E934", "acid yellow", 12]],
  }),
  stylePalette("streetwear-poster", {
    slug: "streetwear-poster-flyposter",
    name: "Flyposter",
    mood: "Gritty, bold, urban",
    description: "Paper white, ink black, poster red and acid yellow, layered like flyposters on a wall. The full streetwear kit.",
    composition: "steps",
    colours: [["#EFEDE6", "paper white", 42], ["#111111", "ink black", 28], ["#C4161C", "poster red", 18], ["#E3E934", "acid yellow", 12]],
  }),
  stylePalette("streetwear-poster", {
    slug: "streetwear-poster-utility",
    name: "Utility",
    mood: "Technical, tough, outdoor",
    description: "Olive drab ground, bone type, black straps and a safety orange tab. Workwear and gorpcore drops.",
    composition: "stripes",
    colours: [["#4B4A33", "olive drab", 48], ["#E8E2D2", "bone", 28], ["#151515", "strap black", 14], ["#F05A1A", "safety orange", 10]],
  }),

  // ——— Shoegaze ———
  stylePalette("shoegaze", {
    slug: "shoegaze-sea-haze",
    name: "Sea Haze",
    mood: "Dreamy, cold, blurred",
    description: "Near-black and a faded mint haze. Barely two colours, like a washed-out record sleeve.",
    composition: "wave",
    colours: [["#0E1214", "deep black", 70], ["#C2CFC7", "faded mint", 30]],
  }),
  stylePalette("shoegaze", {
    slug: "shoegaze-reverb",
    name: "Reverb",
    mood: "Hazy, melancholic, slow",
    description: "Sea teal ground, mint-white type and a bruised violet. Low saturation that still reads, for music and film.",
    composition: "wave",
    colours: [["#1F4B4F", "sea teal", 60], ["#D3DCD5", "mint white", 28], ["#6E5A80", "bruise violet", 12]],
  }),
  stylePalette("shoegaze", {
    slug: "shoegaze-loveless",
    name: "Pink Noise",
    mood: "Saturated, fuzzy, romantic",
    description: "Wine-dark ground, blurred rose type, a teal shadow and a violet glow. Shoegaze’s warmer, louder side.",
    composition: "wave",
    colours: [["#2A0F1C", "wine dark", 50], ["#E79AB8", "blurred rose", 26], ["#2C6468", "teal shadow", 14], ["#8B5BA5", "violet glow", 10]],
  }),
  stylePalette("shoegaze", {
    slug: "shoegaze-fog-light",
    name: "Fog Light",
    mood: "Pale, distant, wistful",
    description: "Fog mint ground, deep teal-black type, a grey-green and a faint violet. A light-mode shoegaze for indie labels.",
    composition: "fields",
    colours: [["#D5DDD7", "fog mint", 48], ["#14272A", "teal black", 28], ["#8EA39C", "grey-green", 14], ["#7D6A8E", "faint violet", 10]],
  }),

  // ——— Type Doodles ———
  stylePalette("type-doodles", {
    slug: "type-doodles-marker",
    name: "Marker",
    mood: "Casual, friendly, handmade",
    description: "Notebook paper and black marker. Doodled type at its most legible.",
    composition: "wave",
    colours: [["#FBF8EF", "notebook paper", 70], ["#1F1F1F", "marker black", 30]],
  }),
  stylePalette("type-doodles", {
    slug: "type-doodles-highlighter",
    name: "Highlighter",
    mood: "Playful, studious, bright",
    description: "Paper, marker black and a coral highlighter swipe. For education, notes apps and workshops.",
    composition: "stripes",
    colours: [["#FAF6EC", "paper", 60], ["#202020", "marker black", 30], ["#FF7A59", "coral highlighter", 10]],
  }),
  stylePalette("type-doodles", {
    slug: "type-doodles-sketchbook",
    name: "Sketchbook",
    mood: "Cheerful, loose, creative",
    description: "Paper, black, sky blue and a lemon highlighter. Two bright marker colours that don’t fight.",
    composition: "orbit",
    colours: [["#FBF8EF", "sketchbook paper", 46], ["#1F1F1F", "marker black", 28], ["#4BB3FD", "sky blue", 16], ["#FFD84D", "lemon", 10]],
  }),
  stylePalette("type-doodles", {
    slug: "type-doodles-chalkboard",
    name: "Chalkboard",
    mood: "Warm, nostalgic, hand-lettered",
    description: "Slate green board, chalk white, a pink chalk and a yellow chalk. Café menus and classroom energy.",
    composition: "fields",
    colours: [["#2F3D36", "slate board", 52], ["#EDEBE3", "chalk", 26], ["#F2A6B5", "pink chalk", 12], ["#F2D46B", "yellow chalk", 10]],
  }),

  // ——— Handwritten ———
  stylePalette("handwritten", {
    slug: "handwritten-fountain-pen",
    name: "Fountain Pen",
    mood: "Personal, quiet, literary",
    description: "Warm writing paper and blue-black ink. A letter, ready for a newsletter or wedding site.",
    composition: "fields",
    colours: [["#F1E9DA", "writing paper", 72], ["#23324F", "blue-black ink", 28]],
  }),
  stylePalette("handwritten", {
    slug: "handwritten-sepia-letter",
    name: "Sepia Letter",
    mood: "Old, warm, sentimental",
    description: "Cream laid paper, sepia ink and a sealing-wax red. For heritage brands, memoirs and invitations.",
    composition: "fields",
    colours: [["#EFE4CF", "laid paper", 62], ["#3A2F28", "sepia ink", 28], ["#9A2C24", "sealing wax", 10]],
  }),
  stylePalette("handwritten", {
    slug: "handwritten-journal",
    name: "Journal",
    mood: "Thoughtful, tactile, calm",
    description: "Paper, blue-black ink, kraft card and a faded green pencil. Journals, coaching and craft shops.",
    composition: "window",
    colours: [["#F2EBDD", "journal paper", 46], ["#26324A", "ink", 28], ["#B89A74", "kraft card", 16], ["#7E9472", "green pencil", 10]],
  }),
  stylePalette("handwritten", {
    slug: "handwritten-postcard",
    name: "Postcard",
    mood: "Sunny, nostalgic, light",
    description: "Pale card, sepia handwriting, a sea blue stamp and a postmark red. Holiday warmth for travel brands.",
    composition: "split",
    colours: [["#F4ECDD", "pale card", 46], ["#3B2E24", "sepia hand", 28], ["#3F7FA6", "sea stamp", 16], ["#C54B3A", "postmark red", 10]],
  }),

  // ——— Tech Spec ———
  stylePalette("tech-spec", {
    slug: "tech-spec-datasheet",
    name: "Datasheet",
    mood: "Exact, technical, neutral",
    description: "Lab grey and spec black. Clean enough for documentation and developer tools.",
    composition: "window",
    colours: [["#E7E7E3", "lab grey", 70], ["#161616", "spec black", 30]],
  }),
  stylePalette("tech-spec", {
    slug: "tech-spec-safety-tag",
    name: "Safety Tag",
    mood: "Industrial, functional, alert",
    description: "Lab grey, spec black and a safety orange used only for warnings and calls to action.",
    composition: "stripes",
    colours: [["#E5E5E1", "lab grey", 62], ["#151515", "spec black", 30], ["#FF5A1F", "safety orange", 8]],
  }),
  stylePalette("tech-spec", {
    slug: "tech-spec-instrument",
    name: "Instrument",
    mood: "Engineered, calm, premium",
    description: "Off-white, graphite, aluminium and an instrument orange. Hardware product pages and spec sheets.",
    composition: "fields",
    colours: [["#EEEEEA", "off-white", 46], ["#1E1F21", "graphite", 28], ["#A2A7AA", "aluminium", 16], ["#F2611D", "instrument orange", 10]],
  }),
  stylePalette("tech-spec", {
    slug: "tech-spec-terminal",
    name: "Terminal",
    mood: "Dark, precise, developer",
    description: "Carbon ground, light grey text, a muted grey panel and an orange cursor. A dark-mode spec for dev tools.",
    composition: "window",
    colours: [["#17181A", "carbon", 54], ["#DCDDD9", "readout grey", 26], ["#3A3C40", "panel grey", 12], ["#FF6A2B", "cursor orange", 8]],
  }),

  // ——— Blueprint ———
  stylePalette("blueprint", {
    slug: "blueprint-cyanotype",
    name: "Cyanotype",
    mood: "Technical, cool, crisp",
    description: "Deep cyanotype blue with chalk-white line. The reprographic original.",
    composition: "window",
    colours: [["#173A73", "cyanotype blue", 76], ["#EAF1FA", "chalk line", 24]],
  }),
  stylePalette("blueprint", {
    slug: "blueprint-redline",
    name: "Redline",
    mood: "Analytical, annotated, precise",
    description: "Prussian blue, white line and a redline correction. For engineering, architecture and process diagrams.",
    composition: "steps",
    colours: [["#1B3F7A", "Prussian blue", 64], ["#E8EFF8", "white line", 28], ["#F0675A", "redline", 8]],
  }),
  stylePalette("blueprint", {
    slug: "blueprint-drafting-table",
    name: "Drafting Table",
    mood: "Methodical, layered, technical",
    description: "Deep blue, chalk line, faded mid-blue and a pencil yellow note. Depth for diagrams with several layers.",
    composition: "window",
    colours: [["#0F2750", "deep blue", 50], ["#EAF1FA", "chalk line", 24], ["#5F86C0", "faded blue", 16], ["#F2D06B", "pencil yellow", 10]],
  }),
  stylePalette("blueprint", {
    slug: "blueprint-whiteprint",
    name: "Whiteprint",
    mood: "Light, technical, airy",
    description: "Whiteprint paper, Prussian line, a pale blue fill and a red dimension. The inverted blueprint for light UIs.",
    composition: "fields",
    colours: [["#EEF2F6", "whiteprint", 50], ["#1B3F7A", "Prussian line", 26], ["#B9CCE6", "pale blue fill", 14], ["#D9483B", "dimension red", 10]],
  }),

  // ——— Collage Art ———
  stylePalette("collage-art", {
    slug: "collage-art-kraft-navy",
    name: "Kraft & Navy",
    mood: "Tactile, archival, warm",
    description: "Kraft paper and faded navy. The backbone of a cut-paper collage, for zines and craft brands.",
    composition: "split",
    colours: [["#D8C3A0", "kraft paper", 66], ["#23364F", "faded navy", 34]],
  }),
  stylePalette("collage-art", {
    slug: "collage-art-scrapbook",
    name: "Scrapbook",
    mood: "Found, nostalgic, layered",
    description: "Aged cream, black ink and a brick-red scrap. Feels pasted together, still reads clearly.",
    composition: "steps",
    colours: [["#E9DFCB", "aged cream", 58], ["#1C1B19", "ink", 30], ["#B8483A", "brick scrap", 12]],
  }),
  stylePalette("collage-art", {
    slug: "collage-art-magazine-cutout",
    name: "Magazine Cutout",
    mood: "Bright, eclectic, mixed",
    description: "Newsprint grey, black, a magazine teal and a printer yellow. Mixed sources that still belong together.",
    composition: "split",
    colours: [["#DCD8CF", "newsprint grey", 44], ["#191919", "black", 28], ["#2C7A7B", "magazine teal", 16], ["#E5B83A", "printer yellow", 12]],
  }),
  stylePalette("collage-art", {
    slug: "collage-art-dada",
    name: "Dada",
    mood: "Absurd, graphic, rebellious",
    description: "Faded pink paper, black type, a stamp red and a pale blue ticket. Early avant-garde collage for art events.",
    composition: "steps",
    colours: [["#EFD9CF", "faded pink paper", 46], ["#1A1918", "type black", 28], ["#C53A2E", "stamp red", 14], ["#9FB8C9", "ticket blue", 12]],
  }),

  // ——— Grunge ———
  stylePalette("grunge", {
    slug: "grunge-soot-cream",
    name: "Soot & Cream",
    mood: "Worn, raw, heavy",
    description: "Soot black and dirty cream. Photocopied and lived in.",
    composition: "stripes",
    colours: [["#2B2A26", "soot", 68], ["#D9CDB0", "dirty cream", 32]],
  }),
  stylePalette("grunge", {
    slug: "grunge-rust-belt",
    name: "Rust Belt",
    mood: "Gritty, industrial, warm",
    description: "Dirty cream, soot type and a rust stain. Raw for bands, skate and denim.",
    composition: "split",
    colours: [["#D6CAAD", "dirty cream", 58], ["#262521", "soot", 30], ["#A8542E", "rust", 12]],
  }),
  stylePalette("grunge", {
    slug: "grunge-flannel",
    name: "Flannel",
    mood: "Rough, warm, nineties",
    description: "Army olive ground, cream type, a flannel red and soot black. Plaid, distortion and thrift-store warmth.",
    composition: "stripes",
    colours: [["#4F4E30", "army olive", 48], ["#DCD0B4", "cream", 26], ["#8E2B25", "flannel red", 14], ["#1E1D1A", "soot", 12]],
  }),
  stylePalette("grunge", {
    slug: "grunge-basement",
    name: "Basement Show",
    mood: "Dark, smoky, underground",
    description: "Near-black, bone type, a bruised purple and a mustard flyer. For gig posters and underground labels.",
    composition: "fields",
    colours: [["#1B1A18", "basement black", 52], ["#D8CFBB", "bone", 26], ["#5B3A57", "bruised purple", 12], ["#C29A3A", "mustard flyer", 10]],
  }),

  // ——— Punk ———
  stylePalette("punk", {
    slug: "punk-xerox",
    name: "Xerox",
    mood: "Raw, cheap, defiant",
    description: "Xerox white and toner black. The photocopied flyer, nothing else needed.",
    composition: "split",
    colours: [["#F0EEE7", "xerox white", 64], ["#0F0F0F", "toner black", 36]],
  }),
  stylePalette("punk", {
    slug: "punk-fluoro-pink",
    name: "Fluoro Pink",
    mood: "Loud, defiant, DIY",
    description: "Fluoro pink ground with toner-black type and a white cut. Sex Pistols-era shock for gig and merch sites.",
    composition: "stripes",
    colours: [["#FF2E88", "fluoro pink", 58], ["#0F0F0F", "toner black", 30], ["#F2F0EA", "cut white", 12]],
  }),
  stylePalette("punk", {
    slug: "punk-ransom-note",
    name: "Ransom Note",
    mood: "Chaotic, cut-up, aggressive",
    description: "White, black, fluoro yellow and fluoro pink, layered like cut-out letters. Maximum noise, still legible.",
    composition: "steps",
    colours: [["#F0EEE7", "xerox white", 42], ["#0F0F0F", "toner black", 30], ["#F4E12B", "fluoro yellow", 16], ["#FF2E88", "fluoro pink", 12]],
  }),
  stylePalette("punk", {
    slug: "punk-safety-pin",
    name: "Safety Pin",
    mood: "Dark, sharp, anarchic",
    description: "Black ground, white type, a tartan red and a fluoro yellow tag. Dark-mode punk for labels and zines.",
    composition: "stripes",
    colours: [["#121212", "black", 52], ["#EFEDE6", "white", 28], ["#B8202A", "tartan red", 12], ["#F4E12B", "fluoro yellow", 8]],
  }),

  // ——— New Wave ———
  stylePalette("new-wave", {
    slug: "new-wave-night-drive",
    name: "Night Drive",
    mood: "Cool, synthetic, sleek",
    description: "Night navy with a cool cyan line. Synth-pop calm for music and tech.",
    composition: "wave",
    colours: [["#111827", "night navy", 70], ["#62D2E8", "cool cyan", 30]],
  }),
  stylePalette("new-wave", {
    slug: "new-wave-rose-sleeve",
    name: "Rose Sleeve",
    mood: "Stylish, bright, eighties",
    description: "Sleeve white, navy type and a neon rose accent. Light and graphic, with one hot note.",
    composition: "split",
    colours: [["#EDEBE6", "sleeve white", 60], ["#141B2D", "navy", 30], ["#FF4F9A", "neon rose", 10]],
  }),
  stylePalette("new-wave", {
    slug: "new-wave-synth",
    name: "Synth",
    mood: "Electric, cool, danceable",
    description: "Navy, white, cool cyan and neon rose: complementary neons balanced by a dark ground. Club nights and playlists.",
    composition: "stripes",
    colours: [["#121A2B", "navy", 50], ["#EDEBE6", "white", 24], ["#62D2E8", "cool cyan", 16], ["#FF4F9A", "neon rose", 10]],
  }),
  stylePalette("new-wave", {
    slug: "new-wave-geometry",
    name: "Geometry",
    mood: "Angular, clean, playful",
    description: "Pale grey, black, a cobalt triangle and a lemon zigzag. Album-sleeve geometry for creative studios.",
    composition: "steps",
    colours: [["#E3E3E1", "pale grey", 46], ["#151515", "black", 28], ["#2846C8", "cobalt", 16], ["#F2E14A", "lemon", 10]],
  }),

  // ——— Graffiti ———
  stylePalette("graffiti", {
    slug: "graffiti-chrome-wall",
    name: "Chrome Wall",
    mood: "Bold, urban, metallic",
    description: "Concrete grey wall with chrome-yellow fill. Throw-up simplicity with strong contrast.",
    composition: "wave",
    colours: [["#4F4B47", "concrete wall", 66], ["#FFE33D", "chrome yellow", 34]],
  }),
  stylePalette("graffiti", {
    slug: "graffiti-wildstyle",
    name: "Wildstyle",
    mood: "Energetic, saturated, street",
    description: "Black wall, spray magenta fill and a white outline. Loud colour held together by a dark ground.",
    composition: "wave",
    colours: [["#151515", "black wall", 58], ["#FF3D7F", "spray magenta", 30], ["#F4F2EC", "white outline", 12]],
  }),
  stylePalette("graffiti", {
    slug: "graffiti-whole-car",
    name: "Whole Car",
    mood: "Vivid, celebratory, loud",
    description: "Concrete, chrome yellow, spray mint and magenta. A full piece balanced around one warm and one cool spray.",
    composition: "stripes",
    colours: [["#5A5652", "concrete", 44], ["#FFE33D", "chrome yellow", 26], ["#25D0B4", "spray mint", 18], ["#FF3D7F", "spray magenta", 12]],
  }),
  stylePalette("graffiti", {
    slug: "graffiti-paste-up",
    name: "Paste-Up",
    mood: "Streetwise, layered, cool",
    description: "Pale wall white, black stencil, a cobalt tag and a tangerine drip. Lighter street art for event and brand sites.",
    composition: "split",
    colours: [["#E7E4DE", "wall white", 48], ["#171717", "stencil black", 28], ["#2A52D9", "cobalt tag", 14], ["#FF8A1F", "tangerine drip", 10]],
  }),
];
