import type { PaletteRecord } from "../types";
import { stylePalette } from "./define";

/** Palettes made for the retro styles (src/content/styles/retro.ts), four per style. */
export const retroPalettes: PaletteRecord[] = [
  // ——— 70s Retro ———
  stylePalette("70s-retro", {
    slug: "70s-retro-burnt-sunset",
    name: "Burnt Sunset",
    mood: "Warm, groovy, sunlit",
    description: "Sun-bleached cream and a deep rust. The essential seventies warmth for food, music and lifestyle.",
    composition: "wave",
    colours: [["#F3E3C3", "sun-bleached cream", 66], ["#A83F1D", "rust", 34]],
  }),
  stylePalette("70s-retro", {
    slug: "70s-retro-shag",
    name: "Shag Pile",
    mood: "Cosy, earthy, nostalgic",
    description: "Olive-brown ground, cream type and a burnt orange stripe. Den-and-record-player warmth for cafés and vintage shops.",
    composition: "stripes",
    colours: [["#4A3C17", "olive brown", 58], ["#F1DFBE", "cream", 30], ["#E0762A", "burnt orange", 12]],
  }),
  stylePalette("70s-retro", {
    slug: "70s-retro-sunburst",
    name: "Sunburst",
    mood: "Cheerful, bold, retro",
    description: "Cream, chocolate type, mustard and orange rays. A complete seventies system with a dark anchor for legibility.",
    composition: "orbit",
    colours: [["#F4E4C4", "cream", 44], ["#3D2516", "chocolate", 28], ["#E2A52A", "mustard", 16], ["#E0702A", "orange ray", 12]],
  }),
  stylePalette("70s-retro", {
    slug: "70s-retro-avocado",
    name: "Avocado Kitchen",
    mood: "Homely, mellow, earthy",
    description: "Harvest gold ground, dark brown type, avocado green and a rust accent. Kitchen-appliance colours for food and home brands.",
    composition: "fields",
    colours: [["#E8C77A", "harvest gold", 46], ["#33251A", "dark brown", 28], ["#6E7A2E", "avocado", 16], ["#A7431F", "rust", 10]],
  }),

  // ——— Retro ———
  stylePalette("retro", {
    slug: "retro-teal-ink",
    name: "Teal Ink",
    mood: "Classic, printed, calm",
    description: "Aged paper and a deep teal ink. A one-ink print look for labels and craft brands.",
    composition: "fields",
    colours: [["#EFE3C8", "aged paper", 68], ["#1F4A54", "deep teal", 32]],
  }),
  stylePalette("retro", {
    slug: "retro-diner",
    name: "Diner",
    mood: "Friendly, all-American, warm",
    description: "Aged cream, poster red and a mustard sign. Two inks plus a highlight, like a vintage menu.",
    composition: "stripes",
    colours: [["#F0E4CA", "aged cream", 60], ["#C4392A", "poster red", 28], ["#E9B44C", "mustard sign", 12]],
  }),
  stylePalette("retro", {
    slug: "retro-matchbook",
    name: "Matchbook",
    mood: "Charming, printed, nostalgic",
    description: "Aged paper, deep teal, poster red and mustard: three inks on paper, as they printed it. For bars, labels and merch.",
    composition: "split",
    colours: [["#EFE3C8", "aged paper", 44], ["#23535E", "deep teal", 28], ["#D0442C", "poster red", 16], ["#E9B44C", "mustard ink", 12]],
  }),
  stylePalette("retro", {
    slug: "retro-travel-poster",
    name: "Travel Poster",
    mood: "Sunny, adventurous, vintage",
    description: "Sky cream, navy type, a sea blue and a sunset coral. Railway-poster optimism for travel and outdoor brands.",
    composition: "wave",
    colours: [["#F2E6CC", "sky cream", 46], ["#1F2E4A", "navy", 28], ["#4C8EAE", "sea blue", 16], ["#E8735A", "sunset coral", 10]],
  }),

  // ——— Synthwave ———
  stylePalette("synthwave", {
    slug: "synthwave-laser",
    name: "Laser Grid",
    mood: "Nocturnal, neon, retro-future",
    description: "Midnight violet with a laser cyan line. The grid at its simplest.",
    composition: "stripes",
    colours: [["#140B2E", "midnight violet", 70], ["#21E6FF", "laser cyan", 30]],
  }),
  stylePalette("synthwave", {
    slug: "synthwave-outrun",
    name: "Outrun",
    mood: "Fast, hot, cinematic",
    description: "Midnight ground, hot magenta and a sunset orange horizon. For games, music and tech launches.",
    composition: "wave",
    colours: [["#16092E", "midnight", 60], ["#FF2E97", "hot magenta", 28], ["#FF9F1C", "sunset orange", 12]],
  }),
  stylePalette("synthwave", {
    slug: "synthwave-sunset-drive",
    name: "Sunset Drive",
    mood: "Euphoric, neon, eighties",
    description: "Violet night, pale lavender type, magenta and cyan. Complementary neons on dark, with a light colour for text.",
    composition: "stripes",
    colours: [["#1A0E36", "violet night", 50], ["#EDE3FF", "lavender white", 24], ["#FF2E97", "magenta", 16], ["#21E6FF", "cyan", 10]],
  }),
  stylePalette("synthwave", {
    slug: "synthwave-chrome-dawn",
    name: "Chrome Dawn",
    mood: "Glowing, dreamy, warm",
    description: "Deep plum, peach-gold sun, a hot pink haze and a violet mountain. The warm end of the synthwave sky.",
    composition: "arch",
    colours: [["#2A0F3A", "deep plum", 50], ["#FFC67A", "peach-gold sun", 24], ["#FF4F9E", "pink haze", 16], ["#6B3FD1", "violet ridge", 10]],
  }),

  // ——— Italo Disco ———
  stylePalette("italo-disco", {
    slug: "italo-disco-mirrorball",
    name: "Mirrorball",
    mood: "Glamorous, nocturnal, shiny",
    description: "Space navy and spotlight gold. Disco glamour in two colours.",
    composition: "orbit",
    colours: [["#0D0A24", "space navy", 70], ["#FFD86B", "spotlight gold", 30]],
  }),
  stylePalette("italo-disco", {
    slug: "italo-disco-laser-pink",
    name: "Laser Pink",
    mood: "Danceable, bright, kitsch",
    description: "Space navy, laser pink and chrome blue. Two lasers on a dark dance floor.",
    composition: "stripes",
    colours: [["#100C2A", "space navy", 60], ["#E83FB4", "laser pink", 28], ["#8FD3FF", "chrome blue", 12]],
  }),
  stylePalette("italo-disco", {
    slug: "italo-disco-riviera",
    name: "Riviera Night",
    mood: "Romantic, synth, glamorous",
    description: "Navy, chrome blue type, laser pink and gold. The full Italo kit for club nights and radio.",
    composition: "orbit",
    colours: [["#0D0A24", "space navy", 50], ["#B8E3FF", "chrome blue", 24], ["#E83FB4", "laser pink", 16], ["#FFD86B", "spotlight gold", 10]],
  }),
  stylePalette("italo-disco", {
    slug: "italo-disco-maxi-single",
    name: "Maxi Single",
    mood: "Playful, bright, retro",
    description: "Pale chrome sleeve, deep violet type, hot pink and a gold stripe. A daytime Italo look for merch and playlists.",
    composition: "stripes",
    colours: [["#E6ECF5", "chrome sleeve", 46], ["#2A1550", "deep violet", 28], ["#E83FB4", "hot pink", 16], ["#E7B93A", "gold stripe", 10]],
  }),

  // ——— Future Funk ———
  stylePalette("future-funk", {
    slug: "future-funk-bubblegum-ink",
    name: "Bubblegum Ink",
    mood: "Sweet, bouncy, anime",
    description: "Blush ground with a deep berry ink for type. Future funk sweetness that still reads.",
    composition: "orbit",
    colours: [["#FFE9F3", "blush", 68], ["#8A1E5C", "berry ink", 32]],
  }),
  stylePalette("future-funk", {
    slug: "future-funk-city-pop",
    name: "City Pop",
    mood: "Summery, nostalgic, upbeat",
    description: "Summer-sky blue ground, deep navy type and a lemon highlight. Sunny eighties Tokyo for music and lifestyle.",
    composition: "wave",
    colours: [["#A9E0FF", "summer sky", 60], ["#13254F", "deep navy", 28], ["#FFD447", "lemon", 12]],
  }),
  stylePalette("future-funk", {
    slug: "future-funk-sampler",
    name: "Sampler",
    mood: "Energetic, cute, looping",
    description: "Blush, deep violet type, bubblegum and summer sky. Pastels with a dark anchor so headlines stay readable.",
    composition: "orbit",
    colours: [["#FFE9F3", "blush", 44], ["#2E1A4F", "deep violet", 28], ["#FF6FB5", "bubblegum", 16], ["#59C3FF", "summer sky", 12]],
  }),
  stylePalette("future-funk", {
    slug: "future-funk-night-loop",
    name: "Night Loop",
    mood: "Glowing, dreamy, danceable",
    description: "Indigo night, bubblegum type, lemon and sky. The after-dark future funk for streams and visuals.",
    composition: "stripes",
    colours: [["#1C1640", "indigo night", 50], ["#FF8AC4", "bubblegum", 24], ["#FFD447", "lemon", 14], ["#59C3FF", "sky", 12]],
  }),

  // ——— Vaporwave ———
  stylePalette("vaporwave", {
    slug: "vaporwave-dusk-mall",
    name: "Dusk Mall",
    mood: "Hazy, ironic, nostalgic",
    description: "Lavender white and dusk violet. Vaporwave pared back to something you can set type in.",
    composition: "arch",
    colours: [["#F4F1FF", "lavender white", 66], ["#5B3FC4", "dusk violet", 34]],
  }),
  stylePalette("vaporwave", {
    slug: "vaporwave-pool",
    name: "Pool Party",
    mood: "Dreamy, glossy, surreal",
    description: "Deep violet night, pool teal type and a vapor pink accent. The classic vapor pairing on dark.",
    composition: "wave",
    colours: [["#22184A", "deep violet", 60], ["#7DE3E1", "pool teal", 28], ["#FF9ECF", "vapor pink", 12]],
  }),
  stylePalette("vaporwave", {
    slug: "vaporwave-aesthetic",
    name: "Aesthetic",
    mood: "Surreal, pastel, ironic",
    description: "Vapor pink ground, deep indigo type, pool teal and a marble white. Full vaporwave with a dark text colour.",
    composition: "arch",
    colours: [["#FFB8DA", "vapor pink", 44], ["#24195A", "deep indigo", 28], ["#7DE3E1", "pool teal", 16], ["#F4F1FF", "marble white", 12]],
  }),
  stylePalette("vaporwave", {
    slug: "vaporwave-windows-95",
    name: "Desktop ’95",
    mood: "Glitchy, nostalgic, digital",
    description: "Desktop teal, lavender white, a dusk violet bar and a hot pink cursor. Old operating systems, softened.",
    composition: "window",
    colours: [["#2E7F86", "desktop teal", 48], ["#F4F1FF", "lavender white", 26], ["#8A6CFF", "dusk violet", 16], ["#FF5FB0", "hot pink", 10]],
  }),

  // ——— Gen X Soft Club ———
  stylePalette("gen-x-soft-club", {
    slug: "gen-x-soft-club-frost",
    name: "Frost",
    mood: "Cool, calm, translucent",
    description: "Frosted blue-white and twilight blue. Soft club’s quiet, clean side.",
    composition: "wave",
    colours: [["#DDE7EF", "frosted blue-white", 68], ["#3F5F84", "twilight blue", 32]],
  }),
  stylePalette("gen-x-soft-club", {
    slug: "gen-x-soft-club-chill-out",
    name: "Chill-Out Room",
    mood: "Hushed, airy, late-night",
    description: "Deep twilight ground, frosted type and a soft silver. Low contrast in the accent, clear contrast in the text.",
    composition: "wave",
    colours: [["#26364D", "deep twilight", 60], ["#DDE7EF", "frosted white", 28], ["#A8BCCB", "ice grey", 12]],
  }),
  stylePalette("gen-x-soft-club", {
    slug: "gen-x-soft-club-minidisc",
    name: "MiniDisc",
    mood: "Sleek, techy, gentle",
    description: "Brushed silver, navy type, twilight blue and a pale lilac. Late-nineties hardware for music and tech sites.",
    composition: "orbit",
    colours: [["#D3D8DD", "brushed silver", 46], ["#1F2C44", "navy", 28], ["#5E7FA3", "twilight blue", 16], ["#C8B8E6", "pale lilac", 10]],
  }),
  stylePalette("gen-x-soft-club", {
    slug: "gen-x-soft-club-sunrise-set",
    name: "Sunrise Set",
    mood: "Warm, hopeful, hazy",
    description: "Pale ice, slate type, a peach sunrise and soft aqua. The end of the night, warming up.",
    composition: "wave",
    colours: [["#E6ECF1", "pale ice", 46], ["#34465E", "slate", 28], ["#F2C3A6", "peach sunrise", 14], ["#9FD3D6", "soft aqua", 12]],
  }),

  // ——— Psychedelic ———
  stylePalette("psychedelic", {
    slug: "psychedelic-haze",
    name: "Purple Haze",
    mood: "Trippy, vivid, swirling",
    description: "Purple haze ground with a marigold that vibrates against it. Complementary contrast at full strength.",
    composition: "wave",
    colours: [["#5A1F96", "purple haze", 66], ["#FFD23F", "marigold", 34]],
  }),
  stylePalette("psychedelic", {
    slug: "psychedelic-fillmore",
    name: "Fillmore",
    mood: "Loud, hand-lettered, sixties",
    description: "Tangerine ground, deep purple lettering and an electric green. Concert-poster clashes for festivals and bands.",
    composition: "wave",
    colours: [["#FF7A2A", "tangerine", 58], ["#3A1166", "deep purple", 30], ["#2FBF71", "electric green", 12]],
  }),
  stylePalette("psychedelic", {
    slug: "psychedelic-kaleidoscope",
    name: "Kaleidoscope",
    mood: "Intense, saturated, cosmic",
    description: "Deep violet with marigold, magenta and electric green: two complementary pairs, held by a dark ground. For art, music and bold campaigns.",
    composition: "orbit",
    colours: [["#2A0E4F", "deep violet", 44], ["#FFD23F", "marigold", 28], ["#D42A8B", "magenta", 16], ["#2FBF71", "electric green", 12]],
  }),
  stylePalette("psychedelic", {
    slug: "psychedelic-flower-power",
    name: "Flower Power",
    mood: "Sunny, joyful, free",
    description: "Cream, a dark plum line, orange petals and green leaves. Softer sixties for food, festivals and kids.",
    composition: "orbit",
    colours: [["#FBEFD2", "cream", 46], ["#4A1650", "plum line", 28], ["#FF6B1A", "orange petal", 16], ["#3DAA5C", "leaf green", 10]],
  }),

  // ——— Acid ———
  stylePalette("acid", {
    slug: "acid-chrome",
    name: "Liquid Chrome",
    mood: "Sleek, cold, metallic",
    description: "Rave black and liquid chrome. Monochrome acid for fashion and music.",
    composition: "wave",
    colours: [["#0A0A0A", "rave black", 70], ["#D9D9D9", "liquid chrome", 30]],
  }),
  stylePalette("acid", {
    slug: "acid-ultraviolet",
    name: "Ultraviolet",
    mood: "Electric, nocturnal, intense",
    description: "Black, ultraviolet type and an acid green flash. Two hot colours kept apart by a black ground.",
    composition: "stripes",
    colours: [["#0B0B0F", "rave black", 60], ["#9B84FF", "ultraviolet", 28], ["#B6FF1A", "acid green", 12]],
  }),
  stylePalette("acid", {
    slug: "acid-warehouse",
    name: "Warehouse",
    mood: "Hard, futuristic, rave",
    description: "Black, chrome type, acid green and ultraviolet. Full acid for club nights and techno labels.",
    composition: "orbit",
    colours: [["#0A0A0A", "rave black", 50], ["#DCDCDC", "chrome", 24], ["#B6FF1A", "acid green", 16], ["#7A5CFF", "ultraviolet", 10]],
  }),
  stylePalette("acid", {
    slug: "acid-daylight",
    name: "Acid Daylight",
    mood: "Clinical, sharp, Y2K",
    description: "Chrome white, rave black type, acid green and a cold cyan. A light-mode acid for fashion and streetwear sites.",
    composition: "split",
    colours: [["#ECECEC", "chrome white", 46], ["#0E0E0E", "rave black", 28], ["#A6F01A", "acid green", 16], ["#35D6F0", "cold cyan", 10]],
  }),

  // ——— Kidcore ———
  stylePalette("kidcore", {
    slug: "kidcore-crayon",
    name: "Crayon Box",
    mood: "Playful, simple, bright",
    description: "Construction-paper cream with toy blue. One bright primary for kids’ apps and classrooms.",
    composition: "orbit",
    colours: [["#FFF7E0", "construction paper", 66], ["#1E6FD9", "toy blue", 34]],
  }),
  stylePalette("kidcore", {
    slug: "kidcore-school-bus",
    name: "School Bus",
    mood: "Cheerful, loud, friendly",
    description: "School-bus yellow ground, black type and a crayon red. Primary fun that stays readable.",
    composition: "stripes",
    colours: [["#FFCC00", "school-bus yellow", 60], ["#1B1B1B", "black", 28], ["#FF3B30", "crayon red", 12]],
  }),
  stylePalette("kidcore", {
    slug: "kidcore-playground",
    name: "Playground",
    mood: "Energetic, primary, joyful",
    description: "Cream, toy blue, crayon red and grass green. A balanced primary set for toys and education.",
    composition: "orbit",
    colours: [["#FFF7E0", "cream", 44], ["#1E5FC8", "toy blue", 28], ["#FF3B30", "crayon red", 16], ["#34B44A", "grass green", 12]],
  }),
  stylePalette("kidcore", {
    slug: "kidcore-sticker-book",
    name: "Sticker Book",
    mood: "Cute, collectable, bright",
    description: "Sky ground, navy type, a bubblegum sticker and a lemon star. Softer kidcore for apps and parties.",
    composition: "orbit",
    colours: [["#CDEBFF", "sky", 46], ["#16245A", "navy", 28], ["#FF7EB6", "bubblegum", 14], ["#FFD43B", "lemon star", 12]],
  }),

  // ——— Y2K ———
  stylePalette("y2k", {
    slug: "y2k-ice",
    name: "Ice Drive",
    mood: "Clean, digital, optimistic",
    description: "Ice white and a translucent aqua deepened for type. The millennium in two colours.",
    composition: "wave",
    colours: [["#E8F1F8", "ice white", 68], ["#1F6F99", "deep aqua", 32]],
  }),
  stylePalette("y2k", {
    slug: "y2k-chrome-heart",
    name: "Chrome Heart",
    mood: "Shiny, flirty, futuristic",
    description: "Chrome silver ground, deep navy type and an iridescent pink. Y2K fashion and beauty energy.",
    composition: "orbit",
    colours: [["#C9CED7", "chrome silver", 60], ["#1C2240", "deep navy", 28], ["#F49AC2", "iridescent pink", 12]],
  }),
  stylePalette("y2k", {
    slug: "y2k-millennium",
    name: "Millennium",
    mood: "Glossy, techno, hopeful",
    description: "Ice white, navy type, aqua and pink. Full Y2K, with a dark text colour so the pastels can stay soft.",
    composition: "wave",
    colours: [["#E8F1F8", "ice white", 44], ["#14284A", "navy", 28], ["#3FA7D6", "translucent aqua", 16], ["#F49AC2", "iridescent pink", 12]],
  }),
  stylePalette("y2k", {
    slug: "y2k-cyber-baby",
    name: "Cyber Baby",
    mood: "Sweet, glossy, digital",
    description: "Baby pink ground, ultramarine type, silver and a lime highlight. Y2K’s pop side for brands and merch.",
    composition: "orbit",
    colours: [["#FFD6EA", "baby pink", 46], ["#2333A8", "ultramarine", 28], ["#C6CBD4", "silver", 16], ["#C8F04A", "lime", 10]],
  }),

  // ——— Bubbleglam ———
  stylePalette("bubbleglam", {
    slug: "bubbleglam-cotton-candy",
    name: "Cotton Candy",
    mood: "Sweet, soft, glamorous",
    description: "Cotton-candy pink ground with a deep raspberry for type. Sugary, still legible.",
    composition: "orbit",
    colours: [["#FFE3F1", "cotton candy", 68], ["#A3195F", "raspberry", 32]],
  }),
  stylePalette("bubbleglam", {
    slug: "bubbleglam-champagne-pop",
    name: "Champagne Pop",
    mood: "Celebratory, glossy, girly",
    description: "Champagne ground, plum type and a hot bubblegum. Parties, beauty and gifting.",
    composition: "orbit",
    colours: [["#FFF4D0", "champagne", 60], ["#4A1D4E", "plum", 28], ["#FF4FA3", "hot bubblegum", 12]],
  }),
  stylePalette("bubbleglam", {
    slug: "bubbleglam-lilac-dream",
    name: "Lilac Dream",
    mood: "Dreamy, playful, shiny",
    description: "Cotton candy, deep violet type, lilac and a champagne shine. Soft glam for beauty and creators.",
    composition: "wave",
    colours: [["#FFE7F3", "cotton candy", 44], ["#3B1F66", "deep violet", 28], ["#B98CFF", "lilac", 16], ["#FFF1B0", "champagne shine", 12]],
  }),
  stylePalette("bubbleglam", {
    slug: "bubbleglam-night-out",
    name: "Night Out",
    mood: "Sparkly, bold, fun",
    description: "Midnight plum ground, pink type, lilac and gold glitter. Bubbleglam after dark.",
    composition: "orbit",
    colours: [["#2B1233", "midnight plum", 50], ["#FF8AC2", "pink", 24], ["#B98CFF", "lilac", 16], ["#F2CF6B", "gold glitter", 10]],
  }),
];
