import manifest from "./covers.generated.json";

/**
 * Cover images in public/covers, keyed by style slug. Generated by
 * scripts/covers.py. Where a style has a cover it replaces the SVG study,
 * except when the study is recoloured with a palette (a raster image can't
 * be recoloured).
 */
export interface Cover {
  src: string;
  /** The PNG in public/covers it was made from, e.g. "gothic2.png". */
  file: string;
  width: number;
  height: number;
}

const all: Record<string, Cover[]> = manifest;

/** The main cover for each style. */
export const covers: Record<string, Cover> = Object.fromEntries(
  Object.entries(all).flatMap(([slug, list]) => (list[0] ? [[slug, list[0]]] : [])),
);

/** Further covers in the same style, shown as similar images on the style page. */
export function similarCovers(slug: string): Cover[] {
  return all[slug]?.slice(1) ?? [];
}
