// Generated by scripts/mine-taste-hierarchy.mjs on 2026-10-08 with google/gemini-3.5-flash-lite. Do not edit by hand.
//
// Reading-order priors: for each kind of design, the content roles designers'
// briefs describe and the order a viewer reads them. Source: the 718
// designer-written briefs in TASTE (Zhu et al. 2026, arXiv:2605.20731; MIT),
// huggingface.co/datasets/purvanshi/TASTE. "other" pools every brief. Kinds with
// fewer than 5 briefs use the pooled order. presence: share of briefs with the role.

export type Role = "brand" | "headline" | "subhead" | "hero" | "offer" | "body" | "cta" | "contact" | "detail";
export type DesignKind = "poster" | "flyer" | "social" | "advert" | "infographic" | "screen" | "magazine" | "thumbnail" | "other";

export const ROLES: Role[] = ["brand","headline","subhead","hero","offer","body","cta","contact","detail"];
export const DESIGN_KINDS: DesignKind[] = ["poster","flyer","social","advert","infographic","screen","magazine","thumbnail","other"];

export interface HierarchyPattern {
  briefs: number;
  order: Role[];
  presence: Partial<Record<Role, number>>;
}

export const HIERARCHY: Record<DesignKind, HierarchyPattern> = {
  "poster": {
    "briefs": 81,
    "order": [
      "headline",
      "brand",
      "subhead",
      "hero",
      "body",
      "offer",
      "cta",
      "detail",
      "contact"
    ],
    "presence": {
      "headline": 0.99,
      "brand": 0.22,
      "subhead": 0.65,
      "hero": 0.9,
      "body": 0.46,
      "offer": 0.41,
      "cta": 0.31,
      "detail": 0.4,
      "contact": 0.49
    }
  },
  "flyer": {
    "briefs": 55,
    "order": [
      "brand",
      "headline",
      "hero",
      "subhead",
      "body",
      "offer",
      "cta",
      "contact",
      "detail"
    ],
    "presence": {
      "brand": 0.31,
      "headline": 1,
      "hero": 0.78,
      "subhead": 0.44,
      "body": 0.67,
      "offer": 0.36,
      "cta": 0.15,
      "contact": 0.71,
      "detail": 0.44
    }
  },
  "social": {
    "briefs": 423,
    "order": [
      "headline",
      "brand",
      "subhead",
      "hero",
      "offer",
      "cta",
      "body",
      "detail",
      "contact"
    ],
    "presence": {
      "headline": 0.9,
      "brand": 0.2,
      "subhead": 0.36,
      "hero": 0.86,
      "offer": 0.16,
      "cta": 0.16,
      "body": 0.33,
      "detail": 0.26,
      "contact": 0.28
    }
  },
  "advert": {
    "briefs": 106,
    "order": [
      "headline",
      "brand",
      "hero",
      "subhead",
      "offer",
      "body",
      "detail",
      "cta",
      "contact"
    ],
    "presence": {
      "headline": 0.86,
      "brand": 0.42,
      "hero": 0.93,
      "subhead": 0.3,
      "offer": 0.54,
      "body": 0.58,
      "detail": 0.18,
      "cta": 0.45,
      "contact": 0.57
    }
  },
  "infographic": {
    "briefs": 12,
    "order": [
      "headline",
      "hero",
      "body",
      "detail"
    ],
    "presence": {
      "headline": 1,
      "hero": 1,
      "body": 1,
      "detail": 0.42
    }
  },
  "screen": {
    "briefs": 23,
    "order": [
      "headline",
      "brand",
      "hero",
      "body",
      "cta",
      "detail"
    ],
    "presence": {
      "headline": 1,
      "brand": 0.17,
      "hero": 0.78,
      "body": 0.35,
      "cta": 0.48,
      "detail": 0.22
    }
  },
  "magazine": {
    "briefs": 9,
    "order": [
      "hero",
      "headline",
      "body"
    ],
    "presence": {
      "hero": 1,
      "headline": 0.89,
      "body": 1
    }
  },
  "thumbnail": {
    "briefs": 0,
    "order": [
      "headline",
      "brand",
      "hero",
      "subhead",
      "offer",
      "body",
      "cta",
      "detail",
      "contact"
    ],
    "presence": {
      "headline": 0.91,
      "brand": 0.24,
      "hero": 0.87,
      "subhead": 0.38,
      "offer": 0.25,
      "body": 0.42,
      "cta": 0.22,
      "detail": 0.27,
      "contact": 0.36
    }
  },
  "other": {
    "briefs": 718,
    "order": [
      "headline",
      "brand",
      "hero",
      "subhead",
      "offer",
      "body",
      "cta",
      "detail",
      "contact"
    ],
    "presence": {
      "headline": 0.91,
      "brand": 0.24,
      "hero": 0.87,
      "subhead": 0.38,
      "offer": 0.25,
      "body": 0.42,
      "cta": 0.22,
      "detail": 0.27,
      "contact": 0.36
    }
  }
};
