import type { ReferenceImage } from "./types";

/**
 * Photographed / scanned references. Every file lives in /public/refs, was
 * downloaded from Wikimedia Commons, resized to ≤900px wide and re-encoded
 * as WebP. Licence data was read from the Commons file page metadata.
 *
 * Captions describe what each image is useful for — they never claim an
 * image is a pure example of a style it merely informs.
 */
export const references: ReferenceImage[] = [
  {
    id: "schwitters-strassenbahnbillet",
    src: "/refs/schwitters-strassenbahnbillet.webp",
    width: 900,
    height: 1199,
    title: "Ohne Titel (Collage mit Straßenbahnbillet)",
    creator: "Kurt Schwitters",
    date: "1927",
    alt: "Paper collage of torn printed papers, a tram ticket and blocks of muted colour on card.",
    caption: "Paper collage built from tickets and printed scraps: layered edges, found type and muted paper tones.",
    licence: "Public domain",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Kurt_Schwitters_Ohne_Titel_(Collage_mit_Stra%C3%9Fenbahnbillet).jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "schwitters-entrance-ticket",
    src: "/refs/schwitters-entrance-ticket.webp",
    width: 900,
    height: 1085,
    title: "Entrance Ticket (Mz 456)",
    creator: "Kurt Schwitters",
    date: "1922",
    alt: "Collage with a large navy torn shape, a yellow letter M, a museum entrance ticket and a cut-out fox illustration.",
    caption: "Torn paper, a museum ticket and fragments of display type overlapping at hard angles.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_Ticket_(Mz_456)_(1922).jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "gottscho-chrysler-1932",
    src: "/refs/gottscho-chrysler-1932.webp",
    width: 900,
    height: 1183,
    title: "Chrysler Building, view from the Empire State Building",
    creator: "Samuel H. Gottscho",
    date: "1932",
    alt: "Black-and-white aerial photograph of the Chrysler Building's stepped, arched spire above Manhattan.",
    caption: "Stepped setbacks and a sunburst-arched crown: the vertical, tiered geometry associated with Art Deco architecture.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chrysler_Building_1932_(cropped).jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "chrysler-lift-door",
    src: "/refs/chrysler-lift-door.webp",
    width: 900,
    height: 1618,
    title: "Lift door, Chrysler Building lobby",
    creator: "Tony Hisgett",
    date: "2011 (photograph)",
    alt: "Ornate lift door with inlaid wood fan and lotus motifs in warm browns and gold.",
    caption: "Inlaid wood, fan motifs and symmetrical ornament on a lobby lift door.",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lift_door_Chrysler_Building_Lobby.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "gottscho-trylon-perisphere",
    src: "/refs/gottscho-trylon-perisphere.webp",
    width: 900,
    height: 1368,
    title: "Trylon and Perisphere, New York World's Fair",
    creator: "Samuel H. Gottscho",
    date: "c. 1939",
    alt: "Black-and-white photograph of a tall white spire and a giant sphere at the 1939 World's Fair.",
    caption: "A 1939 vision of the future: pure white monumental forms. Useful when a futuristic look should feel retro or architectural.",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Trylon_and_Perisphere,_New_York_World%27s_Fair_MET_DP103125.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "paul-amazing-stories-1928-08",
    src: "/refs/paul-amazing-stories-1928-08.webp",
    width: 567,
    height: 779,
    title: "Amazing Stories, August 1928 (cover)",
    creator: "Frank R. Paul",
    date: "1928",
    alt: "Pulp magazine cover with a flying figure in a jet harness above a landscape, bold yellow masthead.",
    caption: "Pulp-era science-fiction illustration: how the future was imagined in 1928, not a contemporary futuristic style.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Amazing_Stories,_August_1928.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "proulx-brass-spider",
    src: "/refs/proulx-brass-spider.webp",
    width: 900,
    height: 900,
    title: "Steampunk clockwork spider",
    creator: "Daniel Proulx (Catherinette Rings Steampunk)",
    date: "2009",
    alt: "Small sculpture of a spider built from brass clock gears and copper wire.",
    caption: "Brass gears, copper wire and exposed clockwork: the material vocabulary of steampunk objects.",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Steampunk_Brass_Spider.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "parseghian-steampunk-radio",
    src: "/refs/parseghian-steampunk-radio.webp",
    width: 900,
    height: 1214,
    title: "Victorian-style steampunk radio",
    creator: "Abraham Parseghian",
    date: "2018",
    alt: "Handmade radio in dark wood with brass dials, valves and exposed mechanical parts.",
    caption: "Solid wood housing, brass fittings and exposed valves on a handmade radio.",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Victorian_Style_Steampunk_Radio.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "imac-g3-bondi",
    src: "/refs/imac-g3-bondi.webp",
    width: 900,
    height: 840,
    title: "iMac G3 (Bondi Blue), three-quarters view",
    creator: "Rama; alterations by David Fuchs",
    date: "Product 1998; photograph 2014",
    alt: "A rounded all-in-one computer in translucent teal-blue and frosted white plastic.",
    caption: "Translucent coloured plastic and soft rounded housings, a key consumer-product reference for Y2K.",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:IMac_G3_Bondi_Blue,_three-quarters_view.png",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "moholy-nagy-komposition-6",
    src: "/refs/moholy-nagy-komposition-6.webp",
    width: 770,
    height: 966,
    title: "Composition, sheet 6 (Masters of the Bauhaus portfolio)",
    creator: "László Moholy-Nagy",
    date: "1923",
    alt: "Abstract print of overlapping circles, bars and translucent planes on a pale ground.",
    caption: "From a 1923 portfolio of prints by Bauhaus teachers: overlapping planes, circles and bars.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Komposition_Sheet_6.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "lissitzky-red-wedge",
    src: "/refs/lissitzky-red-wedge.webp",
    width: 900,
    height: 737,
    title: "Beat the Whites with the Red Wedge",
    creator: "El Lissitzky",
    date: "1919",
    alt: "Poster of a red triangle piercing a white circle on a split black and white ground, with scattered small shapes and text.",
    caption: "A red wedge driving into a white circle: diagonal force, flat primary shapes and integrated lettering.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Beat_the_Whites_with_the_Red_Wedge.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "mucha-job-1896",
    src: "/refs/mucha-job-1896.webp",
    width: 900,
    height: 1188,
    title: "Job (cigarette paper advertisement)",
    creator: "Alphonse Mucha",
    date: "1896",
    alt: "Poster of a woman with swirling, flowing hair framed by an ornamental monogram border.",
    caption: "Whiplash curves of hair, a decorative frame and hand-drawn lettering in soft ochres.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mucha-job.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "rousseau-the-dream",
    src: "/refs/rousseau-the-dream.webp",
    width: 900,
    height: 612,
    title: "The Dream (Le Rêve)",
    creator: "Henri Rousseau",
    date: "1910",
    alt: "Painting of a dense jungle of flat, patterned leaves with animals and a reclining figure on a sofa.",
    caption: "Flat, carefully outlined foliage and frontal figures by a self-taught painter often grouped with naïve art.",
    licence: "Public domain",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Henri_Rousseau_-_Le_R%C3%AAve_-_Google_Art_Project.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "mondrian-composition-ii-1930",
    src: "/refs/mondrian-composition-ii-1930.webp",
    width: 900,
    height: 913,
    title: "Composition II in Red, Blue, and Yellow",
    creator: "Piet Mondrian",
    date: "1930",
    alt: "Painting of a white field divided by thick black lines with a large red square and small blue and yellow blocks.",
    caption: "Black lines dividing a white field with primary blocks, a touchstone for modernist reduction.",
    licence: "Public domain",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Piet_Mondriaan,_1930_-_Mondrian_Composition_II_in_Red,_Blue,_and_Yellow.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "cologne-cathedral-interior",
    src: "/refs/cologne-cathedral-interior.webp",
    width: 900,
    height: 1329,
    title: "Interior view of Cologne Cathedral",
    creator: "Kaap bij Sneeuw",
    date: "2026 (photograph)",
    alt: "Tall pointed arches and ribbed vaults of a Gothic cathedral interior in grey stone.",
    caption: "Pointed arches, ribbed vaults and extreme verticality in Gothic architecture.",
    licence: "CC0 1.0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Interior_view_of_Cologne_Cathedral_May_of_2026.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "huffman-barbican",
    src: "/refs/huffman-barbican.webp",
    width: 900,
    height: 1354,
    title: "Barbican Estate, London",
    creator: "Todd Huffman",
    date: "2007 (photograph)",
    alt: "Concrete residential tower with repeated balconies and deeply textured surfaces.",
    caption: "Board-marked and bush-hammered concrete, repeated balconies and heavy massing.",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Barbican_(1022671240).jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
  {
    id: "morris-strawberry-thief",
    src: "/refs/morris-strawberry-thief.webp",
    width: 900,
    height: 584,
    title: "Strawberry Thief (printed textile)",
    creator: "William Morris",
    date: "1883",
    alt: "Symmetrical textile pattern of thrushes and strawberry plants on deep indigo.",
    caption: "A dense, symmetrical Victorian-era repeat of birds and plants on indigo.",
    licence: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Morris_Strawberry_Thief_1883.jpg",
    sourceName: "Wikimedia Commons",
    placeholder: false,
  },
];

const byId = new Map(references.map((r) => [r.id, r]));

export function getReference(id: string): ReferenceImage | undefined {
  return byId.get(id);
}
